timeout: 1200s
steps:
  - name: 'docker/compose:1.19.0'
    args: ['up' , '--exit-code-from' , 'tests']

  - name: 'gcr.io/cloud-builders/gsutil'
    args: ['cp', '$_CONFIG_API_URL', './config.json']

  - name: 'gcr.io/cloud-builders/docker'
    args: ['build', '-t','gcr.io/$PROJECT_ID/service-promotion:$COMMIT_SHA', '.']

  # Push the image to Container Registry
  - name: 'gcr.io/cloud-builders/docker'
    args: ['push', 'gcr.io/$PROJECT_ID/service-promotion:$COMMIT_SHA']

  - name: "gcr.io/cloud-builders/gke-deploy"
    args:
      - run
      - --filename=./deployments/deployment.yaml
      - --image=gcr.io/$PROJECT_ID/service-promotion:$COMMIT_SHA
      - --location=$_LOCATION
      - --cluster=$_GKE_CLUSTER