// Code generated by protoc-gen-go. DO NOT EDIT.
// source: service_transaction/service.proto

package service_transaction

import proto "github.com/golang/protobuf/proto"
import fmt "fmt"
import math "math"

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion2 // please upgrade the proto package

type InitMerchantAccountReq struct {
	MerchantId           string   `protobuf:"bytes,1,opt,name=merchant_id,json=merchantId,proto3" json:"merchant_id,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *InitMerchantAccountReq) Reset()         { *m = InitMerchantAccountReq{} }
func (m *InitMerchantAccountReq) String() string { return proto.CompactTextString(m) }
func (*InitMerchantAccountReq) ProtoMessage()    {}
func (*InitMerchantAccountReq) Descriptor() ([]byte, []int) {
	return fileDescriptor_service_9ea794d30e59b71a, []int{0}
}
func (m *InitMerchantAccountReq) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_InitMerchantAccountReq.Unmarshal(m, b)
}
func (m *InitMerchantAccountReq) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_InitMerchantAccountReq.Marshal(b, m, deterministic)
}
func (dst *InitMerchantAccountReq) XXX_Merge(src proto.Message) {
	xxx_messageInfo_InitMerchantAccountReq.Merge(dst, src)
}
func (m *InitMerchantAccountReq) XXX_Size() int {
	return xxx_messageInfo_InitMerchantAccountReq.Size(m)
}
func (m *InitMerchantAccountReq) XXX_DiscardUnknown() {
	xxx_messageInfo_InitMerchantAccountReq.DiscardUnknown(m)
}

var xxx_messageInfo_InitMerchantAccountReq proto.InternalMessageInfo

func (m *InitMerchantAccountReq) GetMerchantId() string {
	if m != nil {
		return m.MerchantId
	}
	return ""
}

type AccountingPromotionRequest struct {
	PromotionID          string   `protobuf:"bytes,1,opt,name=PromotionID,proto3" json:"PromotionID,omitempty"`
	Amount               int64    `protobuf:"varint,2,opt,name=Amount,proto3" json:"Amount,omitempty"`
	TypeWallet           string   `protobuf:"bytes,3,opt,name=TypeWallet,proto3" json:"TypeWallet,omitempty"`
	RequestID            string   `protobuf:"bytes,4,opt,name=RequestID,proto3" json:"RequestID,omitempty"`
	Inventory            int64    `protobuf:"varint,5,opt,name=Inventory,proto3" json:"Inventory,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *AccountingPromotionRequest) Reset()         { *m = AccountingPromotionRequest{} }
func (m *AccountingPromotionRequest) String() string { return proto.CompactTextString(m) }
func (*AccountingPromotionRequest) ProtoMessage()    {}
func (*AccountingPromotionRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_service_9ea794d30e59b71a, []int{1}
}
func (m *AccountingPromotionRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_AccountingPromotionRequest.Unmarshal(m, b)
}
func (m *AccountingPromotionRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_AccountingPromotionRequest.Marshal(b, m, deterministic)
}
func (dst *AccountingPromotionRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_AccountingPromotionRequest.Merge(dst, src)
}
func (m *AccountingPromotionRequest) XXX_Size() int {
	return xxx_messageInfo_AccountingPromotionRequest.Size(m)
}
func (m *AccountingPromotionRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_AccountingPromotionRequest.DiscardUnknown(m)
}

var xxx_messageInfo_AccountingPromotionRequest proto.InternalMessageInfo

func (m *AccountingPromotionRequest) GetPromotionID() string {
	if m != nil {
		return m.PromotionID
	}
	return ""
}

func (m *AccountingPromotionRequest) GetAmount() int64 {
	if m != nil {
		return m.Amount
	}
	return 0
}

func (m *AccountingPromotionRequest) GetTypeWallet() string {
	if m != nil {
		return m.TypeWallet
	}
	return ""
}

func (m *AccountingPromotionRequest) GetRequestID() string {
	if m != nil {
		return m.RequestID
	}
	return ""
}

func (m *AccountingPromotionRequest) GetInventory() int64 {
	if m != nil {
		return m.Inventory
	}
	return 0
}

type WithdrawWalletRequest struct {
	BankCode             string   `protobuf:"bytes,1,opt,name=BankCode,proto3" json:"BankCode,omitempty"`
	BankTypeWallet       string   `protobuf:"bytes,2,opt,name=BankTypeWallet,proto3" json:"BankTypeWallet,omitempty"`
	Message              string   `protobuf:"bytes,3,opt,name=Message,proto3" json:"Message,omitempty"`
	GpayID               string   `protobuf:"bytes,4,opt,name=GpayID,proto3" json:"GpayID,omitempty"`
	MerchantID           string   `protobuf:"bytes,5,opt,name=MerchantID,proto3" json:"MerchantID,omitempty"`
	RequestId            string   `protobuf:"bytes,6,opt,name=RequestId,proto3" json:"RequestId,omitempty"`
	Amount               int64    `protobuf:"varint,7,opt,name=Amount,proto3" json:"Amount,omitempty"`
	Source               string   `protobuf:"bytes,8,opt,name=Source,proto3" json:"Source,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *WithdrawWalletRequest) Reset()         { *m = WithdrawWalletRequest{} }
func (m *WithdrawWalletRequest) String() string { return proto.CompactTextString(m) }
func (*WithdrawWalletRequest) ProtoMessage()    {}
func (*WithdrawWalletRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_service_9ea794d30e59b71a, []int{2}
}
func (m *WithdrawWalletRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_WithdrawWalletRequest.Unmarshal(m, b)
}
func (m *WithdrawWalletRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_WithdrawWalletRequest.Marshal(b, m, deterministic)
}
func (dst *WithdrawWalletRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_WithdrawWalletRequest.Merge(dst, src)
}
func (m *WithdrawWalletRequest) XXX_Size() int {
	return xxx_messageInfo_WithdrawWalletRequest.Size(m)
}
func (m *WithdrawWalletRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_WithdrawWalletRequest.DiscardUnknown(m)
}

var xxx_messageInfo_WithdrawWalletRequest proto.InternalMessageInfo

func (m *WithdrawWalletRequest) GetBankCode() string {
	if m != nil {
		return m.BankCode
	}
	return ""
}

func (m *WithdrawWalletRequest) GetBankTypeWallet() string {
	if m != nil {
		return m.BankTypeWallet
	}
	return ""
}

func (m *WithdrawWalletRequest) GetMessage() string {
	if m != nil {
		return m.Message
	}
	return ""
}

func (m *WithdrawWalletRequest) GetGpayID() string {
	if m != nil {
		return m.GpayID
	}
	return ""
}

func (m *WithdrawWalletRequest) GetMerchantID() string {
	if m != nil {
		return m.MerchantID
	}
	return ""
}

func (m *WithdrawWalletRequest) GetRequestId() string {
	if m != nil {
		return m.RequestId
	}
	return ""
}

func (m *WithdrawWalletRequest) GetAmount() int64 {
	if m != nil {
		return m.Amount
	}
	return 0
}

func (m *WithdrawWalletRequest) GetSource() string {
	if m != nil {
		return m.Source
	}
	return ""
}

type DepositGpayRequest struct {
	GPAYID               string   `protobuf:"bytes,1,opt,name=GPAYID,proto3" json:"GPAYID,omitempty"`
	Wallet               string   `protobuf:"bytes,2,opt,name=Wallet,proto3" json:"Wallet,omitempty"`
	Amount               int64    `protobuf:"varint,3,opt,name=Amount,proto3" json:"Amount,omitempty"`
	BankCode             string   `protobuf:"bytes,4,opt,name=BankCode,proto3" json:"BankCode,omitempty"`
	RequestID            string   `protobuf:"bytes,5,opt,name=RequestID,proto3" json:"RequestID,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *DepositGpayRequest) Reset()         { *m = DepositGpayRequest{} }
func (m *DepositGpayRequest) String() string { return proto.CompactTextString(m) }
func (*DepositGpayRequest) ProtoMessage()    {}
func (*DepositGpayRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_service_9ea794d30e59b71a, []int{3}
}
func (m *DepositGpayRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_DepositGpayRequest.Unmarshal(m, b)
}
func (m *DepositGpayRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_DepositGpayRequest.Marshal(b, m, deterministic)
}
func (dst *DepositGpayRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_DepositGpayRequest.Merge(dst, src)
}
func (m *DepositGpayRequest) XXX_Size() int {
	return xxx_messageInfo_DepositGpayRequest.Size(m)
}
func (m *DepositGpayRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_DepositGpayRequest.DiscardUnknown(m)
}

var xxx_messageInfo_DepositGpayRequest proto.InternalMessageInfo

func (m *DepositGpayRequest) GetGPAYID() string {
	if m != nil {
		return m.GPAYID
	}
	return ""
}

func (m *DepositGpayRequest) GetWallet() string {
	if m != nil {
		return m.Wallet
	}
	return ""
}

func (m *DepositGpayRequest) GetAmount() int64 {
	if m != nil {
		return m.Amount
	}
	return 0
}

func (m *DepositGpayRequest) GetBankCode() string {
	if m != nil {
		return m.BankCode
	}
	return ""
}

func (m *DepositGpayRequest) GetRequestID() string {
	if m != nil {
		return m.RequestID
	}
	return ""
}

// Request
type ProcessCashbackRequest struct {
	TransactionId        string   `protobuf:"bytes,1,opt,name=transactionId,proto3" json:"transactionId,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *ProcessCashbackRequest) Reset()         { *m = ProcessCashbackRequest{} }
func (m *ProcessCashbackRequest) String() string { return proto.CompactTextString(m) }
func (*ProcessCashbackRequest) ProtoMessage()    {}
func (*ProcessCashbackRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_service_9ea794d30e59b71a, []int{4}
}
func (m *ProcessCashbackRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ProcessCashbackRequest.Unmarshal(m, b)
}
func (m *ProcessCashbackRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ProcessCashbackRequest.Marshal(b, m, deterministic)
}
func (dst *ProcessCashbackRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ProcessCashbackRequest.Merge(dst, src)
}
func (m *ProcessCashbackRequest) XXX_Size() int {
	return xxx_messageInfo_ProcessCashbackRequest.Size(m)
}
func (m *ProcessCashbackRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_ProcessCashbackRequest.DiscardUnknown(m)
}

var xxx_messageInfo_ProcessCashbackRequest proto.InternalMessageInfo

func (m *ProcessCashbackRequest) GetTransactionId() string {
	if m != nil {
		return m.TransactionId
	}
	return ""
}

type FindByTransactionIdRequest struct {
	Id                   string   `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *FindByTransactionIdRequest) Reset()         { *m = FindByTransactionIdRequest{} }
func (m *FindByTransactionIdRequest) String() string { return proto.CompactTextString(m) }
func (*FindByTransactionIdRequest) ProtoMessage()    {}
func (*FindByTransactionIdRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_service_9ea794d30e59b71a, []int{5}
}
func (m *FindByTransactionIdRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_FindByTransactionIdRequest.Unmarshal(m, b)
}
func (m *FindByTransactionIdRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_FindByTransactionIdRequest.Marshal(b, m, deterministic)
}
func (dst *FindByTransactionIdRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_FindByTransactionIdRequest.Merge(dst, src)
}
func (m *FindByTransactionIdRequest) XXX_Size() int {
	return xxx_messageInfo_FindByTransactionIdRequest.Size(m)
}
func (m *FindByTransactionIdRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_FindByTransactionIdRequest.DiscardUnknown(m)
}

var xxx_messageInfo_FindByTransactionIdRequest proto.InternalMessageInfo

func (m *FindByTransactionIdRequest) GetId() string {
	if m != nil {
		return m.Id
	}
	return ""
}

type ChangeStatusCheckingRequest struct {
	Ids                  []string `protobuf:"bytes,1,rep,name=ids,proto3" json:"ids,omitempty"`
	StatusChecking       string   `protobuf:"bytes,2,opt,name=statusChecking,proto3" json:"statusChecking,omitempty"`
	StatusCodeChecking   string   `protobuf:"bytes,3,opt,name=statusCodeChecking,proto3" json:"statusCodeChecking,omitempty"`
	TimeChecking         int64    `protobuf:"varint,4,opt,name=timeChecking,proto3" json:"timeChecking,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *ChangeStatusCheckingRequest) Reset()         { *m = ChangeStatusCheckingRequest{} }
func (m *ChangeStatusCheckingRequest) String() string { return proto.CompactTextString(m) }
func (*ChangeStatusCheckingRequest) ProtoMessage()    {}
func (*ChangeStatusCheckingRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_service_9ea794d30e59b71a, []int{6}
}
func (m *ChangeStatusCheckingRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ChangeStatusCheckingRequest.Unmarshal(m, b)
}
func (m *ChangeStatusCheckingRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ChangeStatusCheckingRequest.Marshal(b, m, deterministic)
}
func (dst *ChangeStatusCheckingRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ChangeStatusCheckingRequest.Merge(dst, src)
}
func (m *ChangeStatusCheckingRequest) XXX_Size() int {
	return xxx_messageInfo_ChangeStatusCheckingRequest.Size(m)
}
func (m *ChangeStatusCheckingRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_ChangeStatusCheckingRequest.DiscardUnknown(m)
}

var xxx_messageInfo_ChangeStatusCheckingRequest proto.InternalMessageInfo

func (m *ChangeStatusCheckingRequest) GetIds() []string {
	if m != nil {
		return m.Ids
	}
	return nil
}

func (m *ChangeStatusCheckingRequest) GetStatusChecking() string {
	if m != nil {
		return m.StatusChecking
	}
	return ""
}

func (m *ChangeStatusCheckingRequest) GetStatusCodeChecking() string {
	if m != nil {
		return m.StatusCodeChecking
	}
	return ""
}

func (m *ChangeStatusCheckingRequest) GetTimeChecking() int64 {
	if m != nil {
		return m.TimeChecking
	}
	return 0
}

type ChangeStatusSettlementRequest struct {
	Ids                  []string `protobuf:"bytes,1,rep,name=ids,proto3" json:"ids,omitempty"`
	StatusSettlement     string   `protobuf:"bytes,2,opt,name=statusSettlement,proto3" json:"statusSettlement,omitempty"`
	TimeSettlement       int64    `protobuf:"varint,3,opt,name=timeSettlement,proto3" json:"timeSettlement,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *ChangeStatusSettlementRequest) Reset()         { *m = ChangeStatusSettlementRequest{} }
func (m *ChangeStatusSettlementRequest) String() string { return proto.CompactTextString(m) }
func (*ChangeStatusSettlementRequest) ProtoMessage()    {}
func (*ChangeStatusSettlementRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_service_9ea794d30e59b71a, []int{7}
}
func (m *ChangeStatusSettlementRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ChangeStatusSettlementRequest.Unmarshal(m, b)
}
func (m *ChangeStatusSettlementRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ChangeStatusSettlementRequest.Marshal(b, m, deterministic)
}
func (dst *ChangeStatusSettlementRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ChangeStatusSettlementRequest.Merge(dst, src)
}
func (m *ChangeStatusSettlementRequest) XXX_Size() int {
	return xxx_messageInfo_ChangeStatusSettlementRequest.Size(m)
}
func (m *ChangeStatusSettlementRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_ChangeStatusSettlementRequest.DiscardUnknown(m)
}

var xxx_messageInfo_ChangeStatusSettlementRequest proto.InternalMessageInfo

func (m *ChangeStatusSettlementRequest) GetIds() []string {
	if m != nil {
		return m.Ids
	}
	return nil
}

func (m *ChangeStatusSettlementRequest) GetStatusSettlement() string {
	if m != nil {
		return m.StatusSettlement
	}
	return ""
}

func (m *ChangeStatusSettlementRequest) GetTimeSettlement() int64 {
	if m != nil {
		return m.TimeSettlement
	}
	return 0
}

type AccountingPromotionDepositRequest struct {
	// Là nạp tiền vào ví khi có merchantID
	MerchantID string `protobuf:"bytes,1,opt,name=MerchantID,proto3" json:"MerchantID,omitempty"`
	// Là hạch toán tiền vận hành GPAY
	GPAYID                  string   `protobuf:"bytes,2,opt,name=GPAYID,proto3" json:"GPAYID,omitempty"`
	PromotionID             string   `protobuf:"bytes,3,opt,name=PromotionID,proto3" json:"PromotionID,omitempty"`
	PromotionName           string   `protobuf:"bytes,4,opt,name=PromotionName,proto3" json:"PromotionName,omitempty"`
	PromotionAmount         int64    `protobuf:"varint,5,opt,name=PromotionAmount,proto3" json:"PromotionAmount,omitempty"`
	PromotionCode           string   `protobuf:"bytes,6,opt,name=PromotionCode,proto3" json:"PromotionCode,omitempty"`
	TotalPromotionInventory int64    `protobuf:"varint,7,opt,name=TotalPromotionInventory,proto3" json:"TotalPromotionInventory,omitempty"`
	MaxPaidAmount           int64    `protobuf:"varint,8,opt,name=MaxPaidAmount,proto3" json:"MaxPaidAmount,omitempty"`
	RequestID               string   `protobuf:"bytes,9,opt,name=RequestID,proto3" json:"RequestID,omitempty"`
	XXX_NoUnkeyedLiteral    struct{} `json:"-"`
	XXX_unrecognized        []byte   `json:"-"`
	XXX_sizecache           int32    `json:"-"`
}

func (m *AccountingPromotionDepositRequest) Reset()         { *m = AccountingPromotionDepositRequest{} }
func (m *AccountingPromotionDepositRequest) String() string { return proto.CompactTextString(m) }
func (*AccountingPromotionDepositRequest) ProtoMessage()    {}
func (*AccountingPromotionDepositRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_service_9ea794d30e59b71a, []int{8}
}
func (m *AccountingPromotionDepositRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_AccountingPromotionDepositRequest.Unmarshal(m, b)
}
func (m *AccountingPromotionDepositRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_AccountingPromotionDepositRequest.Marshal(b, m, deterministic)
}
func (dst *AccountingPromotionDepositRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_AccountingPromotionDepositRequest.Merge(dst, src)
}
func (m *AccountingPromotionDepositRequest) XXX_Size() int {
	return xxx_messageInfo_AccountingPromotionDepositRequest.Size(m)
}
func (m *AccountingPromotionDepositRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_AccountingPromotionDepositRequest.DiscardUnknown(m)
}

var xxx_messageInfo_AccountingPromotionDepositRequest proto.InternalMessageInfo

func (m *AccountingPromotionDepositRequest) GetMerchantID() string {
	if m != nil {
		return m.MerchantID
	}
	return ""
}

func (m *AccountingPromotionDepositRequest) GetGPAYID() string {
	if m != nil {
		return m.GPAYID
	}
	return ""
}

func (m *AccountingPromotionDepositRequest) GetPromotionID() string {
	if m != nil {
		return m.PromotionID
	}
	return ""
}

func (m *AccountingPromotionDepositRequest) GetPromotionName() string {
	if m != nil {
		return m.PromotionName
	}
	return ""
}

func (m *AccountingPromotionDepositRequest) GetPromotionAmount() int64 {
	if m != nil {
		return m.PromotionAmount
	}
	return 0
}

func (m *AccountingPromotionDepositRequest) GetPromotionCode() string {
	if m != nil {
		return m.PromotionCode
	}
	return ""
}

func (m *AccountingPromotionDepositRequest) GetTotalPromotionInventory() int64 {
	if m != nil {
		return m.TotalPromotionInventory
	}
	return 0
}

func (m *AccountingPromotionDepositRequest) GetMaxPaidAmount() int64 {
	if m != nil {
		return m.MaxPaidAmount
	}
	return 0
}

func (m *AccountingPromotionDepositRequest) GetRequestID() string {
	if m != nil {
		return m.RequestID
	}
	return ""
}

type AccountingPromotionWithdrawRequest struct {
	// Là nạp tiền vào ví khi có merchantID
	MerchantID string `protobuf:"bytes,1,opt,name=MerchantID,proto3" json:"MerchantID,omitempty"`
	// Là hạch toán tiền vận hành GPAY
	GPAYID               string   `protobuf:"bytes,2,opt,name=GPAYID,proto3" json:"GPAYID,omitempty"`
	PromotionID          string   `protobuf:"bytes,3,opt,name=PromotionID,proto3" json:"PromotionID,omitempty"`
	PromotionAmount      int64    `protobuf:"varint,5,opt,name=PromotionAmount,proto3" json:"PromotionAmount,omitempty"`
	RequestID            string   `protobuf:"bytes,9,opt,name=RequestID,proto3" json:"RequestID,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *AccountingPromotionWithdrawRequest) Reset()         { *m = AccountingPromotionWithdrawRequest{} }
func (m *AccountingPromotionWithdrawRequest) String() string { return proto.CompactTextString(m) }
func (*AccountingPromotionWithdrawRequest) ProtoMessage()    {}
func (*AccountingPromotionWithdrawRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_service_9ea794d30e59b71a, []int{9}
}
func (m *AccountingPromotionWithdrawRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_AccountingPromotionWithdrawRequest.Unmarshal(m, b)
}
func (m *AccountingPromotionWithdrawRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_AccountingPromotionWithdrawRequest.Marshal(b, m, deterministic)
}
func (dst *AccountingPromotionWithdrawRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_AccountingPromotionWithdrawRequest.Merge(dst, src)
}
func (m *AccountingPromotionWithdrawRequest) XXX_Size() int {
	return xxx_messageInfo_AccountingPromotionWithdrawRequest.Size(m)
}
func (m *AccountingPromotionWithdrawRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_AccountingPromotionWithdrawRequest.DiscardUnknown(m)
}

var xxx_messageInfo_AccountingPromotionWithdrawRequest proto.InternalMessageInfo

func (m *AccountingPromotionWithdrawRequest) GetMerchantID() string {
	if m != nil {
		return m.MerchantID
	}
	return ""
}

func (m *AccountingPromotionWithdrawRequest) GetGPAYID() string {
	if m != nil {
		return m.GPAYID
	}
	return ""
}

func (m *AccountingPromotionWithdrawRequest) GetPromotionID() string {
	if m != nil {
		return m.PromotionID
	}
	return ""
}

func (m *AccountingPromotionWithdrawRequest) GetPromotionAmount() int64 {
	if m != nil {
		return m.PromotionAmount
	}
	return 0
}

func (m *AccountingPromotionWithdrawRequest) GetRequestID() string {
	if m != nil {
		return m.RequestID
	}
	return ""
}

type AccountingChangeGpayRequest struct {
	GPAYID               string   `protobuf:"bytes,1,opt,name=GPAYID,proto3" json:"GPAYID,omitempty"`
	SrcWallet            string   `protobuf:"bytes,2,opt,name=SrcWallet,proto3" json:"SrcWallet,omitempty"`
	DestWallet           string   `protobuf:"bytes,3,opt,name=DestWallet,proto3" json:"DestWallet,omitempty"`
	Amount               int64    `protobuf:"varint,5,opt,name=Amount,proto3" json:"Amount,omitempty"`
	RequestID            string   `protobuf:"bytes,6,opt,name=RequestID,proto3" json:"RequestID,omitempty"`
	TypeChange           string   `protobuf:"bytes,7,opt,name=TypeChange,proto3" json:"TypeChange,omitempty"`
	Message              string   `protobuf:"bytes,8,opt,name=Message,proto3" json:"Message,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *AccountingChangeGpayRequest) Reset()         { *m = AccountingChangeGpayRequest{} }
func (m *AccountingChangeGpayRequest) String() string { return proto.CompactTextString(m) }
func (*AccountingChangeGpayRequest) ProtoMessage()    {}
func (*AccountingChangeGpayRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_service_9ea794d30e59b71a, []int{10}
}
func (m *AccountingChangeGpayRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_AccountingChangeGpayRequest.Unmarshal(m, b)
}
func (m *AccountingChangeGpayRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_AccountingChangeGpayRequest.Marshal(b, m, deterministic)
}
func (dst *AccountingChangeGpayRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_AccountingChangeGpayRequest.Merge(dst, src)
}
func (m *AccountingChangeGpayRequest) XXX_Size() int {
	return xxx_messageInfo_AccountingChangeGpayRequest.Size(m)
}
func (m *AccountingChangeGpayRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_AccountingChangeGpayRequest.DiscardUnknown(m)
}

var xxx_messageInfo_AccountingChangeGpayRequest proto.InternalMessageInfo

func (m *AccountingChangeGpayRequest) GetGPAYID() string {
	if m != nil {
		return m.GPAYID
	}
	return ""
}

func (m *AccountingChangeGpayRequest) GetSrcWallet() string {
	if m != nil {
		return m.SrcWallet
	}
	return ""
}

func (m *AccountingChangeGpayRequest) GetDestWallet() string {
	if m != nil {
		return m.DestWallet
	}
	return ""
}

func (m *AccountingChangeGpayRequest) GetAmount() int64 {
	if m != nil {
		return m.Amount
	}
	return 0
}

func (m *AccountingChangeGpayRequest) GetRequestID() string {
	if m != nil {
		return m.RequestID
	}
	return ""
}

func (m *AccountingChangeGpayRequest) GetTypeChange() string {
	if m != nil {
		return m.TypeChange
	}
	return ""
}

func (m *AccountingChangeGpayRequest) GetMessage() string {
	if m != nil {
		return m.Message
	}
	return ""
}

type AccountingSettlementRequest struct {
	// typeSettlementRequest = MONTH
	TotalArrearsAmount int64 `protobuf:"varint,1,opt,name=totalArrearsAmount,proto3" json:"totalArrearsAmount,omitempty"`
	// typeSettlementRequest = MONTH
	TotalRetrievalAmount int64 `protobuf:"varint,2,opt,name=totalRetrievalAmount,proto3" json:"totalRetrievalAmount,omitempty"`
	// typeSettlementRequest = DAY
	ActuallyReceiveAmount int64 `protobuf:"varint,3,opt,name=actuallyReceiveAmount,proto3" json:"actuallyReceiveAmount,omitempty"`
	// typeSettlementRequest = DAY
	AmountFeeMerchantGpayImpl int64  `protobuf:"varint,4,opt,name=amountFeeMerchantGpayImpl,proto3" json:"amountFeeMerchantGpayImpl,omitempty"`
	ServiceType               string `protobuf:"bytes,5,opt,name=serviceType,proto3" json:"serviceType,omitempty"`
	TransactionType           string `protobuf:"bytes,6,opt,name=transactionType,proto3" json:"transactionType,omitempty"`
	SubTransactionType        string `protobuf:"bytes,7,opt,name=subTransactionType,proto3" json:"subTransactionType,omitempty"`
	MerchantID                string `protobuf:"bytes,8,opt,name=merchantID,proto3" json:"merchantID,omitempty"`
	// DAY || MONTH
	TypeSettlementRequest string   `protobuf:"bytes,9,opt,name=typeSettlementRequest,proto3" json:"typeSettlementRequest,omitempty"`
	SettlementID          string   `protobuf:"bytes,10,opt,name=SettlementID,proto3" json:"SettlementID,omitempty"`
	XXX_NoUnkeyedLiteral  struct{} `json:"-"`
	XXX_unrecognized      []byte   `json:"-"`
	XXX_sizecache         int32    `json:"-"`
}

func (m *AccountingSettlementRequest) Reset()         { *m = AccountingSettlementRequest{} }
func (m *AccountingSettlementRequest) String() string { return proto.CompactTextString(m) }
func (*AccountingSettlementRequest) ProtoMessage()    {}
func (*AccountingSettlementRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_service_9ea794d30e59b71a, []int{11}
}
func (m *AccountingSettlementRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_AccountingSettlementRequest.Unmarshal(m, b)
}
func (m *AccountingSettlementRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_AccountingSettlementRequest.Marshal(b, m, deterministic)
}
func (dst *AccountingSettlementRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_AccountingSettlementRequest.Merge(dst, src)
}
func (m *AccountingSettlementRequest) XXX_Size() int {
	return xxx_messageInfo_AccountingSettlementRequest.Size(m)
}
func (m *AccountingSettlementRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_AccountingSettlementRequest.DiscardUnknown(m)
}

var xxx_messageInfo_AccountingSettlementRequest proto.InternalMessageInfo

func (m *AccountingSettlementRequest) GetTotalArrearsAmount() int64 {
	if m != nil {
		return m.TotalArrearsAmount
	}
	return 0
}

func (m *AccountingSettlementRequest) GetTotalRetrievalAmount() int64 {
	if m != nil {
		return m.TotalRetrievalAmount
	}
	return 0
}

func (m *AccountingSettlementRequest) GetActuallyReceiveAmount() int64 {
	if m != nil {
		return m.ActuallyReceiveAmount
	}
	return 0
}

func (m *AccountingSettlementRequest) GetAmountFeeMerchantGpayImpl() int64 {
	if m != nil {
		return m.AmountFeeMerchantGpayImpl
	}
	return 0
}

func (m *AccountingSettlementRequest) GetServiceType() string {
	if m != nil {
		return m.ServiceType
	}
	return ""
}

func (m *AccountingSettlementRequest) GetTransactionType() string {
	if m != nil {
		return m.TransactionType
	}
	return ""
}

func (m *AccountingSettlementRequest) GetSubTransactionType() string {
	if m != nil {
		return m.SubTransactionType
	}
	return ""
}

func (m *AccountingSettlementRequest) GetMerchantID() string {
	if m != nil {
		return m.MerchantID
	}
	return ""
}

func (m *AccountingSettlementRequest) GetTypeSettlementRequest() string {
	if m != nil {
		return m.TypeSettlementRequest
	}
	return ""
}

func (m *AccountingSettlementRequest) GetSettlementID() string {
	if m != nil {
		return m.SettlementID
	}
	return ""
}

type TransactionRequest struct {
	Id                   string   `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	PayerId              string   `protobuf:"bytes,2,opt,name=payerId,proto3" json:"payerId,omitempty"`
	Amount               uint64   `protobuf:"varint,3,opt,name=amount,proto3" json:"amount,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *TransactionRequest) Reset()         { *m = TransactionRequest{} }
func (m *TransactionRequest) String() string { return proto.CompactTextString(m) }
func (*TransactionRequest) ProtoMessage()    {}
func (*TransactionRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_service_9ea794d30e59b71a, []int{12}
}
func (m *TransactionRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_TransactionRequest.Unmarshal(m, b)
}
func (m *TransactionRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_TransactionRequest.Marshal(b, m, deterministic)
}
func (dst *TransactionRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_TransactionRequest.Merge(dst, src)
}
func (m *TransactionRequest) XXX_Size() int {
	return xxx_messageInfo_TransactionRequest.Size(m)
}
func (m *TransactionRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_TransactionRequest.DiscardUnknown(m)
}

var xxx_messageInfo_TransactionRequest proto.InternalMessageInfo

func (m *TransactionRequest) GetId() string {
	if m != nil {
		return m.Id
	}
	return ""
}

func (m *TransactionRequest) GetPayerId() string {
	if m != nil {
		return m.PayerId
	}
	return ""
}

func (m *TransactionRequest) GetAmount() uint64 {
	if m != nil {
		return m.Amount
	}
	return 0
}

type CheckPendingTransactionRequest struct {
	UserId               string   `protobuf:"bytes,1,opt,name=userId,proto3" json:"userId,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *CheckPendingTransactionRequest) Reset()         { *m = CheckPendingTransactionRequest{} }
func (m *CheckPendingTransactionRequest) String() string { return proto.CompactTextString(m) }
func (*CheckPendingTransactionRequest) ProtoMessage()    {}
func (*CheckPendingTransactionRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_service_9ea794d30e59b71a, []int{13}
}
func (m *CheckPendingTransactionRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_CheckPendingTransactionRequest.Unmarshal(m, b)
}
func (m *CheckPendingTransactionRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_CheckPendingTransactionRequest.Marshal(b, m, deterministic)
}
func (dst *CheckPendingTransactionRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_CheckPendingTransactionRequest.Merge(dst, src)
}
func (m *CheckPendingTransactionRequest) XXX_Size() int {
	return xxx_messageInfo_CheckPendingTransactionRequest.Size(m)
}
func (m *CheckPendingTransactionRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_CheckPendingTransactionRequest.DiscardUnknown(m)
}

var xxx_messageInfo_CheckPendingTransactionRequest proto.InternalMessageInfo

func (m *CheckPendingTransactionRequest) GetUserId() string {
	if m != nil {
		return m.UserId
	}
	return ""
}

type FindByTransactionIdResponse struct {
	Transaction          *TransactionDetail `protobuf:"bytes,1,opt,name=transaction,proto3" json:"transaction,omitempty"`
	XXX_NoUnkeyedLiteral struct{}           `json:"-"`
	XXX_unrecognized     []byte             `json:"-"`
	XXX_sizecache        int32              `json:"-"`
}

func (m *FindByTransactionIdResponse) Reset()         { *m = FindByTransactionIdResponse{} }
func (m *FindByTransactionIdResponse) String() string { return proto.CompactTextString(m) }
func (*FindByTransactionIdResponse) ProtoMessage()    {}
func (*FindByTransactionIdResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_service_9ea794d30e59b71a, []int{14}
}
func (m *FindByTransactionIdResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_FindByTransactionIdResponse.Unmarshal(m, b)
}
func (m *FindByTransactionIdResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_FindByTransactionIdResponse.Marshal(b, m, deterministic)
}
func (dst *FindByTransactionIdResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_FindByTransactionIdResponse.Merge(dst, src)
}
func (m *FindByTransactionIdResponse) XXX_Size() int {
	return xxx_messageInfo_FindByTransactionIdResponse.Size(m)
}
func (m *FindByTransactionIdResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_FindByTransactionIdResponse.DiscardUnknown(m)
}

var xxx_messageInfo_FindByTransactionIdResponse proto.InternalMessageInfo

func (m *FindByTransactionIdResponse) GetTransaction() *TransactionDetail {
	if m != nil {
		return m.Transaction
	}
	return nil
}

type FilterTransactionRequest struct {
	UserId               string   `protobuf:"bytes,1,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	Type                 string   `protobuf:"bytes,2,opt,name=type,proto3" json:"type,omitempty"`
	Offset               int64    `protobuf:"varint,3,opt,name=offset,proto3" json:"offset,omitempty"`
	Limit                int64    `protobuf:"varint,4,opt,name=limit,proto3" json:"limit,omitempty"`
	State                string   `protobuf:"bytes,5,opt,name=state,proto3" json:"state,omitempty"`
	Status               string   `protobuf:"bytes,6,opt,name=status,proto3" json:"status,omitempty"`
	TypeTransfer         string   `protobuf:"bytes,7,opt,name=typeTransfer,proto3" json:"typeTransfer,omitempty"`
	StarteddAt           int64    `protobuf:"varint,8,opt,name=starteddAt,proto3" json:"starteddAt,omitempty"`
	EndedAt              int64    `protobuf:"varint,9,opt,name=endedAt,proto3" json:"endedAt,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *FilterTransactionRequest) Reset()         { *m = FilterTransactionRequest{} }
func (m *FilterTransactionRequest) String() string { return proto.CompactTextString(m) }
func (*FilterTransactionRequest) ProtoMessage()    {}
func (*FilterTransactionRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_service_9ea794d30e59b71a, []int{15}
}
func (m *FilterTransactionRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_FilterTransactionRequest.Unmarshal(m, b)
}
func (m *FilterTransactionRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_FilterTransactionRequest.Marshal(b, m, deterministic)
}
func (dst *FilterTransactionRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_FilterTransactionRequest.Merge(dst, src)
}
func (m *FilterTransactionRequest) XXX_Size() int {
	return xxx_messageInfo_FilterTransactionRequest.Size(m)
}
func (m *FilterTransactionRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_FilterTransactionRequest.DiscardUnknown(m)
}

var xxx_messageInfo_FilterTransactionRequest proto.InternalMessageInfo

func (m *FilterTransactionRequest) GetUserId() string {
	if m != nil {
		return m.UserId
	}
	return ""
}

func (m *FilterTransactionRequest) GetType() string {
	if m != nil {
		return m.Type
	}
	return ""
}

func (m *FilterTransactionRequest) GetOffset() int64 {
	if m != nil {
		return m.Offset
	}
	return 0
}

func (m *FilterTransactionRequest) GetLimit() int64 {
	if m != nil {
		return m.Limit
	}
	return 0
}

func (m *FilterTransactionRequest) GetState() string {
	if m != nil {
		return m.State
	}
	return ""
}

func (m *FilterTransactionRequest) GetStatus() string {
	if m != nil {
		return m.Status
	}
	return ""
}

func (m *FilterTransactionRequest) GetTypeTransfer() string {
	if m != nil {
		return m.TypeTransfer
	}
	return ""
}

func (m *FilterTransactionRequest) GetStarteddAt() int64 {
	if m != nil {
		return m.StarteddAt
	}
	return 0
}

func (m *FilterTransactionRequest) GetEndedAt() int64 {
	if m != nil {
		return m.EndedAt
	}
	return 0
}

type InitPaymentRequest struct {
	PayerId              string   `protobuf:"bytes,1,opt,name=payer_id,json=payerId,proto3" json:"payer_id,omitempty"`
	PayeeId              string   `protobuf:"bytes,2,opt,name=payee_id,json=payeeId,proto3" json:"payee_id,omitempty"`
	VoucherCode          string   `protobuf:"bytes,3,opt,name=voucher_code,json=voucherCode,proto3" json:"voucher_code,omitempty"`
	TypeTransaction      string   `protobuf:"bytes,4,opt,name=type_transaction,json=typeTransaction,proto3" json:"type_transaction,omitempty"`
	Message              string   `protobuf:"bytes,5,opt,name=message,proto3" json:"message,omitempty"`
	DeviceId             string   `protobuf:"bytes,6,opt,name=device_id,json=deviceId,proto3" json:"device_id,omitempty"`
	TypeTransfer         string   `protobuf:"bytes,7,opt,name=type_transfer,json=typeTransfer,proto3" json:"type_transfer,omitempty"`
	Currency             string   `protobuf:"bytes,8,opt,name=currency,proto3" json:"currency,omitempty"`
	MerchantCode         string   `protobuf:"bytes,9,opt,name=merchant_code,json=merchantCode,proto3" json:"merchant_code,omitempty"`
	PartnerCode          string   `protobuf:"bytes,10,opt,name=partner_code,json=partnerCode,proto3" json:"partner_code,omitempty"`
	TypeWallet           string   `protobuf:"bytes,11,opt,name=type_wallet,json=typeWallet,proto3" json:"type_wallet,omitempty"`
	Amount               uint64   `protobuf:"varint,12,opt,name=amount,proto3" json:"amount,omitempty"`
	Freeze               bool     `protobuf:"varint,13,opt,name=freeze,proto3" json:"freeze,omitempty"`
	UnUsewallet          bool     `protobuf:"varint,14,opt,name=un_usewallet,json=unUsewallet,proto3" json:"un_usewallet,omitempty"`
	RefId                string   `protobuf:"bytes,15,opt,name=ref_id,json=refId,proto3" json:"ref_id,omitempty"`
	Id                   string   `protobuf:"bytes,16,opt,name=id,proto3" json:"id,omitempty"`
	PaymentType          string   `protobuf:"bytes,17,opt,name=payment_type,json=paymentType,proto3" json:"payment_type,omitempty"`
	Fee                  uint64   `protobuf:"varint,18,opt,name=fee,proto3" json:"fee,omitempty"`
	DiscountAmount       uint64   `protobuf:"varint,19,opt,name=discount_amount,json=discountAmount,proto3" json:"discount_amount,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *InitPaymentRequest) Reset()         { *m = InitPaymentRequest{} }
func (m *InitPaymentRequest) String() string { return proto.CompactTextString(m) }
func (*InitPaymentRequest) ProtoMessage()    {}
func (*InitPaymentRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_service_9ea794d30e59b71a, []int{16}
}
func (m *InitPaymentRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_InitPaymentRequest.Unmarshal(m, b)
}
func (m *InitPaymentRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_InitPaymentRequest.Marshal(b, m, deterministic)
}
func (dst *InitPaymentRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_InitPaymentRequest.Merge(dst, src)
}
func (m *InitPaymentRequest) XXX_Size() int {
	return xxx_messageInfo_InitPaymentRequest.Size(m)
}
func (m *InitPaymentRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_InitPaymentRequest.DiscardUnknown(m)
}

var xxx_messageInfo_InitPaymentRequest proto.InternalMessageInfo

func (m *InitPaymentRequest) GetPayerId() string {
	if m != nil {
		return m.PayerId
	}
	return ""
}

func (m *InitPaymentRequest) GetPayeeId() string {
	if m != nil {
		return m.PayeeId
	}
	return ""
}

func (m *InitPaymentRequest) GetVoucherCode() string {
	if m != nil {
		return m.VoucherCode
	}
	return ""
}

func (m *InitPaymentRequest) GetTypeTransaction() string {
	if m != nil {
		return m.TypeTransaction
	}
	return ""
}

func (m *InitPaymentRequest) GetMessage() string {
	if m != nil {
		return m.Message
	}
	return ""
}

func (m *InitPaymentRequest) GetDeviceId() string {
	if m != nil {
		return m.DeviceId
	}
	return ""
}

func (m *InitPaymentRequest) GetTypeTransfer() string {
	if m != nil {
		return m.TypeTransfer
	}
	return ""
}

func (m *InitPaymentRequest) GetCurrency() string {
	if m != nil {
		return m.Currency
	}
	return ""
}

func (m *InitPaymentRequest) GetMerchantCode() string {
	if m != nil {
		return m.MerchantCode
	}
	return ""
}

func (m *InitPaymentRequest) GetPartnerCode() string {
	if m != nil {
		return m.PartnerCode
	}
	return ""
}

func (m *InitPaymentRequest) GetTypeWallet() string {
	if m != nil {
		return m.TypeWallet
	}
	return ""
}

func (m *InitPaymentRequest) GetAmount() uint64 {
	if m != nil {
		return m.Amount
	}
	return 0
}

func (m *InitPaymentRequest) GetFreeze() bool {
	if m != nil {
		return m.Freeze
	}
	return false
}

func (m *InitPaymentRequest) GetUnUsewallet() bool {
	if m != nil {
		return m.UnUsewallet
	}
	return false
}

func (m *InitPaymentRequest) GetRefId() string {
	if m != nil {
		return m.RefId
	}
	return ""
}

func (m *InitPaymentRequest) GetId() string {
	if m != nil {
		return m.Id
	}
	return ""
}

func (m *InitPaymentRequest) GetPaymentType() string {
	if m != nil {
		return m.PaymentType
	}
	return ""
}

func (m *InitPaymentRequest) GetFee() uint64 {
	if m != nil {
		return m.Fee
	}
	return 0
}

func (m *InitPaymentRequest) GetDiscountAmount() uint64 {
	if m != nil {
		return m.DiscountAmount
	}
	return 0
}

type MakePaymentRequest struct {
	TransactionId        string   `protobuf:"bytes,1,opt,name=transaction_id,json=transactionId,proto3" json:"transaction_id,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *MakePaymentRequest) Reset()         { *m = MakePaymentRequest{} }
func (m *MakePaymentRequest) String() string { return proto.CompactTextString(m) }
func (*MakePaymentRequest) ProtoMessage()    {}
func (*MakePaymentRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_service_9ea794d30e59b71a, []int{17}
}
func (m *MakePaymentRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_MakePaymentRequest.Unmarshal(m, b)
}
func (m *MakePaymentRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_MakePaymentRequest.Marshal(b, m, deterministic)
}
func (dst *MakePaymentRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_MakePaymentRequest.Merge(dst, src)
}
func (m *MakePaymentRequest) XXX_Size() int {
	return xxx_messageInfo_MakePaymentRequest.Size(m)
}
func (m *MakePaymentRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_MakePaymentRequest.DiscardUnknown(m)
}

var xxx_messageInfo_MakePaymentRequest proto.InternalMessageInfo

func (m *MakePaymentRequest) GetTransactionId() string {
	if m != nil {
		return m.TransactionId
	}
	return ""
}

type CancelTransactionIdRequest struct {
	TransactionId        string   `protobuf:"bytes,1,opt,name=transaction_id,json=transactionId,proto3" json:"transaction_id,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *CancelTransactionIdRequest) Reset()         { *m = CancelTransactionIdRequest{} }
func (m *CancelTransactionIdRequest) String() string { return proto.CompactTextString(m) }
func (*CancelTransactionIdRequest) ProtoMessage()    {}
func (*CancelTransactionIdRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_service_9ea794d30e59b71a, []int{18}
}
func (m *CancelTransactionIdRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_CancelTransactionIdRequest.Unmarshal(m, b)
}
func (m *CancelTransactionIdRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_CancelTransactionIdRequest.Marshal(b, m, deterministic)
}
func (dst *CancelTransactionIdRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_CancelTransactionIdRequest.Merge(dst, src)
}
func (m *CancelTransactionIdRequest) XXX_Size() int {
	return xxx_messageInfo_CancelTransactionIdRequest.Size(m)
}
func (m *CancelTransactionIdRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_CancelTransactionIdRequest.DiscardUnknown(m)
}

var xxx_messageInfo_CancelTransactionIdRequest proto.InternalMessageInfo

func (m *CancelTransactionIdRequest) GetTransactionId() string {
	if m != nil {
		return m.TransactionId
	}
	return ""
}

type UpdateIncrementAmountRequest struct {
	UserId               string   `protobuf:"bytes,1,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *UpdateIncrementAmountRequest) Reset()         { *m = UpdateIncrementAmountRequest{} }
func (m *UpdateIncrementAmountRequest) String() string { return proto.CompactTextString(m) }
func (*UpdateIncrementAmountRequest) ProtoMessage()    {}
func (*UpdateIncrementAmountRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_service_9ea794d30e59b71a, []int{19}
}
func (m *UpdateIncrementAmountRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_UpdateIncrementAmountRequest.Unmarshal(m, b)
}
func (m *UpdateIncrementAmountRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_UpdateIncrementAmountRequest.Marshal(b, m, deterministic)
}
func (dst *UpdateIncrementAmountRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_UpdateIncrementAmountRequest.Merge(dst, src)
}
func (m *UpdateIncrementAmountRequest) XXX_Size() int {
	return xxx_messageInfo_UpdateIncrementAmountRequest.Size(m)
}
func (m *UpdateIncrementAmountRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_UpdateIncrementAmountRequest.DiscardUnknown(m)
}

var xxx_messageInfo_UpdateIncrementAmountRequest proto.InternalMessageInfo

func (m *UpdateIncrementAmountRequest) GetUserId() string {
	if m != nil {
		return m.UserId
	}
	return ""
}

type UpdateDecrementAmountRequest struct {
	UserId               string   `protobuf:"bytes,1,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *UpdateDecrementAmountRequest) Reset()         { *m = UpdateDecrementAmountRequest{} }
func (m *UpdateDecrementAmountRequest) String() string { return proto.CompactTextString(m) }
func (*UpdateDecrementAmountRequest) ProtoMessage()    {}
func (*UpdateDecrementAmountRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_service_9ea794d30e59b71a, []int{20}
}
func (m *UpdateDecrementAmountRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_UpdateDecrementAmountRequest.Unmarshal(m, b)
}
func (m *UpdateDecrementAmountRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_UpdateDecrementAmountRequest.Marshal(b, m, deterministic)
}
func (dst *UpdateDecrementAmountRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_UpdateDecrementAmountRequest.Merge(dst, src)
}
func (m *UpdateDecrementAmountRequest) XXX_Size() int {
	return xxx_messageInfo_UpdateDecrementAmountRequest.Size(m)
}
func (m *UpdateDecrementAmountRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_UpdateDecrementAmountRequest.DiscardUnknown(m)
}

var xxx_messageInfo_UpdateDecrementAmountRequest proto.InternalMessageInfo

func (m *UpdateDecrementAmountRequest) GetUserId() string {
	if m != nil {
		return m.UserId
	}
	return ""
}

type UpdateUserIncurredRequest struct {
	UserId               string   `protobuf:"bytes,1,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *UpdateUserIncurredRequest) Reset()         { *m = UpdateUserIncurredRequest{} }
func (m *UpdateUserIncurredRequest) String() string { return proto.CompactTextString(m) }
func (*UpdateUserIncurredRequest) ProtoMessage()    {}
func (*UpdateUserIncurredRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_service_9ea794d30e59b71a, []int{21}
}
func (m *UpdateUserIncurredRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_UpdateUserIncurredRequest.Unmarshal(m, b)
}
func (m *UpdateUserIncurredRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_UpdateUserIncurredRequest.Marshal(b, m, deterministic)
}
func (dst *UpdateUserIncurredRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_UpdateUserIncurredRequest.Merge(dst, src)
}
func (m *UpdateUserIncurredRequest) XXX_Size() int {
	return xxx_messageInfo_UpdateUserIncurredRequest.Size(m)
}
func (m *UpdateUserIncurredRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_UpdateUserIncurredRequest.DiscardUnknown(m)
}

var xxx_messageInfo_UpdateUserIncurredRequest proto.InternalMessageInfo

func (m *UpdateUserIncurredRequest) GetUserId() string {
	if m != nil {
		return m.UserId
	}
	return ""
}

// Response
type ProcessCashbackResponse struct {
	Success              bool     `protobuf:"varint,1,opt,name=Success,proto3" json:"Success,omitempty"`
	IdCashback           string   `protobuf:"bytes,2,opt,name=id_cashback,json=idCashback,proto3" json:"id_cashback,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *ProcessCashbackResponse) Reset()         { *m = ProcessCashbackResponse{} }
func (m *ProcessCashbackResponse) String() string { return proto.CompactTextString(m) }
func (*ProcessCashbackResponse) ProtoMessage()    {}
func (*ProcessCashbackResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_service_9ea794d30e59b71a, []int{22}
}
func (m *ProcessCashbackResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ProcessCashbackResponse.Unmarshal(m, b)
}
func (m *ProcessCashbackResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ProcessCashbackResponse.Marshal(b, m, deterministic)
}
func (dst *ProcessCashbackResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ProcessCashbackResponse.Merge(dst, src)
}
func (m *ProcessCashbackResponse) XXX_Size() int {
	return xxx_messageInfo_ProcessCashbackResponse.Size(m)
}
func (m *ProcessCashbackResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_ProcessCashbackResponse.DiscardUnknown(m)
}

var xxx_messageInfo_ProcessCashbackResponse proto.InternalMessageInfo

func (m *ProcessCashbackResponse) GetSuccess() bool {
	if m != nil {
		return m.Success
	}
	return false
}

func (m *ProcessCashbackResponse) GetIdCashback() string {
	if m != nil {
		return m.IdCashback
	}
	return ""
}

type UpdateTransactionResponse struct {
	Success              bool     `protobuf:"varint,1,opt,name=success,proto3" json:"success,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *UpdateTransactionResponse) Reset()         { *m = UpdateTransactionResponse{} }
func (m *UpdateTransactionResponse) String() string { return proto.CompactTextString(m) }
func (*UpdateTransactionResponse) ProtoMessage()    {}
func (*UpdateTransactionResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_service_9ea794d30e59b71a, []int{23}
}
func (m *UpdateTransactionResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_UpdateTransactionResponse.Unmarshal(m, b)
}
func (m *UpdateTransactionResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_UpdateTransactionResponse.Marshal(b, m, deterministic)
}
func (dst *UpdateTransactionResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_UpdateTransactionResponse.Merge(dst, src)
}
func (m *UpdateTransactionResponse) XXX_Size() int {
	return xxx_messageInfo_UpdateTransactionResponse.Size(m)
}
func (m *UpdateTransactionResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_UpdateTransactionResponse.DiscardUnknown(m)
}

var xxx_messageInfo_UpdateTransactionResponse proto.InternalMessageInfo

func (m *UpdateTransactionResponse) GetSuccess() bool {
	if m != nil {
		return m.Success
	}
	return false
}

type InitTransactionResponse struct {
	TransactionDetail    *TransactionDetail `protobuf:"bytes,1,opt,name=transaction_detail,json=transactionDetail,proto3" json:"transaction_detail,omitempty"`
	XXX_NoUnkeyedLiteral struct{}           `json:"-"`
	XXX_unrecognized     []byte             `json:"-"`
	XXX_sizecache        int32              `json:"-"`
}

func (m *InitTransactionResponse) Reset()         { *m = InitTransactionResponse{} }
func (m *InitTransactionResponse) String() string { return proto.CompactTextString(m) }
func (*InitTransactionResponse) ProtoMessage()    {}
func (*InitTransactionResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_service_9ea794d30e59b71a, []int{24}
}
func (m *InitTransactionResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_InitTransactionResponse.Unmarshal(m, b)
}
func (m *InitTransactionResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_InitTransactionResponse.Marshal(b, m, deterministic)
}
func (dst *InitTransactionResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_InitTransactionResponse.Merge(dst, src)
}
func (m *InitTransactionResponse) XXX_Size() int {
	return xxx_messageInfo_InitTransactionResponse.Size(m)
}
func (m *InitTransactionResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_InitTransactionResponse.DiscardUnknown(m)
}

var xxx_messageInfo_InitTransactionResponse proto.InternalMessageInfo

func (m *InitTransactionResponse) GetTransactionDetail() *TransactionDetail {
	if m != nil {
		return m.TransactionDetail
	}
	return nil
}

type CheckPendingTransactionResponse struct {
	Success              bool     `protobuf:"varint,1,opt,name=Success,proto3" json:"Success,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *CheckPendingTransactionResponse) Reset()         { *m = CheckPendingTransactionResponse{} }
func (m *CheckPendingTransactionResponse) String() string { return proto.CompactTextString(m) }
func (*CheckPendingTransactionResponse) ProtoMessage()    {}
func (*CheckPendingTransactionResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_service_9ea794d30e59b71a, []int{25}
}
func (m *CheckPendingTransactionResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_CheckPendingTransactionResponse.Unmarshal(m, b)
}
func (m *CheckPendingTransactionResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_CheckPendingTransactionResponse.Marshal(b, m, deterministic)
}
func (dst *CheckPendingTransactionResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_CheckPendingTransactionResponse.Merge(dst, src)
}
func (m *CheckPendingTransactionResponse) XXX_Size() int {
	return xxx_messageInfo_CheckPendingTransactionResponse.Size(m)
}
func (m *CheckPendingTransactionResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_CheckPendingTransactionResponse.DiscardUnknown(m)
}

var xxx_messageInfo_CheckPendingTransactionResponse proto.InternalMessageInfo

func (m *CheckPendingTransactionResponse) GetSuccess() bool {
	if m != nil {
		return m.Success
	}
	return false
}

type FilterTransactionResponse struct {
	TransactionDetail    []*TransactionDetail `protobuf:"bytes,1,rep,name=transaction_detail,json=transactionDetail,proto3" json:"transaction_detail,omitempty"`
	XXX_NoUnkeyedLiteral struct{}             `json:"-"`
	XXX_unrecognized     []byte               `json:"-"`
	XXX_sizecache        int32                `json:"-"`
}

func (m *FilterTransactionResponse) Reset()         { *m = FilterTransactionResponse{} }
func (m *FilterTransactionResponse) String() string { return proto.CompactTextString(m) }
func (*FilterTransactionResponse) ProtoMessage()    {}
func (*FilterTransactionResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_service_9ea794d30e59b71a, []int{26}
}
func (m *FilterTransactionResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_FilterTransactionResponse.Unmarshal(m, b)
}
func (m *FilterTransactionResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_FilterTransactionResponse.Marshal(b, m, deterministic)
}
func (dst *FilterTransactionResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_FilterTransactionResponse.Merge(dst, src)
}
func (m *FilterTransactionResponse) XXX_Size() int {
	return xxx_messageInfo_FilterTransactionResponse.Size(m)
}
func (m *FilterTransactionResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_FilterTransactionResponse.DiscardUnknown(m)
}

var xxx_messageInfo_FilterTransactionResponse proto.InternalMessageInfo

func (m *FilterTransactionResponse) GetTransactionDetail() []*TransactionDetail {
	if m != nil {
		return m.TransactionDetail
	}
	return nil
}

type MakePaymentResponse struct {
	Done                 bool     `protobuf:"varint,1,opt,name=done,proto3" json:"done,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *MakePaymentResponse) Reset()         { *m = MakePaymentResponse{} }
func (m *MakePaymentResponse) String() string { return proto.CompactTextString(m) }
func (*MakePaymentResponse) ProtoMessage()    {}
func (*MakePaymentResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_service_9ea794d30e59b71a, []int{27}
}
func (m *MakePaymentResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_MakePaymentResponse.Unmarshal(m, b)
}
func (m *MakePaymentResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_MakePaymentResponse.Marshal(b, m, deterministic)
}
func (dst *MakePaymentResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_MakePaymentResponse.Merge(dst, src)
}
func (m *MakePaymentResponse) XXX_Size() int {
	return xxx_messageInfo_MakePaymentResponse.Size(m)
}
func (m *MakePaymentResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_MakePaymentResponse.DiscardUnknown(m)
}

var xxx_messageInfo_MakePaymentResponse proto.InternalMessageInfo

func (m *MakePaymentResponse) GetDone() bool {
	if m != nil {
		return m.Done
	}
	return false
}

type CancelTransactionIdResponse struct {
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *CancelTransactionIdResponse) Reset()         { *m = CancelTransactionIdResponse{} }
func (m *CancelTransactionIdResponse) String() string { return proto.CompactTextString(m) }
func (*CancelTransactionIdResponse) ProtoMessage()    {}
func (*CancelTransactionIdResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_service_9ea794d30e59b71a, []int{28}
}
func (m *CancelTransactionIdResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_CancelTransactionIdResponse.Unmarshal(m, b)
}
func (m *CancelTransactionIdResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_CancelTransactionIdResponse.Marshal(b, m, deterministic)
}
func (dst *CancelTransactionIdResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_CancelTransactionIdResponse.Merge(dst, src)
}
func (m *CancelTransactionIdResponse) XXX_Size() int {
	return xxx_messageInfo_CancelTransactionIdResponse.Size(m)
}
func (m *CancelTransactionIdResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_CancelTransactionIdResponse.DiscardUnknown(m)
}

var xxx_messageInfo_CancelTransactionIdResponse proto.InternalMessageInfo

type UpdateIncrementAmountResponse struct {
	TotalAmount          int64    `protobuf:"varint,1,opt,name=total_amount,json=totalAmount,proto3" json:"total_amount,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *UpdateIncrementAmountResponse) Reset()         { *m = UpdateIncrementAmountResponse{} }
func (m *UpdateIncrementAmountResponse) String() string { return proto.CompactTextString(m) }
func (*UpdateIncrementAmountResponse) ProtoMessage()    {}
func (*UpdateIncrementAmountResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_service_9ea794d30e59b71a, []int{29}
}
func (m *UpdateIncrementAmountResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_UpdateIncrementAmountResponse.Unmarshal(m, b)
}
func (m *UpdateIncrementAmountResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_UpdateIncrementAmountResponse.Marshal(b, m, deterministic)
}
func (dst *UpdateIncrementAmountResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_UpdateIncrementAmountResponse.Merge(dst, src)
}
func (m *UpdateIncrementAmountResponse) XXX_Size() int {
	return xxx_messageInfo_UpdateIncrementAmountResponse.Size(m)
}
func (m *UpdateIncrementAmountResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_UpdateIncrementAmountResponse.DiscardUnknown(m)
}

var xxx_messageInfo_UpdateIncrementAmountResponse proto.InternalMessageInfo

func (m *UpdateIncrementAmountResponse) GetTotalAmount() int64 {
	if m != nil {
		return m.TotalAmount
	}
	return 0
}

type UpdateDecrementAmountResponse struct {
	TotalAmount          int64    `protobuf:"varint,1,opt,name=total_amount,json=totalAmount,proto3" json:"total_amount,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *UpdateDecrementAmountResponse) Reset()         { *m = UpdateDecrementAmountResponse{} }
func (m *UpdateDecrementAmountResponse) String() string { return proto.CompactTextString(m) }
func (*UpdateDecrementAmountResponse) ProtoMessage()    {}
func (*UpdateDecrementAmountResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_service_9ea794d30e59b71a, []int{30}
}
func (m *UpdateDecrementAmountResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_UpdateDecrementAmountResponse.Unmarshal(m, b)
}
func (m *UpdateDecrementAmountResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_UpdateDecrementAmountResponse.Marshal(b, m, deterministic)
}
func (dst *UpdateDecrementAmountResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_UpdateDecrementAmountResponse.Merge(dst, src)
}
func (m *UpdateDecrementAmountResponse) XXX_Size() int {
	return xxx_messageInfo_UpdateDecrementAmountResponse.Size(m)
}
func (m *UpdateDecrementAmountResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_UpdateDecrementAmountResponse.DiscardUnknown(m)
}

var xxx_messageInfo_UpdateDecrementAmountResponse proto.InternalMessageInfo

func (m *UpdateDecrementAmountResponse) GetTotalAmount() int64 {
	if m != nil {
		return m.TotalAmount
	}
	return 0
}

type UpdateUserIncurredResponse struct {
	Success              bool     `protobuf:"varint,1,opt,name=success,proto3" json:"success,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *UpdateUserIncurredResponse) Reset()         { *m = UpdateUserIncurredResponse{} }
func (m *UpdateUserIncurredResponse) String() string { return proto.CompactTextString(m) }
func (*UpdateUserIncurredResponse) ProtoMessage()    {}
func (*UpdateUserIncurredResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_service_9ea794d30e59b71a, []int{31}
}
func (m *UpdateUserIncurredResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_UpdateUserIncurredResponse.Unmarshal(m, b)
}
func (m *UpdateUserIncurredResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_UpdateUserIncurredResponse.Marshal(b, m, deterministic)
}
func (dst *UpdateUserIncurredResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_UpdateUserIncurredResponse.Merge(dst, src)
}
func (m *UpdateUserIncurredResponse) XXX_Size() int {
	return xxx_messageInfo_UpdateUserIncurredResponse.Size(m)
}
func (m *UpdateUserIncurredResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_UpdateUserIncurredResponse.DiscardUnknown(m)
}

var xxx_messageInfo_UpdateUserIncurredResponse proto.InternalMessageInfo

func (m *UpdateUserIncurredResponse) GetSuccess() bool {
	if m != nil {
		return m.Success
	}
	return false
}

func init() {
	proto.RegisterType((*InitMerchantAccountReq)(nil), "service_transaction.InitMerchantAccountReq")
	proto.RegisterType((*AccountingPromotionRequest)(nil), "service_transaction.AccountingPromotionRequest")
	proto.RegisterType((*WithdrawWalletRequest)(nil), "service_transaction.WithdrawWalletRequest")
	proto.RegisterType((*DepositGpayRequest)(nil), "service_transaction.DepositGpayRequest")
	proto.RegisterType((*ProcessCashbackRequest)(nil), "service_transaction.ProcessCashbackRequest")
	proto.RegisterType((*FindByTransactionIdRequest)(nil), "service_transaction.FindByTransactionIdRequest")
	proto.RegisterType((*ChangeStatusCheckingRequest)(nil), "service_transaction.ChangeStatusCheckingRequest")
	proto.RegisterType((*ChangeStatusSettlementRequest)(nil), "service_transaction.ChangeStatusSettlementRequest")
	proto.RegisterType((*AccountingPromotionDepositRequest)(nil), "service_transaction.AccountingPromotionDepositRequest")
	proto.RegisterType((*AccountingPromotionWithdrawRequest)(nil), "service_transaction.AccountingPromotionWithdrawRequest")
	proto.RegisterType((*AccountingChangeGpayRequest)(nil), "service_transaction.AccountingChangeGpayRequest")
	proto.RegisterType((*AccountingSettlementRequest)(nil), "service_transaction.AccountingSettlementRequest")
	proto.RegisterType((*TransactionRequest)(nil), "service_transaction.TransactionRequest")
	proto.RegisterType((*CheckPendingTransactionRequest)(nil), "service_transaction.CheckPendingTransactionRequest")
	proto.RegisterType((*FindByTransactionIdResponse)(nil), "service_transaction.FindByTransactionIdResponse")
	proto.RegisterType((*FilterTransactionRequest)(nil), "service_transaction.FilterTransactionRequest")
	proto.RegisterType((*InitPaymentRequest)(nil), "service_transaction.InitPaymentRequest")
	proto.RegisterType((*MakePaymentRequest)(nil), "service_transaction.MakePaymentRequest")
	proto.RegisterType((*CancelTransactionIdRequest)(nil), "service_transaction.CancelTransactionIdRequest")
	proto.RegisterType((*UpdateIncrementAmountRequest)(nil), "service_transaction.UpdateIncrementAmountRequest")
	proto.RegisterType((*UpdateDecrementAmountRequest)(nil), "service_transaction.UpdateDecrementAmountRequest")
	proto.RegisterType((*UpdateUserIncurredRequest)(nil), "service_transaction.UpdateUserIncurredRequest")
	proto.RegisterType((*ProcessCashbackResponse)(nil), "service_transaction.ProcessCashbackResponse")
	proto.RegisterType((*UpdateTransactionResponse)(nil), "service_transaction.UpdateTransactionResponse")
	proto.RegisterType((*InitTransactionResponse)(nil), "service_transaction.InitTransactionResponse")
	proto.RegisterType((*CheckPendingTransactionResponse)(nil), "service_transaction.CheckPendingTransactionResponse")
	proto.RegisterType((*FilterTransactionResponse)(nil), "service_transaction.FilterTransactionResponse")
	proto.RegisterType((*MakePaymentResponse)(nil), "service_transaction.MakePaymentResponse")
	proto.RegisterType((*CancelTransactionIdResponse)(nil), "service_transaction.CancelTransactionIdResponse")
	proto.RegisterType((*UpdateIncrementAmountResponse)(nil), "service_transaction.UpdateIncrementAmountResponse")
	proto.RegisterType((*UpdateDecrementAmountResponse)(nil), "service_transaction.UpdateDecrementAmountResponse")
	proto.RegisterType((*UpdateUserIncurredResponse)(nil), "service_transaction.UpdateUserIncurredResponse")
}

func init() {
	proto.RegisterFile("service_transaction/service.proto", fileDescriptor_service_9ea794d30e59b71a)
}

var fileDescriptor_service_9ea794d30e59b71a = []byte{
	// 2182 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0xb4, 0x5a, 0x4b, 0x6f, 0xdc, 0xc8,
	0x11, 0x1e, 0x4a, 0xb2, 0x34, 0xaa, 0x91, 0x65, 0xa9, 0x65, 0x4b, 0x63, 0xca, 0x5e, 0x4b, 0x6d,
	0xef, 0xae, 0xbc, 0xf1, 0xca, 0xbb, 0x5a, 0xef, 0x23, 0xf0, 0x22, 0x80, 0xa4, 0x59, 0x39, 0x03,
	0xac, 0x13, 0x65, 0x24, 0x67, 0x91, 0xd3, 0xa0, 0x45, 0xb6, 0x24, 0xc6, 0x33, 0xe4, 0x98, 0xec,
	0x91, 0x33, 0x46, 0x80, 0x3c, 0x80, 0x00, 0xd9, 0x1c, 0x02, 0xe4, 0x92, 0x5f, 0x90, 0x5b, 0x6e,
	0xf9, 0x03, 0xb9, 0xe5, 0x9e, 0x1f, 0x90, 0x53, 0x8e, 0x39, 0xe5, 0x9c, 0x4b, 0xd0, 0x0f, 0x92,
	0x4d, 0xb2, 0x39, 0x0f, 0xad, 0x7c, 0x63, 0x57, 0x57, 0x55, 0x7f, 0x5d, 0xfd, 0x55, 0x55, 0x73,
	0x38, 0xb0, 0x19, 0xd1, 0xf0, 0xc2, 0x73, 0x68, 0x9b, 0x85, 0xc4, 0x8f, 0x88, 0xc3, 0xbc, 0xc0,
	0x7f, 0xac, 0x64, 0xdb, 0xbd, 0x30, 0x60, 0x01, 0x5a, 0x31, 0xa8, 0xd8, 0x8f, 0x4c, 0x76, 0xda,
	0x73, 0xdb, 0xa5, 0x8c, 0x78, 0x1d, 0xe9, 0xc2, 0x7e, 0x77, 0x84, 0xb6, 0x52, 0x7b, 0x3c, 0xca,
	0x69, 0xc7, 0xeb, 0x7a, 0xac, 0x7d, 0x4a, 0x15, 0x34, 0xfc, 0x7d, 0x58, 0x6d, 0xfa, 0x1e, 0x7b,
	0x4e, 0x43, 0xe7, 0x9c, 0xf8, 0x6c, 0xd7, 0x71, 0x82, 0xbe, 0xcf, 0x5a, 0xf4, 0x15, 0xba, 0x07,
	0xb5, 0xae, 0x92, 0xb6, 0x3d, 0xb7, 0x6e, 0x6d, 0x58, 0x5b, 0xf3, 0x2d, 0x88, 0x45, 0x4d, 0x17,
	0xff, 0xcd, 0x02, 0x5b, 0xe9, 0x7b, 0xfe, 0xd9, 0x61, 0x18, 0x74, 0x03, 0xbe, 0x44, 0x8b, 0xbe,
	0xea, 0xd3, 0x88, 0xa1, 0x0d, 0xa8, 0x25, 0xb2, 0x66, 0x43, 0xd9, 0xeb, 0x22, 0xb4, 0x0a, 0xb3,
	0xbb, 0x5d, 0x6e, 0x5e, 0x9f, 0xda, 0xb0, 0xb6, 0xa6, 0x5b, 0x6a, 0x84, 0xde, 0x01, 0x38, 0x1e,
	0xf4, 0xe8, 0x37, 0xa4, 0xd3, 0xa1, 0xac, 0x3e, 0x2d, 0x17, 0x4e, 0x25, 0xe8, 0x0e, 0xcc, 0xab,
	0x45, 0x9a, 0x8d, 0xfa, 0x8c, 0x98, 0x4e, 0x05, 0x7c, 0xb6, 0xe9, 0x5f, 0x50, 0x9f, 0x05, 0xe1,
	0xa0, 0x7e, 0x4d, 0x38, 0x4e, 0x05, 0xf8, 0x7f, 0x16, 0xdc, 0xfa, 0xc6, 0x63, 0xe7, 0x6e, 0x48,
	0x5e, 0x4b, 0x77, 0x31, 0x5e, 0x1b, 0xaa, 0x7b, 0xc4, 0x7f, 0xb9, 0x1f, 0xb8, 0x54, 0x81, 0x4d,
	0xc6, 0xe8, 0x3d, 0x58, 0xe4, 0xcf, 0x1a, 0xaa, 0x29, 0xa1, 0x91, 0x93, 0xa2, 0x3a, 0xcc, 0x3d,
	0xa7, 0x51, 0x44, 0xce, 0xa8, 0x82, 0x1d, 0x0f, 0xf9, 0x5e, 0x9f, 0xf5, 0xc8, 0x20, 0x01, 0xac,
	0x46, 0x7c, 0xaf, 0x71, 0xec, 0x9b, 0x0d, 0x01, 0x77, 0xbe, 0xa5, 0x49, 0xf4, 0xbd, 0xba, 0xf5,
	0xd9, 0xec, 0x5e, 0x5d, 0x2d, 0x82, 0x73, 0x99, 0x08, 0xae, 0xc2, 0xec, 0x51, 0xd0, 0x0f, 0x1d,
	0x5a, 0xaf, 0xca, 0xd5, 0xe4, 0x08, 0xff, 0xd9, 0x02, 0xd4, 0xa0, 0xbd, 0x20, 0xf2, 0x18, 0x5f,
	0x3f, 0xde, 0x3a, 0x07, 0x77, 0xb8, 0xfb, 0xb3, 0xe4, 0x94, 0xd4, 0x88, 0xcb, 0x33, 0xdb, 0x55,
	0x23, 0x6d, 0xd9, 0xe9, 0xcc, 0xb2, 0x7a, 0x08, 0x67, 0x72, 0x21, 0xcc, 0x1c, 0xda, 0xb5, 0xdc,
	0xa1, 0xe1, 0x1f, 0xc0, 0xea, 0x61, 0x18, 0x38, 0x34, 0x8a, 0xf6, 0x49, 0x74, 0x7e, 0x42, 0x9c,
	0x97, 0x31, 0xb6, 0x07, 0x70, 0x5d, 0xe3, 0x6f, 0x33, 0x26, 0x62, 0x56, 0x88, 0x1f, 0x81, 0x7d,
	0xe0, 0xf9, 0xee, 0xde, 0xe0, 0x58, 0x17, 0xc7, 0x3e, 0x16, 0x61, 0x2a, 0x61, 0xf0, 0x94, 0xe7,
	0xe2, 0xbf, 0x5a, 0xb0, 0xbe, 0x7f, 0x4e, 0xfc, 0x33, 0x7a, 0xc4, 0x08, 0xeb, 0x47, 0xfb, 0xe7,
	0xd4, 0x79, 0xe9, 0xf9, 0x67, 0xb1, 0xfe, 0x12, 0x4c, 0x7b, 0x6e, 0x54, 0xb7, 0x36, 0xa6, 0xb7,
	0xe6, 0x5b, 0xfc, 0x91, 0x13, 0x20, 0xca, 0xa8, 0xc6, 0x04, 0xc8, 0x4a, 0xd1, 0x36, 0x20, 0x25,
	0x09, 0x5c, 0x9a, 0xe8, 0x4a, 0x2e, 0x18, 0x66, 0x10, 0x86, 0x05, 0xe6, 0x75, 0x53, 0xcd, 0x19,
	0x11, 0xcf, 0x8c, 0x0c, 0xff, 0xce, 0x82, 0xbb, 0x3a, 0xda, 0x23, 0xca, 0x58, 0x87, 0x76, 0xa9,
	0xcf, 0xca, 0xf1, 0x7e, 0x00, 0x4b, 0x51, 0x4e, 0x59, 0x21, 0x2e, 0xc8, 0xf9, 0xde, 0xf8, 0x7a,
	0x9a, 0xa6, 0x3c, 0xd5, 0x9c, 0x14, 0xff, 0x77, 0x0a, 0x36, 0x0d, 0xf9, 0xae, 0xf8, 0x14, 0x63,
	0xc9, 0x12, 0xda, 0x2a, 0x10, 0x3a, 0xe5, 0xda, 0x54, 0x86, 0x6b, 0xb9, 0x72, 0x31, 0x5d, 0x2c,
	0x17, 0x0f, 0xe0, 0x7a, 0x32, 0xfc, 0x11, 0xe9, 0xc6, 0x14, 0xcb, 0x0a, 0xd1, 0x16, 0xdc, 0x48,
	0x04, 0x8a, 0xa4, 0xb2, 0x08, 0xe4, 0xc5, 0x19, 0x7f, 0x82, 0xb2, 0xb3, 0x39, 0x7f, 0x82, 0xb7,
	0x5f, 0xc0, 0xda, 0x71, 0xc0, 0x48, 0x27, 0x45, 0x92, 0x14, 0x17, 0x99, 0x73, 0x65, 0xd3, 0xdc,
	0xff, 0x73, 0xf2, 0x8b, 0x43, 0xe2, 0xb9, 0x0a, 0x47, 0x55, 0xe8, 0x67, 0x85, 0xd9, 0xbc, 0x98,
	0xcf, 0xe7, 0xc5, 0x3f, 0x2c, 0xc0, 0x86, 0x98, 0xc7, 0x15, 0xec, 0xed, 0x07, 0x7d, 0xfc, 0x70,
	0x0e, 0xdf, 0xc8, 0xbf, 0x2d, 0x58, 0x4f, 0x37, 0x22, 0xe9, 0x3c, 0x4e, 0x09, 0xba, 0x03, 0xf3,
	0x47, 0xa1, 0x93, 0xa9, 0x42, 0xa9, 0x80, 0xef, 0xbb, 0x41, 0x23, 0x96, 0xed, 0x14, 0xa9, 0x44,
	0x2b, 0x54, 0xd7, 0x32, 0x85, 0x2a, 0x83, 0x75, 0x36, 0xdf, 0x41, 0x54, 0xff, 0x91, 0x20, 0xc5,
	0x29, 0xab, 0xfe, 0x23, 0x25, 0x7a, 0x95, 0xaf, 0x66, 0xaa, 0x3c, 0xfe, 0xcf, 0xb4, 0xbe, 0xcb,
	0x62, 0xa2, 0x6e, 0x03, 0x62, 0x9c, 0x2d, 0xbb, 0x61, 0x48, 0x49, 0x18, 0x29, 0x6c, 0x96, 0xc0,
	0x66, 0x98, 0x41, 0x3b, 0x70, 0x53, 0x48, 0x5b, 0x94, 0x85, 0x1e, 0xbd, 0x20, 0x9d, 0x4c, 0xbf,
	0x34, 0xce, 0xa1, 0x27, 0x70, 0x8b, 0x38, 0xac, 0x4f, 0x3a, 0x9d, 0x41, 0x8b, 0x3a, 0xd4, 0xbb,
	0xa0, 0x99, 0x5a, 0x6d, 0x9e, 0x44, 0x5f, 0xc2, 0x6d, 0x22, 0x9e, 0x0e, 0x28, 0x8d, 0x89, 0x23,
	0x5a, 0x54, 0xb7, 0xd7, 0x51, 0x55, 0xa9, 0x5c, 0x81, 0xf3, 0x48, 0x5d, 0x3c, 0x78, 0x98, 0x54,
	0x79, 0xd7, 0x45, 0x9c, 0x47, 0x5a, 0xc5, 0x16, 0x5a, 0x32, 0xee, 0x79, 0xb1, 0x28, 0xa1, 0xfd,
	0x93, 0xe3, 0x9c, 0xf2, 0x9c, 0x2a, 0xa1, 0x85, 0x19, 0x7e, 0x5a, 0xdd, 0x94, 0xfb, 0xd5, 0xdc,
	0x35, 0xa5, 0xc1, 0xe3, 0xc1, 0x06, 0x3d, 0x5a, 0x38, 0x0c, 0xc5, 0x51, 0xf3, 0x24, 0x2f, 0xcc,
	0xa9, 0xb0, 0xd9, 0xa8, 0x83, 0x50, 0xce, 0xc8, 0xf0, 0x4f, 0x01, 0x69, 0x60, 0x4a, 0x9a, 0x0d,
	0x67, 0x4b, 0x8f, 0x0c, 0x68, 0xd8, 0x74, 0x15, 0x7f, 0xe3, 0x21, 0x67, 0x27, 0x49, 0x8f, 0x66,
	0xa6, 0xa5, 0x46, 0xf8, 0x0b, 0x78, 0x47, 0x14, 0xff, 0x43, 0xea, 0xbb, 0x9e, 0x7f, 0x66, 0x58,
	0x63, 0x15, 0x66, 0xfb, 0x91, 0x70, 0xa9, 0xb2, 0x45, 0x8e, 0xf0, 0x19, 0xac, 0x1b, 0xdb, 0x60,
	0xd4, 0x0b, 0xfc, 0x88, 0xa2, 0x1f, 0x42, 0x4d, 0x8b, 0xb6, 0xb0, 0xad, 0xed, 0xbc, 0xb7, 0x6d,
	0xb8, 0x33, 0x6e, 0x6b, 0x0e, 0x1a, 0xe2, 0x1e, 0xda, 0xd2, 0x4d, 0xf1, 0x6f, 0xa6, 0xa0, 0x7e,
	0xe0, 0x75, 0x18, 0x0d, 0x0d, 0xe8, 0xd6, 0x60, 0x8e, 0xe3, 0x49, 0x6f, 0x8d, 0x0a, 0x1e, 0x42,
	0x30, 0xc3, 0xa3, 0xad, 0xe2, 0x20, 0x9e, 0xf9, 0x56, 0x82, 0xd3, 0xd3, 0x88, 0x26, 0x77, 0x09,
	0x39, 0x42, 0x37, 0xe1, 0x9a, 0xb8, 0xab, 0x2a, 0xf2, 0xc9, 0x01, 0x97, 0xf2, 0xfe, 0x15, 0x53,
	0x4c, 0x0e, 0xb8, 0x0f, 0xd9, 0xd5, 0x14, 0xa7, 0xd4, 0x48, 0x74, 0xd7, 0x41, 0x8f, 0x0a, 0x88,
	0xa7, 0x34, 0x54, 0x24, 0xca, 0xc8, 0x38, 0x7d, 0x22, 0x46, 0x42, 0x46, 0x5d, 0x77, 0x37, 0x2e,
	0xd1, 0x9a, 0x84, 0x1f, 0x1f, 0xf5, 0x5d, 0xca, 0x27, 0xe7, 0xc5, 0x64, 0x3c, 0xc4, 0xff, 0x9c,
	0x01, 0xc4, 0xef, 0xce, 0x87, 0x64, 0xa0, 0x33, 0xe7, 0x36, 0x54, 0xc5, 0x01, 0xa7, 0xdb, 0x4f,
	0x0e, 0x5c, 0x4d, 0x51, 0x3e, 0xa5, 0x71, 0x81, 0x36, 0x5d, 0xb4, 0x09, 0x0b, 0x17, 0x41, 0xdf,
	0x39, 0xa7, 0x61, 0xdb, 0xe1, 0xbd, 0x48, 0x95, 0x62, 0x25, 0x13, 0x9d, 0xe8, 0x21, 0x2c, 0x71,
	0xe4, 0xfa, 0x31, 0xa9, 0x16, 0x78, 0x23, 0xd9, 0x91, 0x14, 0x73, 0xd0, 0x5d, 0x55, 0xa1, 0x64,
	0xa0, 0xe2, 0x21, 0x5a, 0x87, 0x79, 0x97, 0x8a, 0xd3, 0xf6, 0xe2, 0xfb, 0x64, 0x55, 0x0a, 0x9a,
	0x2e, 0xba, 0x0f, 0xd7, 0xd3, 0x15, 0xca, 0x02, 0x66, 0x43, 0xd5, 0xe9, 0x87, 0x21, 0xf5, 0x9d,
	0x81, 0xca, 0xb6, 0x64, 0xcc, 0x1d, 0x24, 0xef, 0x0c, 0x62, 0x1b, 0x32, 0xc7, 0x16, 0x62, 0xa1,
	0xd8, 0xc7, 0x26, 0x2c, 0xf4, 0x48, 0xc8, 0xfc, 0x78, 0xab, 0x32, 0xb5, 0x6a, 0x4a, 0x26, 0x54,
	0xee, 0x41, 0x4d, 0x00, 0x79, 0x2d, 0x0b, 0x7b, 0x4d, 0x26, 0x35, 0x4b, 0x2f, 0xda, 0x69, 0xea,
	0x2c, 0xe8, 0xa9, 0xc3, 0xe5, 0xa7, 0x21, 0xa5, 0x6f, 0x68, 0xfd, 0xfa, 0x86, 0xb5, 0x55, 0x6d,
	0xa9, 0x11, 0x5f, 0xb3, 0xef, 0xb7, 0xfb, 0x11, 0x55, 0x1e, 0x17, 0xc5, 0x6c, 0xad, 0xef, 0xbf,
	0x88, 0x45, 0xe8, 0x16, 0xcc, 0x86, 0xf4, 0x94, 0x87, 0xe5, 0x86, 0xe4, 0x56, 0x48, 0x4f, 0x9b,
	0xae, 0x4a, 0xe7, 0xa5, 0x24, 0x9d, 0x05, 0x7a, 0x71, 0xe0, 0x6d, 0xc1, 0xe5, 0xe5, 0x18, 0xbd,
	0x90, 0x89, 0x8a, 0xb4, 0x04, 0xd3, 0xa7, 0x94, 0xd6, 0x91, 0x40, 0xc6, 0x1f, 0xd1, 0xfb, 0x70,
	0xc3, 0xf5, 0x22, 0xd1, 0x17, 0xda, 0x0a, 0xf7, 0x8a, 0x98, 0x5d, 0x8c, 0xc5, 0xb2, 0x0c, 0xe3,
	0xa7, 0x80, 0x9e, 0x93, 0x97, 0x34, 0x47, 0xa9, 0x77, 0x61, 0x51, 0x7f, 0x87, 0xf3, 0x4a, 0x2e,
	0xc1, 0xfb, 0x60, 0xef, 0x13, 0xdf, 0xa1, 0x1d, 0xe3, 0x25, 0x78, 0x4c, 0x27, 0x9f, 0xc3, 0x9d,
	0x17, 0x3d, 0x97, 0x30, 0xda, 0xf4, 0x9d, 0x50, 0x54, 0x3a, 0x09, 0x6d, 0x54, 0x72, 0xa7, 0x86,
	0x0d, 0x3a, 0x99, 0xe1, 0x13, 0xb8, 0x2d, 0x0d, 0x5f, 0xf0, 0xb1, 0x2f, 0xc8, 0xe4, 0x8e, 0xb4,
	0x3a, 0x86, 0xb5, 0xc2, 0x1b, 0x83, 0x2a, 0x73, 0x75, 0x98, 0x3b, 0xea, 0x3b, 0x7c, 0x4a, 0xd8,
	0x54, 0x5b, 0xf1, 0x90, 0xf3, 0xca, 0x73, 0xdb, 0x8e, 0x32, 0x50, 0x39, 0x08, 0x9e, 0x1b, 0xbb,
	0xc0, 0x9f, 0xc6, 0x58, 0x32, 0x65, 0x2d, 0xf5, 0x1b, 0x65, 0xfd, 0xaa, 0x21, 0xee, 0xc1, 0x1a,
	0xaf, 0x04, 0x26, 0xa3, 0x17, 0x80, 0x8a, 0x2f, 0xf5, 0x13, 0x96, 0xde, 0x65, 0x96, 0x17, 0xe1,
	0xa7, 0x70, 0xaf, 0xb4, 0x47, 0x8c, 0x0a, 0x03, 0x0e, 0xe1, 0xb6, 0xa1, 0x78, 0x8f, 0x00, 0x3c,
	0xfd, 0xdd, 0x00, 0x3f, 0x84, 0x95, 0x0c, 0xb3, 0xd5, 0x6a, 0x08, 0x66, 0xdc, 0xc0, 0xa7, 0x0a,
	0xa1, 0x78, 0xc6, 0x77, 0x61, 0xdd, 0xc8, 0x63, 0x69, 0x82, 0xf7, 0xe0, 0x6e, 0x09, 0x43, 0x95,
	0xcf, 0x4d, 0x58, 0x10, 0x37, 0xa3, 0x38, 0xd5, 0xe4, 0xfd, 0xaa, 0x26, 0xef, 0x57, 0x32, 0xcf,
	0x12, 0x1f, 0x05, 0xb2, 0x8e, 0xef, 0xe3, 0x33, 0xb0, 0x4d, 0xbc, 0x1d, 0x45, 0x96, 0x9d, 0x7f,
	0x61, 0x98, 0x3b, 0x92, 0x61, 0x44, 0x6f, 0x60, 0xc5, 0xd0, 0xb0, 0xd1, 0x63, 0x63, 0x9c, 0xcb,
	0xdf, 0x70, 0xed, 0x8f, 0xc6, 0x37, 0x50, 0x51, 0xac, 0x20, 0x06, 0xcb, 0x05, 0x16, 0xa0, 0x0f,
	0x4b, 0x1c, 0x99, 0x5b, 0xbd, 0xbd, 0x3d, 0xae, 0x7a, 0xb2, 0xea, 0x09, 0xd4, 0xb4, 0xa6, 0x89,
	0xee, 0x8f, 0x64, 0xd4, 0xf1, 0x8f, 0xed, 0x47, 0x46, 0xa5, 0x92, 0x8c, 0x93, 0x6b, 0x68, 0x5c,
	0x43, 0xef, 0x1b, 0xcd, 0x8b, 0x75, 0xd6, 0xde, 0x1a, 0xad, 0x98, 0xac, 0xf1, 0x06, 0x56, 0x0c,
	0x24, 0x2d, 0x39, 0xb9, 0xf2, 0xb2, 0x5c, 0x72, 0x72, 0xc3, 0xf8, 0x5f, 0x41, 0x21, 0xdc, 0x2a,
	0x54, 0xa9, 0xbd, 0x41, 0xd3, 0x2d, 0xd9, 0xe9, 0xd8, 0xe7, 0x56, 0x5a, 0xfa, 0x70, 0x05, 0xfd,
	0x41, 0xfc, 0x66, 0x62, 0xac, 0x38, 0x47, 0xe7, 0x5e, 0x0f, 0x7d, 0x62, 0xde, 0xc7, 0xd0, 0x7b,
	0xac, 0xfd, 0x64, 0x32, 0xa3, 0x04, 0x8c, 0x2f, 0xde, 0x4a, 0xf5, 0xe2, 0x8f, 0xbe, 0x67, 0x74,
	0x65, 0xfe, 0x51, 0xa9, 0x84, 0x50, 0x25, 0xfd, 0x04, 0x57, 0xd0, 0xaf, 0xad, 0x38, 0xe2, 0xb9,
	0x9a, 0x83, 0x3e, 0x1e, 0x12, 0x48, 0x73, 0x07, 0xb5, 0x77, 0x26, 0x31, 0x31, 0x40, 0xc8, 0x95,
	0xac, 0xa1, 0x10, 0xcc, 0xbd, 0x78, 0x28, 0x84, 0x92, 0x8a, 0x88, 0x2b, 0xe8, 0x35, 0xa0, 0x62,
	0xc1, 0x43, 0xc3, 0xa8, 0x64, 0xe8, 0xe8, 0xf6, 0xe3, 0xb1, 0xf5, 0x93, 0x85, 0xbf, 0xb5, 0xa0,
	0x2e, 0x48, 0xa1, 0xb1, 0xe1, 0x6b, 0xfe, 0x3e, 0x70, 0x40, 0x29, 0x1a, 0xc2, 0x21, 0x83, 0x7a,
	0x8c, 0xe2, 0xd3, 0x09, 0xad, 0x12, 0x2c, 0x3d, 0x58, 0x78, 0x46, 0x19, 0x07, 0x2a, 0x26, 0x87,
	0xf1, 0x5e, 0x73, 0xf4, 0x93, 0x7e, 0xc0, 0xc8, 0xae, 0xef, 0x4a, 0x04, 0xf6, 0x43, 0xa3, 0x91,
	0xee, 0x57, 0x5b, 0xf1, 0xf7, 0x16, 0xdc, 0x7b, 0x46, 0xf5, 0x52, 0x27, 0x4f, 0x66, 0x6f, 0x70,
	0xec, 0x75, 0x69, 0x4b, 0xfc, 0x24, 0xf1, 0x51, 0x99, 0xc3, 0x82, 0x55, 0x1c, 0x80, 0x8f, 0x27,
	0xb0, 0x48, 0xa0, 0xfc, 0x0a, 0xee, 0xec, 0x73, 0x91, 0xa6, 0x13, 0xe9, 0x30, 0xcc, 0xdd, 0xa3,
	0x60, 0x32, 0xbc, 0x0a, 0x19, 0xd4, 0x13, 0x00, 0x8e, 0xec, 0x97, 0xd9, 0xba, 0xd7, 0x40, 0x0f,
	0x8c, 0x8e, 0xbe, 0xca, 0xb5, 0x91, 0xb1, 0xb4, 0x70, 0x05, 0xb5, 0xe1, 0x46, 0xae, 0xb7, 0x5c,
	0xf1, 0x02, 0x27, 0x80, 0xf6, 0x03, 0xff, 0xd4, 0x0b, 0xbb, 0x6f, 0x6f, 0x8d, 0x6f, 0xe3, 0x7a,
	0x6d, 0x66, 0xe1, 0xe5, 0x78, 0x7b, 0x09, 0xa3, 0x08, 0x57, 0x10, 0x81, 0xe5, 0x42, 0x6b, 0xb9,
	0xe2, 0xed, 0x12, 0x58, 0x2e, 0xf4, 0xcc, 0x2b, 0x5e, 0xe2, 0xef, 0x16, 0x7c, 0xf8, 0x8c, 0x32,
	0xb1, 0xdb, 0x03, 0x4a, 0xd5, 0x65, 0x5a, 0xef, 0x83, 0x8c, 0xb0, 0x4c, 0x3a, 0x7c, 0x55, 0x96,
	0x63, 0xe3, 0xfb, 0xe0, 0x51, 0xbf, 0x12, 0x37, 0xfc, 0x1c, 0xfe, 0x62, 0xc1, 0x03, 0x91, 0x5d,
	0xb1, 0x61, 0x59, 0x1e, 0x7f, 0x59, 0x9e, 0x98, 0x23, 0x4c, 0x39, 0xde, 0xef, 0x62, 0xcd, 0x61,
	0xfe, 0xd1, 0x82, 0xfb, 0x3c, 0xcb, 0x47, 0xa1, 0x7c, 0x5a, 0x7a, 0xe9, 0x1d, 0x03, 0xa4, 0xf9,
	0xae, 0xf7, 0xb5, 0x17, 0x31, 0x63, 0xbe, 0xb6, 0xe8, 0x05, 0x0d, 0xa3, 0xb7, 0x48, 0xe0, 0x5f,
	0xc2, 0x4d, 0xd3, 0x27, 0xa9, 0x92, 0xca, 0x3e, 0xe4, 0xeb, 0x95, 0x3d, 0xb1, 0x05, 0xae, 0xa0,
	0xdf, 0x5a, 0xb0, 0x6a, 0xfe, 0xc6, 0x84, 0x76, 0x46, 0xba, 0x2b, 0xfc, 0x7a, 0x6a, 0x5f, 0xc2,
	0x46, 0x86, 0xc0, 0xf4, 0xe3, 0x79, 0x49, 0x08, 0x86, 0xfc, 0xce, 0x6e, 0x4f, 0x6c, 0x21, 0x59,
	0x67, 0x97, 0x7f, 0xde, 0x42, 0x9f, 0x8d, 0x70, 0x59, 0xf2, 0x3d, 0xcc, 0xbe, 0xa4, 0x1d, 0xae,
	0xa0, 0x3f, 0x65, 0x3e, 0x99, 0x14, 0xbe, 0xfd, 0xa0, 0xcf, 0xc7, 0xf5, 0x9c, 0xfb, 0x5a, 0x64,
	0x5f, 0xd6, 0x30, 0x7f, 0x44, 0xe9, 0x57, 0x9c, 0x91, 0x47, 0x54, 0xf8, 0xe0, 0x63, 0x4f, 0x6c,
	0x21, 0x8a, 0x7c, 0x4d, 0xfb, 0x7a, 0x5d, 0xf2, 0xb6, 0x53, 0xfc, 0xbe, 0x6d, 0x8f, 0xab, 0x88,
	0x2b, 0xe8, 0xe7, 0xb0, 0x98, 0xfd, 0x7b, 0x00, 0xfa, 0xc0, 0x68, 0x6c, 0xfc, 0x0f, 0x81, 0x3d,
	0x81, 0x2e, 0xae, 0xa0, 0x01, 0xac, 0x18, 0x82, 0x5e, 0xf2, 0x0a, 0x59, 0xfe, 0x4f, 0x0b, 0x7b,
	0x52, 0x03, 0x5c, 0x41, 0x67, 0xb0, 0x56, 0xb8, 0x47, 0x1d, 0x92, 0x90, 0x74, 0xa3, 0x2b, 0x2e,
	0x6b, 0xaf, 0x60, 0xc5, 0xf0, 0xff, 0x92, 0x92, 0xb7, 0x35, 0xf3, 0x3f, 0x51, 0xec, 0x49, 0x94,
	0x71, 0xe5, 0x64, 0x56, 0xfc, 0xb3, 0xe5, 0x93, 0xff, 0x07, 0x00, 0x00, 0xff, 0xff, 0xc2, 0xdb,
	0xae, 0x0c, 0x99, 0x23, 0x00, 0x00,
}
