version: '3.1'

services:
  tests:
    container_name: "tests"
    build:
      context: ./
      dockerfile: TestDockerfile
    depends_on:
      - mongo

  mongo:
    image: mongo:4.2
    restart: "no"
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: root
    logging:
      driver: none
  rabbitmq:
    image: "rabbitmq:3-management"
    environment:
      RABBITMQ_DEFAULT_USER: "admin"
      RABBITMQ_DEFAULT_PASS: "admin"
      RABBITMQ_DEFAULT_VHOST: "/"
    logging:
      driver: none
  etcd:
    image: bitnami/etcd:latest
    logging:
      driver: none
    environment:
      ALLOW_NONE_AUTHENTICATION: 'yes'