// Code generated by protoc-gen-go. DO NOT EDIT.
// source: service_user/merchant.proto

package service_user

import (
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

type MerchantDTO struct {
	Id                   string   `protobuf:"bytes,1,opt,name=Id,proto3" json:"Id,omitempty"`
	Email                string   `protobuf:"bytes,2,opt,name=Email,proto3" json:"Email,omitempty"`
	Code                 string   `protobuf:"bytes,3,opt,name=Code,proto3" json:"Code,omitempty"`
	Logo                 string   `protobuf:"bytes,4,opt,name=Logo,proto3" json:"Logo,omitempty"`
	SecretKey            string   `protobuf:"bytes,5,opt,name=SecretKey,proto3" json:"SecretKey,omitempty"`
	Salt                 string   `protobuf:"bytes,6,opt,name=Salt,proto3" json:"Salt,omitempty"`
	UserID               string   `protobuf:"bytes,7,opt,name=UserID,proto3" json:"UserID,omitempty"`
	Address              string   `protobuf:"bytes,8,opt,name=Address,proto3" json:"Address,omitempty"`
	Limited              int64    `protobuf:"varint,9,opt,name=Limited,proto3" json:"Limited,omitempty"`
	Name                 string   `protobuf:"bytes,10,opt,name=Name,proto3" json:"Name,omitempty"`
	PhoneNumber          string   `protobuf:"bytes,11,opt,name=PhoneNumber,proto3" json:"PhoneNumber,omitempty"`
	ParentId             string   `protobuf:"bytes,12,opt,name=ParentId,proto3" json:"ParentId,omitempty"`
	Status               string   `protobuf:"bytes,13,opt,name=Status,proto3" json:"Status,omitempty"`
	Website              string   `protobuf:"bytes,14,opt,name=Website,proto3" json:"Website,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *MerchantDTO) Reset()         { *m = MerchantDTO{} }
func (m *MerchantDTO) String() string { return proto.CompactTextString(m) }
func (*MerchantDTO) ProtoMessage()    {}
func (*MerchantDTO) Descriptor() ([]byte, []int) {
	return fileDescriptor_f75e5e65dad4ce95, []int{0}
}

func (m *MerchantDTO) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_MerchantDTO.Unmarshal(m, b)
}
func (m *MerchantDTO) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_MerchantDTO.Marshal(b, m, deterministic)
}
func (m *MerchantDTO) XXX_Merge(src proto.Message) {
	xxx_messageInfo_MerchantDTO.Merge(m, src)
}
func (m *MerchantDTO) XXX_Size() int {
	return xxx_messageInfo_MerchantDTO.Size(m)
}
func (m *MerchantDTO) XXX_DiscardUnknown() {
	xxx_messageInfo_MerchantDTO.DiscardUnknown(m)
}

var xxx_messageInfo_MerchantDTO proto.InternalMessageInfo

func (m *MerchantDTO) GetId() string {
	if m != nil {
		return m.Id
	}
	return ""
}

func (m *MerchantDTO) GetEmail() string {
	if m != nil {
		return m.Email
	}
	return ""
}

func (m *MerchantDTO) GetCode() string {
	if m != nil {
		return m.Code
	}
	return ""
}

func (m *MerchantDTO) GetLogo() string {
	if m != nil {
		return m.Logo
	}
	return ""
}

func (m *MerchantDTO) GetSecretKey() string {
	if m != nil {
		return m.SecretKey
	}
	return ""
}

func (m *MerchantDTO) GetSalt() string {
	if m != nil {
		return m.Salt
	}
	return ""
}

func (m *MerchantDTO) GetUserID() string {
	if m != nil {
		return m.UserID
	}
	return ""
}

func (m *MerchantDTO) GetAddress() string {
	if m != nil {
		return m.Address
	}
	return ""
}

func (m *MerchantDTO) GetLimited() int64 {
	if m != nil {
		return m.Limited
	}
	return 0
}

func (m *MerchantDTO) GetName() string {
	if m != nil {
		return m.Name
	}
	return ""
}

func (m *MerchantDTO) GetPhoneNumber() string {
	if m != nil {
		return m.PhoneNumber
	}
	return ""
}

func (m *MerchantDTO) GetParentId() string {
	if m != nil {
		return m.ParentId
	}
	return ""
}

func (m *MerchantDTO) GetStatus() string {
	if m != nil {
		return m.Status
	}
	return ""
}

func (m *MerchantDTO) GetWebsite() string {
	if m != nil {
		return m.Website
	}
	return ""
}

func init() {
	proto.RegisterType((*MerchantDTO)(nil), "service_user.MerchantDTO")
}

func init() {
	proto.RegisterFile("service_user/merchant.proto", fileDescriptor_f75e5e65dad4ce95)
}

var fileDescriptor_f75e5e65dad4ce95 = []byte{
	// 270 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x09, 0x6e, 0x88, 0x02, 0xff, 0x4c, 0x90, 0x4f, 0x4f, 0xc2, 0x40,
	0x10, 0xc5, 0x43, 0x81, 0x42, 0xa7, 0xc8, 0x61, 0x62, 0xcc, 0x44, 0x3d, 0x10, 0x4f, 0x9e, 0xf4,
	0xe0, 0x27, 0x30, 0xe2, 0x81, 0x88, 0x48, 0xa8, 0xc6, 0xa3, 0xd9, 0xb6, 0x13, 0x69, 0x42, 0xbb,
	0x66, 0x77, 0x6b, 0xe2, 0x87, 0xf5, 0xbb, 0xb8, 0x7f, 0x8a, 0x70, 0x7b, 0xef, 0xfd, 0x76, 0x66,
	0x5f, 0x06, 0x2e, 0x34, 0xab, 0xef, 0xaa, 0xe0, 0x8f, 0xd6, 0x8a, 0xdb, 0x9a, 0x55, 0xb1, 0x15,
	0x8d, 0xb9, 0xf9, 0x52, 0xd2, 0x48, 0x9c, 0x1c, 0xc3, 0xab, 0xdf, 0x08, 0xd2, 0xe7, 0xee, 0xc1,
	0xfc, 0xf5, 0x05, 0xa7, 0x10, 0x2d, 0x4a, 0xea, 0xcd, 0x7a, 0xd7, 0xc9, 0xc6, 0x2a, 0x3c, 0x85,
	0xe1, 0x63, 0x2d, 0xaa, 0x1d, 0x45, 0x3e, 0x0a, 0x06, 0x11, 0x06, 0x0f, 0xb2, 0x64, 0xea, 0xfb,
	0xd0, 0x6b, 0x97, 0x2d, 0xe5, 0xa7, 0xa4, 0x41, 0xc8, 0x9c, 0xc6, 0x4b, 0x48, 0x32, 0x2e, 0x14,
	0x9b, 0x27, 0xfe, 0xa1, 0xa1, 0x07, 0x87, 0xc0, 0x4d, 0x64, 0x62, 0x67, 0x28, 0x0e, 0x13, 0x4e,
	0xe3, 0x19, 0xc4, 0x6f, 0xb6, 0xd7, 0x62, 0x4e, 0x23, 0x9f, 0x76, 0x0e, 0x09, 0x46, 0xf7, 0x65,
	0xa9, 0x58, 0x6b, 0x1a, 0x7b, 0xb0, 0xb7, 0x8e, 0x2c, 0xab, 0xba, 0x32, 0x5c, 0x52, 0x62, 0x49,
	0x7f, 0xb3, 0xb7, 0x6e, 0xff, 0x4a, 0xd4, 0x4c, 0x10, 0xf6, 0x3b, 0x8d, 0x33, 0x48, 0xd7, 0x5b,
	0xd9, 0xf0, 0xaa, 0xad, 0x73, 0x56, 0x94, 0x7a, 0x74, 0x1c, 0xe1, 0x39, 0x8c, 0xd7, 0x42, 0x71,
	0x63, 0xec, 0x1d, 0x26, 0x1e, 0xff, 0x7b, 0xd7, 0x2e, 0x33, 0xc2, 0xb4, 0x9a, 0x4e, 0x42, 0xbb,
	0xe0, 0x5c, 0x87, 0x77, 0xce, 0xb5, 0xfd, 0x95, 0xa6, 0xa1, 0x5d, 0x67, 0xf3, 0xd8, 0x1f, 0xfd,
	0xee, 0x2f, 0x00, 0x00, 0xff, 0xff, 0xd6, 0x06, 0x68, 0x2b, 0x93, 0x01, 0x00, 0x00,
}
