// Code generated by protoc-gen-go. DO NOT EDIT.
// source: service_user/service.proto

package service_user

import (
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

/// ---- request ----
type CreateUserRequest struct {
	User                 *UserDTO `protobuf:"bytes,1,opt,name=User,proto3" json:"User,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *CreateUserRequest) Reset()         { *m = CreateUserRequest{} }
func (m *CreateUserRequest) String() string { return proto.CompactTextString(m) }
func (*CreateUserRequest) ProtoMessage()    {}
func (*CreateUserRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_9d59c98d0900be46, []int{0}
}

func (m *CreateUserRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_CreateUserRequest.Unmarshal(m, b)
}
func (m *CreateUserRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_CreateUserRequest.Marshal(b, m, deterministic)
}
func (m *CreateUserRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_CreateUserRequest.Merge(m, src)
}
func (m *CreateUserRequest) XXX_Size() int {
	return xxx_messageInfo_CreateUserRequest.Size(m)
}
func (m *CreateUserRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_CreateUserRequest.DiscardUnknown(m)
}

var xxx_messageInfo_CreateUserRequest proto.InternalMessageInfo

func (m *CreateUserRequest) GetUser() *UserDTO {
	if m != nil {
		return m.User
	}
	return nil
}

type UpdateUserRequest struct {
	User                 *UserDTO `protobuf:"bytes,1,opt,name=User,proto3" json:"User,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *UpdateUserRequest) Reset()         { *m = UpdateUserRequest{} }
func (m *UpdateUserRequest) String() string { return proto.CompactTextString(m) }
func (*UpdateUserRequest) ProtoMessage()    {}
func (*UpdateUserRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_9d59c98d0900be46, []int{1}
}

func (m *UpdateUserRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_UpdateUserRequest.Unmarshal(m, b)
}
func (m *UpdateUserRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_UpdateUserRequest.Marshal(b, m, deterministic)
}
func (m *UpdateUserRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_UpdateUserRequest.Merge(m, src)
}
func (m *UpdateUserRequest) XXX_Size() int {
	return xxx_messageInfo_UpdateUserRequest.Size(m)
}
func (m *UpdateUserRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_UpdateUserRequest.DiscardUnknown(m)
}

var xxx_messageInfo_UpdateUserRequest proto.InternalMessageInfo

func (m *UpdateUserRequest) GetUser() *UserDTO {
	if m != nil {
		return m.User
	}
	return nil
}

type FindUserByIdRequest struct {
	Id                   string   `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *FindUserByIdRequest) Reset()         { *m = FindUserByIdRequest{} }
func (m *FindUserByIdRequest) String() string { return proto.CompactTextString(m) }
func (*FindUserByIdRequest) ProtoMessage()    {}
func (*FindUserByIdRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_9d59c98d0900be46, []int{2}
}

func (m *FindUserByIdRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_FindUserByIdRequest.Unmarshal(m, b)
}
func (m *FindUserByIdRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_FindUserByIdRequest.Marshal(b, m, deterministic)
}
func (m *FindUserByIdRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_FindUserByIdRequest.Merge(m, src)
}
func (m *FindUserByIdRequest) XXX_Size() int {
	return xxx_messageInfo_FindUserByIdRequest.Size(m)
}
func (m *FindUserByIdRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_FindUserByIdRequest.DiscardUnknown(m)
}

var xxx_messageInfo_FindUserByIdRequest proto.InternalMessageInfo

func (m *FindUserByIdRequest) GetId() string {
	if m != nil {
		return m.Id
	}
	return ""
}

type FindUserByEmailRequest struct {
	Email                string   `protobuf:"bytes,1,opt,name=email,proto3" json:"email,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *FindUserByEmailRequest) Reset()         { *m = FindUserByEmailRequest{} }
func (m *FindUserByEmailRequest) String() string { return proto.CompactTextString(m) }
func (*FindUserByEmailRequest) ProtoMessage()    {}
func (*FindUserByEmailRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_9d59c98d0900be46, []int{3}
}

func (m *FindUserByEmailRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_FindUserByEmailRequest.Unmarshal(m, b)
}
func (m *FindUserByEmailRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_FindUserByEmailRequest.Marshal(b, m, deterministic)
}
func (m *FindUserByEmailRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_FindUserByEmailRequest.Merge(m, src)
}
func (m *FindUserByEmailRequest) XXX_Size() int {
	return xxx_messageInfo_FindUserByEmailRequest.Size(m)
}
func (m *FindUserByEmailRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_FindUserByEmailRequest.DiscardUnknown(m)
}

var xxx_messageInfo_FindUserByEmailRequest proto.InternalMessageInfo

func (m *FindUserByEmailRequest) GetEmail() string {
	if m != nil {
		return m.Email
	}
	return ""
}

type FindUserByPhoneRequest struct {
	Phone                string   `protobuf:"bytes,1,opt,name=phone,proto3" json:"phone,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *FindUserByPhoneRequest) Reset()         { *m = FindUserByPhoneRequest{} }
func (m *FindUserByPhoneRequest) String() string { return proto.CompactTextString(m) }
func (*FindUserByPhoneRequest) ProtoMessage()    {}
func (*FindUserByPhoneRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_9d59c98d0900be46, []int{4}
}

func (m *FindUserByPhoneRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_FindUserByPhoneRequest.Unmarshal(m, b)
}
func (m *FindUserByPhoneRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_FindUserByPhoneRequest.Marshal(b, m, deterministic)
}
func (m *FindUserByPhoneRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_FindUserByPhoneRequest.Merge(m, src)
}
func (m *FindUserByPhoneRequest) XXX_Size() int {
	return xxx_messageInfo_FindUserByPhoneRequest.Size(m)
}
func (m *FindUserByPhoneRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_FindUserByPhoneRequest.DiscardUnknown(m)
}

var xxx_messageInfo_FindUserByPhoneRequest proto.InternalMessageInfo

func (m *FindUserByPhoneRequest) GetPhone() string {
	if m != nil {
		return m.Phone
	}
	return ""
}

type FindUserDetailByPhoneRequest struct {
	Phone                string   `protobuf:"bytes,1,opt,name=phone,proto3" json:"phone,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *FindUserDetailByPhoneRequest) Reset()         { *m = FindUserDetailByPhoneRequest{} }
func (m *FindUserDetailByPhoneRequest) String() string { return proto.CompactTextString(m) }
func (*FindUserDetailByPhoneRequest) ProtoMessage()    {}
func (*FindUserDetailByPhoneRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_9d59c98d0900be46, []int{5}
}

func (m *FindUserDetailByPhoneRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_FindUserDetailByPhoneRequest.Unmarshal(m, b)
}
func (m *FindUserDetailByPhoneRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_FindUserDetailByPhoneRequest.Marshal(b, m, deterministic)
}
func (m *FindUserDetailByPhoneRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_FindUserDetailByPhoneRequest.Merge(m, src)
}
func (m *FindUserDetailByPhoneRequest) XXX_Size() int {
	return xxx_messageInfo_FindUserDetailByPhoneRequest.Size(m)
}
func (m *FindUserDetailByPhoneRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_FindUserDetailByPhoneRequest.DiscardUnknown(m)
}

var xxx_messageInfo_FindUserDetailByPhoneRequest proto.InternalMessageInfo

func (m *FindUserDetailByPhoneRequest) GetPhone() string {
	if m != nil {
		return m.Phone
	}
	return ""
}

type FindUserDetailByEmailRequest struct {
	Email                string   `protobuf:"bytes,1,opt,name=email,proto3" json:"email,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *FindUserDetailByEmailRequest) Reset()         { *m = FindUserDetailByEmailRequest{} }
func (m *FindUserDetailByEmailRequest) String() string { return proto.CompactTextString(m) }
func (*FindUserDetailByEmailRequest) ProtoMessage()    {}
func (*FindUserDetailByEmailRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_9d59c98d0900be46, []int{6}
}

func (m *FindUserDetailByEmailRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_FindUserDetailByEmailRequest.Unmarshal(m, b)
}
func (m *FindUserDetailByEmailRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_FindUserDetailByEmailRequest.Marshal(b, m, deterministic)
}
func (m *FindUserDetailByEmailRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_FindUserDetailByEmailRequest.Merge(m, src)
}
func (m *FindUserDetailByEmailRequest) XXX_Size() int {
	return xxx_messageInfo_FindUserDetailByEmailRequest.Size(m)
}
func (m *FindUserDetailByEmailRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_FindUserDetailByEmailRequest.DiscardUnknown(m)
}

var xxx_messageInfo_FindUserDetailByEmailRequest proto.InternalMessageInfo

func (m *FindUserDetailByEmailRequest) GetEmail() string {
	if m != nil {
		return m.Email
	}
	return ""
}

type FindUserDetailByIdRequest struct {
	Id                   string   `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *FindUserDetailByIdRequest) Reset()         { *m = FindUserDetailByIdRequest{} }
func (m *FindUserDetailByIdRequest) String() string { return proto.CompactTextString(m) }
func (*FindUserDetailByIdRequest) ProtoMessage()    {}
func (*FindUserDetailByIdRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_9d59c98d0900be46, []int{7}
}

func (m *FindUserDetailByIdRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_FindUserDetailByIdRequest.Unmarshal(m, b)
}
func (m *FindUserDetailByIdRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_FindUserDetailByIdRequest.Marshal(b, m, deterministic)
}
func (m *FindUserDetailByIdRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_FindUserDetailByIdRequest.Merge(m, src)
}
func (m *FindUserDetailByIdRequest) XXX_Size() int {
	return xxx_messageInfo_FindUserDetailByIdRequest.Size(m)
}
func (m *FindUserDetailByIdRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_FindUserDetailByIdRequest.DiscardUnknown(m)
}

var xxx_messageInfo_FindUserDetailByIdRequest proto.InternalMessageInfo

func (m *FindUserDetailByIdRequest) GetId() string {
	if m != nil {
		return m.Id
	}
	return ""
}

type FindMerchantAccountByCodeRequest struct {
	Code                 string   `protobuf:"bytes,1,opt,name=code,proto3" json:"code,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *FindMerchantAccountByCodeRequest) Reset()         { *m = FindMerchantAccountByCodeRequest{} }
func (m *FindMerchantAccountByCodeRequest) String() string { return proto.CompactTextString(m) }
func (*FindMerchantAccountByCodeRequest) ProtoMessage()    {}
func (*FindMerchantAccountByCodeRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_9d59c98d0900be46, []int{8}
}

func (m *FindMerchantAccountByCodeRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_FindMerchantAccountByCodeRequest.Unmarshal(m, b)
}
func (m *FindMerchantAccountByCodeRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_FindMerchantAccountByCodeRequest.Marshal(b, m, deterministic)
}
func (m *FindMerchantAccountByCodeRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_FindMerchantAccountByCodeRequest.Merge(m, src)
}
func (m *FindMerchantAccountByCodeRequest) XXX_Size() int {
	return xxx_messageInfo_FindMerchantAccountByCodeRequest.Size(m)
}
func (m *FindMerchantAccountByCodeRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_FindMerchantAccountByCodeRequest.DiscardUnknown(m)
}

var xxx_messageInfo_FindMerchantAccountByCodeRequest proto.InternalMessageInfo

func (m *FindMerchantAccountByCodeRequest) GetCode() string {
	if m != nil {
		return m.Code
	}
	return ""
}

type FindMerchantAccountByIdRequest struct {
	Id                   string   `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *FindMerchantAccountByIdRequest) Reset()         { *m = FindMerchantAccountByIdRequest{} }
func (m *FindMerchantAccountByIdRequest) String() string { return proto.CompactTextString(m) }
func (*FindMerchantAccountByIdRequest) ProtoMessage()    {}
func (*FindMerchantAccountByIdRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_9d59c98d0900be46, []int{9}
}

func (m *FindMerchantAccountByIdRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_FindMerchantAccountByIdRequest.Unmarshal(m, b)
}
func (m *FindMerchantAccountByIdRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_FindMerchantAccountByIdRequest.Marshal(b, m, deterministic)
}
func (m *FindMerchantAccountByIdRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_FindMerchantAccountByIdRequest.Merge(m, src)
}
func (m *FindMerchantAccountByIdRequest) XXX_Size() int {
	return xxx_messageInfo_FindMerchantAccountByIdRequest.Size(m)
}
func (m *FindMerchantAccountByIdRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_FindMerchantAccountByIdRequest.DiscardUnknown(m)
}

var xxx_messageInfo_FindMerchantAccountByIdRequest proto.InternalMessageInfo

func (m *FindMerchantAccountByIdRequest) GetId() string {
	if m != nil {
		return m.Id
	}
	return ""
}

type FindMerchantAccountByUserIdRequest struct {
	UserId               string   `protobuf:"bytes,1,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *FindMerchantAccountByUserIdRequest) Reset()         { *m = FindMerchantAccountByUserIdRequest{} }
func (m *FindMerchantAccountByUserIdRequest) String() string { return proto.CompactTextString(m) }
func (*FindMerchantAccountByUserIdRequest) ProtoMessage()    {}
func (*FindMerchantAccountByUserIdRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_9d59c98d0900be46, []int{10}
}

func (m *FindMerchantAccountByUserIdRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_FindMerchantAccountByUserIdRequest.Unmarshal(m, b)
}
func (m *FindMerchantAccountByUserIdRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_FindMerchantAccountByUserIdRequest.Marshal(b, m, deterministic)
}
func (m *FindMerchantAccountByUserIdRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_FindMerchantAccountByUserIdRequest.Merge(m, src)
}
func (m *FindMerchantAccountByUserIdRequest) XXX_Size() int {
	return xxx_messageInfo_FindMerchantAccountByUserIdRequest.Size(m)
}
func (m *FindMerchantAccountByUserIdRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_FindMerchantAccountByUserIdRequest.DiscardUnknown(m)
}

var xxx_messageInfo_FindMerchantAccountByUserIdRequest proto.InternalMessageInfo

func (m *FindMerchantAccountByUserIdRequest) GetUserId() string {
	if m != nil {
		return m.UserId
	}
	return ""
}

/// ---- response ----
type CreateUserResponse struct {
	User                 *UserDTO `protobuf:"bytes,1,opt,name=User,proto3" json:"User,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *CreateUserResponse) Reset()         { *m = CreateUserResponse{} }
func (m *CreateUserResponse) String() string { return proto.CompactTextString(m) }
func (*CreateUserResponse) ProtoMessage()    {}
func (*CreateUserResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_9d59c98d0900be46, []int{11}
}

func (m *CreateUserResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_CreateUserResponse.Unmarshal(m, b)
}
func (m *CreateUserResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_CreateUserResponse.Marshal(b, m, deterministic)
}
func (m *CreateUserResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_CreateUserResponse.Merge(m, src)
}
func (m *CreateUserResponse) XXX_Size() int {
	return xxx_messageInfo_CreateUserResponse.Size(m)
}
func (m *CreateUserResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_CreateUserResponse.DiscardUnknown(m)
}

var xxx_messageInfo_CreateUserResponse proto.InternalMessageInfo

func (m *CreateUserResponse) GetUser() *UserDTO {
	if m != nil {
		return m.User
	}
	return nil
}

type UpdateUserResponse struct {
	User                 *UserDTO `protobuf:"bytes,1,opt,name=User,proto3" json:"User,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *UpdateUserResponse) Reset()         { *m = UpdateUserResponse{} }
func (m *UpdateUserResponse) String() string { return proto.CompactTextString(m) }
func (*UpdateUserResponse) ProtoMessage()    {}
func (*UpdateUserResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_9d59c98d0900be46, []int{12}
}

func (m *UpdateUserResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_UpdateUserResponse.Unmarshal(m, b)
}
func (m *UpdateUserResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_UpdateUserResponse.Marshal(b, m, deterministic)
}
func (m *UpdateUserResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_UpdateUserResponse.Merge(m, src)
}
func (m *UpdateUserResponse) XXX_Size() int {
	return xxx_messageInfo_UpdateUserResponse.Size(m)
}
func (m *UpdateUserResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_UpdateUserResponse.DiscardUnknown(m)
}

var xxx_messageInfo_UpdateUserResponse proto.InternalMessageInfo

func (m *UpdateUserResponse) GetUser() *UserDTO {
	if m != nil {
		return m.User
	}
	return nil
}

type FindUserByIdResponse struct {
	User                 *UserDTO `protobuf:"bytes,1,opt,name=User,proto3" json:"User,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *FindUserByIdResponse) Reset()         { *m = FindUserByIdResponse{} }
func (m *FindUserByIdResponse) String() string { return proto.CompactTextString(m) }
func (*FindUserByIdResponse) ProtoMessage()    {}
func (*FindUserByIdResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_9d59c98d0900be46, []int{13}
}

func (m *FindUserByIdResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_FindUserByIdResponse.Unmarshal(m, b)
}
func (m *FindUserByIdResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_FindUserByIdResponse.Marshal(b, m, deterministic)
}
func (m *FindUserByIdResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_FindUserByIdResponse.Merge(m, src)
}
func (m *FindUserByIdResponse) XXX_Size() int {
	return xxx_messageInfo_FindUserByIdResponse.Size(m)
}
func (m *FindUserByIdResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_FindUserByIdResponse.DiscardUnknown(m)
}

var xxx_messageInfo_FindUserByIdResponse proto.InternalMessageInfo

func (m *FindUserByIdResponse) GetUser() *UserDTO {
	if m != nil {
		return m.User
	}
	return nil
}

type FindUserByEmailResponse struct {
	User                 *UserDTO `protobuf:"bytes,1,opt,name=User,proto3" json:"User,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *FindUserByEmailResponse) Reset()         { *m = FindUserByEmailResponse{} }
func (m *FindUserByEmailResponse) String() string { return proto.CompactTextString(m) }
func (*FindUserByEmailResponse) ProtoMessage()    {}
func (*FindUserByEmailResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_9d59c98d0900be46, []int{14}
}

func (m *FindUserByEmailResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_FindUserByEmailResponse.Unmarshal(m, b)
}
func (m *FindUserByEmailResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_FindUserByEmailResponse.Marshal(b, m, deterministic)
}
func (m *FindUserByEmailResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_FindUserByEmailResponse.Merge(m, src)
}
func (m *FindUserByEmailResponse) XXX_Size() int {
	return xxx_messageInfo_FindUserByEmailResponse.Size(m)
}
func (m *FindUserByEmailResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_FindUserByEmailResponse.DiscardUnknown(m)
}

var xxx_messageInfo_FindUserByEmailResponse proto.InternalMessageInfo

func (m *FindUserByEmailResponse) GetUser() *UserDTO {
	if m != nil {
		return m.User
	}
	return nil
}

type FindUserByPhoneResponse struct {
	User                 *UserDTO `protobuf:"bytes,1,opt,name=User,proto3" json:"User,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *FindUserByPhoneResponse) Reset()         { *m = FindUserByPhoneResponse{} }
func (m *FindUserByPhoneResponse) String() string { return proto.CompactTextString(m) }
func (*FindUserByPhoneResponse) ProtoMessage()    {}
func (*FindUserByPhoneResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_9d59c98d0900be46, []int{15}
}

func (m *FindUserByPhoneResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_FindUserByPhoneResponse.Unmarshal(m, b)
}
func (m *FindUserByPhoneResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_FindUserByPhoneResponse.Marshal(b, m, deterministic)
}
func (m *FindUserByPhoneResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_FindUserByPhoneResponse.Merge(m, src)
}
func (m *FindUserByPhoneResponse) XXX_Size() int {
	return xxx_messageInfo_FindUserByPhoneResponse.Size(m)
}
func (m *FindUserByPhoneResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_FindUserByPhoneResponse.DiscardUnknown(m)
}

var xxx_messageInfo_FindUserByPhoneResponse proto.InternalMessageInfo

func (m *FindUserByPhoneResponse) GetUser() *UserDTO {
	if m != nil {
		return m.User
	}
	return nil
}

type FindUserDetailByPhoneResponse struct {
	UserDetail           *UserDetailDTO `protobuf:"bytes,1,opt,name=UserDetail,proto3" json:"UserDetail,omitempty"`
	XXX_NoUnkeyedLiteral struct{}       `json:"-"`
	XXX_unrecognized     []byte         `json:"-"`
	XXX_sizecache        int32          `json:"-"`
}

func (m *FindUserDetailByPhoneResponse) Reset()         { *m = FindUserDetailByPhoneResponse{} }
func (m *FindUserDetailByPhoneResponse) String() string { return proto.CompactTextString(m) }
func (*FindUserDetailByPhoneResponse) ProtoMessage()    {}
func (*FindUserDetailByPhoneResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_9d59c98d0900be46, []int{16}
}

func (m *FindUserDetailByPhoneResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_FindUserDetailByPhoneResponse.Unmarshal(m, b)
}
func (m *FindUserDetailByPhoneResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_FindUserDetailByPhoneResponse.Marshal(b, m, deterministic)
}
func (m *FindUserDetailByPhoneResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_FindUserDetailByPhoneResponse.Merge(m, src)
}
func (m *FindUserDetailByPhoneResponse) XXX_Size() int {
	return xxx_messageInfo_FindUserDetailByPhoneResponse.Size(m)
}
func (m *FindUserDetailByPhoneResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_FindUserDetailByPhoneResponse.DiscardUnknown(m)
}

var xxx_messageInfo_FindUserDetailByPhoneResponse proto.InternalMessageInfo

func (m *FindUserDetailByPhoneResponse) GetUserDetail() *UserDetailDTO {
	if m != nil {
		return m.UserDetail
	}
	return nil
}

type FindUserDetailByEmailResponse struct {
	UserDetail           *UserDetailDTO `protobuf:"bytes,1,opt,name=UserDetail,proto3" json:"UserDetail,omitempty"`
	XXX_NoUnkeyedLiteral struct{}       `json:"-"`
	XXX_unrecognized     []byte         `json:"-"`
	XXX_sizecache        int32          `json:"-"`
}

func (m *FindUserDetailByEmailResponse) Reset()         { *m = FindUserDetailByEmailResponse{} }
func (m *FindUserDetailByEmailResponse) String() string { return proto.CompactTextString(m) }
func (*FindUserDetailByEmailResponse) ProtoMessage()    {}
func (*FindUserDetailByEmailResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_9d59c98d0900be46, []int{17}
}

func (m *FindUserDetailByEmailResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_FindUserDetailByEmailResponse.Unmarshal(m, b)
}
func (m *FindUserDetailByEmailResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_FindUserDetailByEmailResponse.Marshal(b, m, deterministic)
}
func (m *FindUserDetailByEmailResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_FindUserDetailByEmailResponse.Merge(m, src)
}
func (m *FindUserDetailByEmailResponse) XXX_Size() int {
	return xxx_messageInfo_FindUserDetailByEmailResponse.Size(m)
}
func (m *FindUserDetailByEmailResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_FindUserDetailByEmailResponse.DiscardUnknown(m)
}

var xxx_messageInfo_FindUserDetailByEmailResponse proto.InternalMessageInfo

func (m *FindUserDetailByEmailResponse) GetUserDetail() *UserDetailDTO {
	if m != nil {
		return m.UserDetail
	}
	return nil
}

type FindUserDetailByIdResponse struct {
	UserDetail           *UserDetailDTO `protobuf:"bytes,1,opt,name=UserDetail,proto3" json:"UserDetail,omitempty"`
	XXX_NoUnkeyedLiteral struct{}       `json:"-"`
	XXX_unrecognized     []byte         `json:"-"`
	XXX_sizecache        int32          `json:"-"`
}

func (m *FindUserDetailByIdResponse) Reset()         { *m = FindUserDetailByIdResponse{} }
func (m *FindUserDetailByIdResponse) String() string { return proto.CompactTextString(m) }
func (*FindUserDetailByIdResponse) ProtoMessage()    {}
func (*FindUserDetailByIdResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_9d59c98d0900be46, []int{18}
}

func (m *FindUserDetailByIdResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_FindUserDetailByIdResponse.Unmarshal(m, b)
}
func (m *FindUserDetailByIdResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_FindUserDetailByIdResponse.Marshal(b, m, deterministic)
}
func (m *FindUserDetailByIdResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_FindUserDetailByIdResponse.Merge(m, src)
}
func (m *FindUserDetailByIdResponse) XXX_Size() int {
	return xxx_messageInfo_FindUserDetailByIdResponse.Size(m)
}
func (m *FindUserDetailByIdResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_FindUserDetailByIdResponse.DiscardUnknown(m)
}

var xxx_messageInfo_FindUserDetailByIdResponse proto.InternalMessageInfo

func (m *FindUserDetailByIdResponse) GetUserDetail() *UserDetailDTO {
	if m != nil {
		return m.UserDetail
	}
	return nil
}

type FindMerchantAccountByCodeResponse struct {
	MerchantDetail       *MerchantDetailDTO `protobuf:"bytes,1,opt,name=MerchantDetail,proto3" json:"MerchantDetail,omitempty"`
	XXX_NoUnkeyedLiteral struct{}           `json:"-"`
	XXX_unrecognized     []byte             `json:"-"`
	XXX_sizecache        int32              `json:"-"`
}

func (m *FindMerchantAccountByCodeResponse) Reset()         { *m = FindMerchantAccountByCodeResponse{} }
func (m *FindMerchantAccountByCodeResponse) String() string { return proto.CompactTextString(m) }
func (*FindMerchantAccountByCodeResponse) ProtoMessage()    {}
func (*FindMerchantAccountByCodeResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_9d59c98d0900be46, []int{19}
}

func (m *FindMerchantAccountByCodeResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_FindMerchantAccountByCodeResponse.Unmarshal(m, b)
}
func (m *FindMerchantAccountByCodeResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_FindMerchantAccountByCodeResponse.Marshal(b, m, deterministic)
}
func (m *FindMerchantAccountByCodeResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_FindMerchantAccountByCodeResponse.Merge(m, src)
}
func (m *FindMerchantAccountByCodeResponse) XXX_Size() int {
	return xxx_messageInfo_FindMerchantAccountByCodeResponse.Size(m)
}
func (m *FindMerchantAccountByCodeResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_FindMerchantAccountByCodeResponse.DiscardUnknown(m)
}

var xxx_messageInfo_FindMerchantAccountByCodeResponse proto.InternalMessageInfo

func (m *FindMerchantAccountByCodeResponse) GetMerchantDetail() *MerchantDetailDTO {
	if m != nil {
		return m.MerchantDetail
	}
	return nil
}

type FindMerchantAccountByIdResponse struct {
	MerchantDetail       *MerchantDetailDTO `protobuf:"bytes,1,opt,name=MerchantDetail,proto3" json:"MerchantDetail,omitempty"`
	XXX_NoUnkeyedLiteral struct{}           `json:"-"`
	XXX_unrecognized     []byte             `json:"-"`
	XXX_sizecache        int32              `json:"-"`
}

func (m *FindMerchantAccountByIdResponse) Reset()         { *m = FindMerchantAccountByIdResponse{} }
func (m *FindMerchantAccountByIdResponse) String() string { return proto.CompactTextString(m) }
func (*FindMerchantAccountByIdResponse) ProtoMessage()    {}
func (*FindMerchantAccountByIdResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_9d59c98d0900be46, []int{20}
}

func (m *FindMerchantAccountByIdResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_FindMerchantAccountByIdResponse.Unmarshal(m, b)
}
func (m *FindMerchantAccountByIdResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_FindMerchantAccountByIdResponse.Marshal(b, m, deterministic)
}
func (m *FindMerchantAccountByIdResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_FindMerchantAccountByIdResponse.Merge(m, src)
}
func (m *FindMerchantAccountByIdResponse) XXX_Size() int {
	return xxx_messageInfo_FindMerchantAccountByIdResponse.Size(m)
}
func (m *FindMerchantAccountByIdResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_FindMerchantAccountByIdResponse.DiscardUnknown(m)
}

var xxx_messageInfo_FindMerchantAccountByIdResponse proto.InternalMessageInfo

func (m *FindMerchantAccountByIdResponse) GetMerchantDetail() *MerchantDetailDTO {
	if m != nil {
		return m.MerchantDetail
	}
	return nil
}

type FindMerchantAccountByUserIdResponse struct {
	MerchantDetail       *MerchantDetailDTO `protobuf:"bytes,1,opt,name=MerchantDetail,proto3" json:"MerchantDetail,omitempty"`
	XXX_NoUnkeyedLiteral struct{}           `json:"-"`
	XXX_unrecognized     []byte             `json:"-"`
	XXX_sizecache        int32              `json:"-"`
}

func (m *FindMerchantAccountByUserIdResponse) Reset()         { *m = FindMerchantAccountByUserIdResponse{} }
func (m *FindMerchantAccountByUserIdResponse) String() string { return proto.CompactTextString(m) }
func (*FindMerchantAccountByUserIdResponse) ProtoMessage()    {}
func (*FindMerchantAccountByUserIdResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_9d59c98d0900be46, []int{21}
}

func (m *FindMerchantAccountByUserIdResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_FindMerchantAccountByUserIdResponse.Unmarshal(m, b)
}
func (m *FindMerchantAccountByUserIdResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_FindMerchantAccountByUserIdResponse.Marshal(b, m, deterministic)
}
func (m *FindMerchantAccountByUserIdResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_FindMerchantAccountByUserIdResponse.Merge(m, src)
}
func (m *FindMerchantAccountByUserIdResponse) XXX_Size() int {
	return xxx_messageInfo_FindMerchantAccountByUserIdResponse.Size(m)
}
func (m *FindMerchantAccountByUserIdResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_FindMerchantAccountByUserIdResponse.DiscardUnknown(m)
}

var xxx_messageInfo_FindMerchantAccountByUserIdResponse proto.InternalMessageInfo

func (m *FindMerchantAccountByUserIdResponse) GetMerchantDetail() *MerchantDetailDTO {
	if m != nil {
		return m.MerchantDetail
	}
	return nil
}

func init() {
	proto.RegisterType((*CreateUserRequest)(nil), "service_user.CreateUserRequest")
	proto.RegisterType((*UpdateUserRequest)(nil), "service_user.UpdateUserRequest")
	proto.RegisterType((*FindUserByIdRequest)(nil), "service_user.FindUserByIdRequest")
	proto.RegisterType((*FindUserByEmailRequest)(nil), "service_user.FindUserByEmailRequest")
	proto.RegisterType((*FindUserByPhoneRequest)(nil), "service_user.FindUserByPhoneRequest")
	proto.RegisterType((*FindUserDetailByPhoneRequest)(nil), "service_user.FindUserDetailByPhoneRequest")
	proto.RegisterType((*FindUserDetailByEmailRequest)(nil), "service_user.FindUserDetailByEmailRequest")
	proto.RegisterType((*FindUserDetailByIdRequest)(nil), "service_user.FindUserDetailByIdRequest")
	proto.RegisterType((*FindMerchantAccountByCodeRequest)(nil), "service_user.FindMerchantAccountByCodeRequest")
	proto.RegisterType((*FindMerchantAccountByIdRequest)(nil), "service_user.FindMerchantAccountByIdRequest")
	proto.RegisterType((*FindMerchantAccountByUserIdRequest)(nil), "service_user.FindMerchantAccountByUserIdRequest")
	proto.RegisterType((*CreateUserResponse)(nil), "service_user.CreateUserResponse")
	proto.RegisterType((*UpdateUserResponse)(nil), "service_user.UpdateUserResponse")
	proto.RegisterType((*FindUserByIdResponse)(nil), "service_user.FindUserByIdResponse")
	proto.RegisterType((*FindUserByEmailResponse)(nil), "service_user.FindUserByEmailResponse")
	proto.RegisterType((*FindUserByPhoneResponse)(nil), "service_user.FindUserByPhoneResponse")
	proto.RegisterType((*FindUserDetailByPhoneResponse)(nil), "service_user.FindUserDetailByPhoneResponse")
	proto.RegisterType((*FindUserDetailByEmailResponse)(nil), "service_user.FindUserDetailByEmailResponse")
	proto.RegisterType((*FindUserDetailByIdResponse)(nil), "service_user.FindUserDetailByIdResponse")
	proto.RegisterType((*FindMerchantAccountByCodeResponse)(nil), "service_user.FindMerchantAccountByCodeResponse")
	proto.RegisterType((*FindMerchantAccountByIdResponse)(nil), "service_user.FindMerchantAccountByIdResponse")
	proto.RegisterType((*FindMerchantAccountByUserIdResponse)(nil), "service_user.FindMerchantAccountByUserIdResponse")
}

func init() {
	proto.RegisterFile("service_user/service.proto", fileDescriptor_9d59c98d0900be46)
}

var fileDescriptor_9d59c98d0900be46 = []byte{
	// 601 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x09, 0x6e, 0x88, 0x02, 0xff, 0xac, 0x56, 0x5b, 0x4f, 0xd4, 0x40,
	0x14, 0x76, 0x0d, 0x42, 0x38, 0x12, 0x8c, 0x23, 0xb8, 0x3a, 0x28, 0x2c, 0xa3, 0x44, 0x74, 0xb5,
	0x20, 0x1a, 0x5f, 0x8c, 0x1a, 0xa0, 0x6a, 0x7c, 0x30, 0xea, 0x2a, 0x31, 0x26, 0x26, 0xb8, 0xb6,
	0x93, 0x50, 0x03, 0xed, 0xda, 0xed, 0x1a, 0x79, 0xf1, 0xc9, 0x1f, 0xe2, 0x4f, 0xb5, 0x33, 0xbd,
	0xcd, 0x74, 0x66, 0xba, 0x2d, 0xbb, 0x2f, 0x64, 0x4e, 0xce, 0x77, 0x99, 0x32, 0xe7, 0xb2, 0x80,
	0x87, 0x34, 0xfc, 0xe5, 0x39, 0xf4, 0x70, 0x14, 0x1f, 0xb6, 0xd2, 0xc0, 0x1a, 0x84, 0x41, 0x14,
	0xa0, 0x05, 0x31, 0x87, 0xdb, 0x12, 0x92, 0xfd, 0x49, 0x60, 0x98, 0x48, 0x89, 0x13, 0x1a, 0x3a,
	0x47, 0x7d, 0x3f, 0x3a, 0x74, 0x69, 0xd4, 0xf7, 0x8e, 0x53, 0xcc, 0xaa, 0x42, 0x96, 0xf2, 0xe4,
	0x39, 0x5c, 0xde, 0x0f, 0x69, 0x3f, 0xa2, 0x07, 0x71, 0xaa, 0x47, 0x7f, 0x8e, 0xe8, 0x30, 0x42,
	0x77, 0x61, 0x86, 0x85, 0xd7, 0x5a, 0x9d, 0xd6, 0xe6, 0xc5, 0x9d, 0x65, 0x4b, 0xd4, 0xb0, 0x58,
	0xc6, 0xfe, 0xf4, 0xae, 0xc7, 0x21, 0x8c, 0x7f, 0x30, 0x70, 0xcf, 0xce, 0xdf, 0x80, 0x2b, 0xaf,
	0x3c, 0xdf, 0x65, 0xe7, 0xbd, 0xd3, 0x37, 0x6e, 0xa6, 0xb0, 0x08, 0xe7, 0x3d, 0x97, 0xf3, 0xe7,
	0x7b, 0xf1, 0x89, 0x58, 0x70, 0xb5, 0x80, 0xbd, 0x3c, 0x89, 0xef, 0x9f, 0x21, 0x97, 0xe0, 0x02,
	0x65, 0x71, 0x0a, 0x4e, 0x02, 0x19, 0xff, 0xfe, 0x28, 0xf0, 0xa9, 0x80, 0x1f, 0xb0, 0x38, 0xc3,
	0xf3, 0x80, 0x3c, 0x86, 0x1b, 0x19, 0xde, 0xe6, 0xff, 0x9e, 0xb3, 0xb2, 0x6a, 0xdc, 0xad, 0x0b,
	0xd7, 0xcb, 0x2c, 0xf3, 0x87, 0x3f, 0x81, 0x0e, 0x03, 0xbf, 0x4d, 0x1f, 0x77, 0xd7, 0x71, 0x82,
	0x91, 0x1f, 0xed, 0x9d, 0xee, 0x07, 0x6e, 0x7e, 0x39, 0x04, 0x33, 0x4e, 0x1c, 0xa6, 0x2c, 0x7e,
	0x26, 0xdb, 0xb0, 0xaa, 0xe5, 0x99, 0x9d, 0x9e, 0x01, 0xd1, 0x32, 0xd8, 0x3d, 0x0b, 0x56, 0x1b,
	0xe6, 0x78, 0x11, 0xe5, 0xd4, 0xd9, 0x11, 0xcf, 0x93, 0x17, 0x80, 0xc4, 0x42, 0x1a, 0x0e, 0x02,
	0x7f, 0x48, 0x9b, 0x54, 0x42, 0x2c, 0x20, 0x56, 0x52, 0x73, 0x81, 0x5d, 0x58, 0x92, 0x4b, 0xa9,
	0xb9, 0x84, 0x0d, 0x6d, 0xa5, 0xcc, 0x26, 0x54, 0x49, 0xcb, 0xa8, 0xb9, 0xca, 0x57, 0xb8, 0x69,
	0x28, 0xc9, 0x54, 0xeb, 0x29, 0x40, 0x91, 0x4c, 0x15, 0x57, 0x34, 0x8a, 0x3c, 0xcf, 0x74, 0x05,
	0xb8, 0x4e, 0x5d, 0xfe, 0xde, 0x89, 0xd4, 0xbf, 0x00, 0xd6, 0x95, 0xf8, 0x34, 0xa4, 0x8f, 0x61,
	0xbd, 0xa2, 0x21, 0x52, 0x87, 0xd7, 0xb0, 0x98, 0x01, 0x24, 0x97, 0x35, 0xd9, 0x45, 0xc6, 0x30,
	0xa7, 0x12, 0x8d, 0xfc, 0x80, 0x35, 0x63, 0x1b, 0x4d, 0xdb, 0xcb, 0x87, 0x5b, 0x95, 0x0d, 0x38,
	0x65, 0xbf, 0x9d, 0x7f, 0xf3, 0x30, 0xf7, 0x31, 0xa1, 0xa0, 0x0f, 0x00, 0x45, 0xf7, 0xa2, 0x92,
	0x94, 0xb2, 0x20, 0x70, 0xc7, 0x0c, 0x48, 0x6e, 0x49, 0xce, 0x31, 0xc9, 0xa2, 0x9f, 0xcb, 0x92,
	0xca, 0xce, 0x28, 0x4b, 0xaa, 0xa3, 0x20, 0x96, 0xfc, 0x0c, 0x0b, 0x62, 0x87, 0xa3, 0x75, 0x99,
	0xa3, 0x59, 0x24, 0x98, 0x54, 0x41, 0x72, 0xe1, 0x6f, 0x70, 0xa9, 0xd4, 0xf7, 0xe8, 0xb6, 0x89,
	0x28, 0x4e, 0x78, 0xbc, 0x31, 0x06, 0xa5, 0x77, 0xe0, 0x7d, 0x6c, 0x76, 0x10, 0x37, 0x8f, 0xd9,
	0x41, 0x1a, 0x06, 0xb1, 0x83, 0x07, 0x48, 0xed, 0x39, 0x74, 0x47, 0x4f, 0x57, 0x16, 0x0f, 0xde,
	0x1c, 0x0f, 0xcc, 0xad, 0x42, 0x58, 0xd6, 0x8e, 0x26, 0x74, 0xaf, 0x5a, 0x44, 0xfa, 0xb0, 0x6e,
	0x2d, 0x6c, 0x95, 0x67, 0xf2, 0x50, 0x63, 0x3c, 0xa5, 0xe7, 0xea, 0xd6, 0xc2, 0xe6, 0x9e, 0x7f,
	0x92, 0x4d, 0xad, 0x9d, 0x35, 0xc8, 0x52, 0xb5, 0xaa, 0xb6, 0x34, 0xde, 0xaa, 0x8d, 0xcf, 0xfd,
	0x7f, 0x27, 0x8b, 0x44, 0x9d, 0x3e, 0x36, 0xba, 0x5f, 0x43, 0xad, 0x78, 0xdc, 0x07, 0x35, 0xd1,
	0xb9, 0xf3, 0xdf, 0x16, 0xac, 0x98, 0x87, 0x91, 0x8d, 0xb6, 0x6b, 0x08, 0x4a, 0x3f, 0x1c, 0xf0,
	0xc3, 0x06, 0x8c, 0xec, 0x1a, 0xdf, 0x67, 0xf9, 0x8f, 0xd4, 0x47, 0xff, 0x03, 0x00, 0x00, 0xff,
	0xff, 0x1f, 0xa0, 0x73, 0xc3, 0x2d, 0x0b, 0x00, 0x00,
}
