// Code generated by protoc-gen-go. DO NOT EDIT.
// source: service_user/user_detail.proto

package service_user

import (
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

type UserDetailDTO struct {
	User                 *UserDTO      `protobuf:"bytes,1,opt,name=User,proto3" json:"User,omitempty"`
	Balances             []*BalanceDTO `protobuf:"bytes,2,rep,name=Balances,proto3" json:"Balances,omitempty"`
	XXX_NoUnkeyedLiteral struct{}      `json:"-"`
	XXX_unrecognized     []byte        `json:"-"`
	XXX_sizecache        int32         `json:"-"`
}

func (m *UserDetailDTO) Reset()         { *m = UserDetailDTO{} }
func (m *UserDetailDTO) String() string { return proto.CompactTextString(m) }
func (*UserDetailDTO) ProtoMessage()    {}
func (*UserDetailDTO) Descriptor() ([]byte, []int) {
	return fileDescriptor_bdead03259e3e62e, []int{0}
}

func (m *UserDetailDTO) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_UserDetailDTO.Unmarshal(m, b)
}
func (m *UserDetailDTO) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_UserDetailDTO.Marshal(b, m, deterministic)
}
func (m *UserDetailDTO) XXX_Merge(src proto.Message) {
	xxx_messageInfo_UserDetailDTO.Merge(m, src)
}
func (m *UserDetailDTO) XXX_Size() int {
	return xxx_messageInfo_UserDetailDTO.Size(m)
}
func (m *UserDetailDTO) XXX_DiscardUnknown() {
	xxx_messageInfo_UserDetailDTO.DiscardUnknown(m)
}

var xxx_messageInfo_UserDetailDTO proto.InternalMessageInfo

func (m *UserDetailDTO) GetUser() *UserDTO {
	if m != nil {
		return m.User
	}
	return nil
}

func (m *UserDetailDTO) GetBalances() []*BalanceDTO {
	if m != nil {
		return m.Balances
	}
	return nil
}

func init() {
	proto.RegisterType((*UserDetailDTO)(nil), "service_user.UserDetailDTO")
}

func init() {
	proto.RegisterFile("service_user/user_detail.proto", fileDescriptor_bdead03259e3e62e)
}

var fileDescriptor_bdead03259e3e62e = []byte{
	// 142 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x09, 0x6e, 0x88, 0x02, 0xff, 0xe2, 0x92, 0x2b, 0x4e, 0x2d, 0x2a,
	0xcb, 0x4c, 0x4e, 0x8d, 0x2f, 0x05, 0x32, 0xf4, 0x41, 0x44, 0x7c, 0x4a, 0x6a, 0x49, 0x62, 0x66,
	0x8e, 0x5e, 0x41, 0x51, 0x7e, 0x49, 0xbe, 0x10, 0x0f, 0xb2, 0xbc, 0x94, 0x38, 0x86, 0x6a, 0x88,
	0x32, 0x29, 0x29, 0x14, 0x89, 0xa4, 0xc4, 0x9c, 0xc4, 0xbc, 0xe4, 0x54, 0x88, 0x9c, 0x52, 0x01,
	0x17, 0x6f, 0x28, 0x50, 0xd4, 0x05, 0x6c, 0xac, 0x4b, 0x88, 0xbf, 0x90, 0x26, 0x17, 0x0b, 0x48,
	0x40, 0x82, 0x51, 0x81, 0x51, 0x83, 0xdb, 0x48, 0x54, 0x0f, 0x59, 0xaf, 0x1e, 0x58, 0x69, 0x88,
	0x7f, 0x10, 0x58, 0x89, 0x90, 0x09, 0x17, 0x87, 0x13, 0xc4, 0xb0, 0x62, 0x09, 0x26, 0x05, 0x66,
	0xa0, 0x72, 0x09, 0x54, 0xe5, 0x50, 0x59, 0x90, 0x0e, 0xb8, 0xca, 0x24, 0x36, 0xb0, 0xc5, 0xc6,
	0x80, 0x00, 0x00, 0x00, 0xff, 0xff, 0xfb, 0xd3, 0x56, 0x90, 0xdd, 0x00, 0x00, 0x00,
}
