// Code generated by protoc-gen-go. DO NOT EDIT.
// source: service_core/balance.proto

package service_core

import (
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

type BalanceDTO struct {
	Id                   string   `protobuf:"bytes,1,opt,name=id,proto3" json:"id"`
	AmountAvailable      int64    `protobuf:"varint,2,opt,name=amountAvailable,proto3" json:"amountAvailable"`
	AmountFreeze         int64    `protobuf:"varint,3,opt,name=amountFreeze,proto3" json:"amountFreeze"`
	Type                 string   `protobuf:"bytes,4,opt,name=type,proto3" json:"type"`
	UserId               string   `protobuf:"bytes,5,opt,name=userId,proto3" json:"userId"`
	FreezeIds            []string `protobuf:"bytes,6,rep,name=freezeIds,proto3" json:"freezeIds"`
	Currency             string   `protobuf:"bytes,7,opt,name=currency,proto3" json:"currency"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *BalanceDTO) Reset()         { *m = BalanceDTO{} }
func (m *BalanceDTO) String() string { return proto.CompactTextString(m) }
func (*BalanceDTO) ProtoMessage()    {}
func (*BalanceDTO) Descriptor() ([]byte, []int) {
	return fileDescriptor_aab2670abd0875a6, []int{0}
}

func (m *BalanceDTO) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_BalanceDTO.Unmarshal(m, b)
}
func (m *BalanceDTO) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_BalanceDTO.Marshal(b, m, deterministic)
}
func (m *BalanceDTO) XXX_Merge(src proto.Message) {
	xxx_messageInfo_BalanceDTO.Merge(m, src)
}
func (m *BalanceDTO) XXX_Size() int {
	return xxx_messageInfo_BalanceDTO.Size(m)
}
func (m *BalanceDTO) XXX_DiscardUnknown() {
	xxx_messageInfo_BalanceDTO.DiscardUnknown(m)
}

var xxx_messageInfo_BalanceDTO proto.InternalMessageInfo

func (m *BalanceDTO) GetId() string {
	if m != nil {
		return m.Id
	}
	return ""
}

func (m *BalanceDTO) GetAmountAvailable() int64 {
	if m != nil {
		return m.AmountAvailable
	}
	return 0
}

func (m *BalanceDTO) GetAmountFreeze() int64 {
	if m != nil {
		return m.AmountFreeze
	}
	return 0
}

func (m *BalanceDTO) GetType() string {
	if m != nil {
		return m.Type
	}
	return ""
}

func (m *BalanceDTO) GetUserId() string {
	if m != nil {
		return m.UserId
	}
	return ""
}

func (m *BalanceDTO) GetFreezeIds() []string {
	if m != nil {
		return m.FreezeIds
	}
	return nil
}

func (m *BalanceDTO) GetCurrency() string {
	if m != nil {
		return m.Currency
	}
	return ""
}

//balances
type BalancesDTO struct {
	Balances             []*BalanceDTO `protobuf:"bytes,1,rep,name=balances,proto3" json:"balances"`
	XXX_NoUnkeyedLiteral struct{}      `json:"-"`
	XXX_unrecognized     []byte        `json:"-"`
	XXX_sizecache        int32         `json:"-"`
}

func (m *BalancesDTO) Reset()         { *m = BalancesDTO{} }
func (m *BalancesDTO) String() string { return proto.CompactTextString(m) }
func (*BalancesDTO) ProtoMessage()    {}
func (*BalancesDTO) Descriptor() ([]byte, []int) {
	return fileDescriptor_aab2670abd0875a6, []int{1}
}

func (m *BalancesDTO) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_BalancesDTO.Unmarshal(m, b)
}
func (m *BalancesDTO) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_BalancesDTO.Marshal(b, m, deterministic)
}
func (m *BalancesDTO) XXX_Merge(src proto.Message) {
	xxx_messageInfo_BalancesDTO.Merge(m, src)
}
func (m *BalancesDTO) XXX_Size() int {
	return xxx_messageInfo_BalancesDTO.Size(m)
}
func (m *BalancesDTO) XXX_DiscardUnknown() {
	xxx_messageInfo_BalancesDTO.DiscardUnknown(m)
}

var xxx_messageInfo_BalancesDTO proto.InternalMessageInfo

func (m *BalancesDTO) GetBalances() []*BalanceDTO {
	if m != nil {
		return m.Balances
	}
	return nil
}

func init() {
	proto.RegisterType((*BalanceDTO)(nil), "service_core.BalanceDTO")
	proto.RegisterType((*BalancesDTO)(nil), "service_core.BalancesDTO")
}

func init() {
	proto.RegisterFile("service_core/balance.proto", fileDescriptor_aab2670abd0875a6)
}

var fileDescriptor_aab2670abd0875a6 = []byte{
	// 232 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x5c, 0x90, 0x5f, 0x4b, 0xc3, 0x30,
	0x14, 0xc5, 0x49, 0x3b, 0xeb, 0x7a, 0x37, 0x14, 0xee, 0x83, 0x5c, 0x86, 0x0f, 0xa5, 0x4f, 0x79,
	0xaa, 0xa0, 0x7e, 0x01, 0xff, 0x20, 0xec, 0x49, 0x08, 0xbe, 0x4b, 0x9a, 0x5c, 0x21, 0x50, 0x9b,
	0x91, 0xb4, 0x83, 0xf9, 0x29, 0xfd, 0x48, 0x62, 0x56, 0xb6, 0xe9, 0x5b, 0xee, 0xef, 0x9c, 0x13,
	0x38, 0x07, 0x56, 0x91, 0xc3, 0xd6, 0x19, 0x7e, 0x37, 0x3e, 0xf0, 0x4d, 0xab, 0x3b, 0xdd, 0x1b,
	0x6e, 0x36, 0xc1, 0x0f, 0x1e, 0x97, 0xa7, 0x5a, 0xfd, 0x2d, 0x00, 0x1e, 0xf7, 0xfa, 0xf3, 0xdb,
	0x2b, 0x5e, 0x40, 0xe6, 0x2c, 0x89, 0x4a, 0xc8, 0x52, 0x65, 0xce, 0xa2, 0x84, 0x4b, 0xfd, 0xe9,
	0xc7, 0x7e, 0x78, 0xd8, 0x6a, 0xd7, 0xe9, 0xb6, 0x63, 0xca, 0x2a, 0x21, 0x73, 0xf5, 0x1f, 0x63,
	0x0d, 0xcb, 0x3d, 0x7a, 0x09, 0xcc, 0x5f, 0x4c, 0x79, 0xb2, 0xfd, 0x61, 0x88, 0x30, 0x1b, 0x76,
	0x1b, 0xa6, 0x59, 0xfa, 0x3f, 0xbd, 0xf1, 0x0a, 0x8a, 0x31, 0x72, 0x58, 0x5b, 0x3a, 0x4b, 0x74,
	0xba, 0xf0, 0x1a, 0xca, 0x8f, 0x94, 0x5a, 0xdb, 0x48, 0x45, 0x95, 0xcb, 0x52, 0x1d, 0x01, 0xae,
	0x60, 0x6e, 0xc6, 0x10, 0xb8, 0x37, 0x3b, 0x3a, 0x4f, 0xb9, 0xc3, 0x5d, 0x3f, 0xc1, 0x62, 0x6a,
	0x14, 0x7f, 0x2b, 0xdd, 0xc3, 0x7c, 0x1a, 0x20, 0x92, 0xa8, 0x72, 0xb9, 0xb8, 0xa5, 0xe6, 0x74,
	0x82, 0xe6, 0x58, 0x5f, 0x1d, 0x9c, 0x6d, 0x91, 0xc6, 0xba, 0xfb, 0x09, 0x00, 0x00, 0xff, 0xff,
	0xb4, 0x8e, 0x34, 0xb6, 0x4a, 0x01, 0x00, 0x00,
}
