// Code generated by mockery v2.0.4. DO NOT EDIT.

package mocks

import (
	mock "github.com/stretchr/testify/mock"
	entities "gitlab.com/wallet-gpay/service-promotion/service_promotion/pkg/models/entities"
)

// IPopup is an autogenerated mock type for the IPopup type
type IPopup struct {
	mock.Mock
}

// GetList provides a mock function with given fields: user_id
func (_m *IPopup) GetList(user_id string) ([]*entities.PopUp, error) {
	ret := _m.Called(user_id)

	var r0 []*entities.PopUp
	if rf, ok := ret.Get(0).(func(string) []*entities.PopUp); ok {
		r0 = rf(user_id)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]*entities.PopUp)
		}
	}

	var r1 error
	if rf, ok := ret.Get(1).(func(string) error); ok {
		r1 = rf(user_id)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}
