// Code generated by mockery v2.0.4. DO NOT EDIT.

package mocks

import mock "github.com/stretchr/testify/mock"

// IUserApplyVoucher is an autogenerated mock type for the IUserApplyVoucher type
type IUserApplyVoucher struct {
	mock.Mock
}

// CheckApplied provides a mock function with given fields: userid, promoid
func (_m *IUserApplyVoucher) CheckApplied(userid string, promoid string) (int64, error) {
	ret := _m.Called(userid, promoid)

	var r0 int64
	if rf, ok := ret.Get(0).(func(string, string) int64); ok {
		r0 = rf(userid, promoid)
	} else {
		r0 = ret.Get(0).(int64)
	}

	var r1 error
	if rf, ok := ret.Get(1).(func(string, string) error); ok {
		r1 = rf(userid, promoid)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}
