// Code generated by protoc-gen-go. DO NOT EDIT.
// source: service_merchant_fee/service.proto

package service_merchant_fee

import proto "github.com/golang/protobuf/proto"
import fmt "fmt"
import math "math"

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion2 // please upgrade the proto package

type FeeCheckLogStatus int32

const (
	FeeCheckLogStatus_PROCESSING FeeCheckLogStatus = 0
	FeeCheckLogStatus_PENDING    FeeCheckLogStatus = 1
	FeeCheckLogStatus_SUCCESS    FeeCheckLogStatus = 2
)

var FeeCheckLogStatus_name = map[int32]string{
	0: "PROCESSING",
	1: "PENDING",
	2: "SUCCESS",
}
var FeeCheckLogStatus_value = map[string]int32{
	"PROCESSING": 0,
	"PENDING":    1,
	"SUCCESS":    2,
}

func (x FeeCheckLogStatus) String() string {
	return proto.EnumName(FeeCheckLogStatus_name, int32(x))
}
func (FeeCheckLogStatus) EnumDescriptor() ([]byte, []int) {
	return fileDescriptor_service_6256f3cfcc50a5b4, []int{0}
}

type CreateFeeCheckLogReq_TimeType int32

const (
	CreateFeeCheckLogReq_DAY    CreateFeeCheckLogReq_TimeType = 0
	CreateFeeCheckLogReq_MONTH  CreateFeeCheckLogReq_TimeType = 1
	CreateFeeCheckLogReq_PERIOD CreateFeeCheckLogReq_TimeType = 2
)

var CreateFeeCheckLogReq_TimeType_name = map[int32]string{
	0: "DAY",
	1: "MONTH",
	2: "PERIOD",
}
var CreateFeeCheckLogReq_TimeType_value = map[string]int32{
	"DAY":    0,
	"MONTH":  1,
	"PERIOD": 2,
}

func (x CreateFeeCheckLogReq_TimeType) String() string {
	return proto.EnumName(CreateFeeCheckLogReq_TimeType_name, int32(x))
}
func (CreateFeeCheckLogReq_TimeType) EnumDescriptor() ([]byte, []int) {
	return fileDescriptor_service_6256f3cfcc50a5b4, []int{4, 0}
}

type CheckMerchantQuotaAndFeeRes_FeeMethod int32

const (
	CheckMerchantQuotaAndFeeRes_FEE_NOW   CheckMerchantQuotaAndFeeRes_FeeMethod = 0
	CheckMerchantQuotaAndFeeRes_FEE_LATER CheckMerchantQuotaAndFeeRes_FeeMethod = 1
)

var CheckMerchantQuotaAndFeeRes_FeeMethod_name = map[int32]string{
	0: "FEE_NOW",
	1: "FEE_LATER",
}
var CheckMerchantQuotaAndFeeRes_FeeMethod_value = map[string]int32{
	"FEE_NOW":   0,
	"FEE_LATER": 1,
}

func (x CheckMerchantQuotaAndFeeRes_FeeMethod) String() string {
	return proto.EnumName(CheckMerchantQuotaAndFeeRes_FeeMethod_name, int32(x))
}
func (CheckMerchantQuotaAndFeeRes_FeeMethod) EnumDescriptor() ([]byte, []int) {
	return fileDescriptor_service_6256f3cfcc50a5b4, []int{11, 0}
}

type SettlementReq struct {
	Id                   string   `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *SettlementReq) Reset()         { *m = SettlementReq{} }
func (m *SettlementReq) String() string { return proto.CompactTextString(m) }
func (*SettlementReq) ProtoMessage()    {}
func (*SettlementReq) Descriptor() ([]byte, []int) {
	return fileDescriptor_service_6256f3cfcc50a5b4, []int{0}
}
func (m *SettlementReq) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_SettlementReq.Unmarshal(m, b)
}
func (m *SettlementReq) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_SettlementReq.Marshal(b, m, deterministic)
}
func (dst *SettlementReq) XXX_Merge(src proto.Message) {
	xxx_messageInfo_SettlementReq.Merge(dst, src)
}
func (m *SettlementReq) XXX_Size() int {
	return xxx_messageInfo_SettlementReq.Size(m)
}
func (m *SettlementReq) XXX_DiscardUnknown() {
	xxx_messageInfo_SettlementReq.DiscardUnknown(m)
}

var xxx_messageInfo_SettlementReq proto.InternalMessageInfo

func (m *SettlementReq) GetId() string {
	if m != nil {
		return m.Id
	}
	return ""
}

type SettlementRes struct {
	Success              bool     `protobuf:"varint,1,opt,name=success,proto3" json:"success,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *SettlementRes) Reset()         { *m = SettlementRes{} }
func (m *SettlementRes) String() string { return proto.CompactTextString(m) }
func (*SettlementRes) ProtoMessage()    {}
func (*SettlementRes) Descriptor() ([]byte, []int) {
	return fileDescriptor_service_6256f3cfcc50a5b4, []int{1}
}
func (m *SettlementRes) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_SettlementRes.Unmarshal(m, b)
}
func (m *SettlementRes) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_SettlementRes.Marshal(b, m, deterministic)
}
func (dst *SettlementRes) XXX_Merge(src proto.Message) {
	xxx_messageInfo_SettlementRes.Merge(dst, src)
}
func (m *SettlementRes) XXX_Size() int {
	return xxx_messageInfo_SettlementRes.Size(m)
}
func (m *SettlementRes) XXX_DiscardUnknown() {
	xxx_messageInfo_SettlementRes.DiscardUnknown(m)
}

var xxx_messageInfo_SettlementRes proto.InternalMessageInfo

func (m *SettlementRes) GetSuccess() bool {
	if m != nil {
		return m.Success
	}
	return false
}

type CrossCheckStatusUpdatesReq struct {
	MerchantId             string   `protobuf:"bytes,1,opt,name=merchant_id,json=merchantId,proto3" json:"merchant_id,omitempty"`
	TransactionIds         []string `protobuf:"bytes,2,rep,name=transaction_ids,json=transactionIds,proto3" json:"transaction_ids,omitempty"`
	Status                 string   `protobuf:"bytes,3,opt,name=status,proto3" json:"status,omitempty"`
	NewCrossCheckTimestamp int64    `protobuf:"varint,4,opt,name=new_cross_check_timestamp,json=newCrossCheckTimestamp,proto3" json:"new_cross_check_timestamp,omitempty"`
	Reason                 string   `protobuf:"bytes,5,opt,name=reason,proto3" json:"reason,omitempty"`
	XXX_NoUnkeyedLiteral   struct{} `json:"-"`
	XXX_unrecognized       []byte   `json:"-"`
	XXX_sizecache          int32    `json:"-"`
}

func (m *CrossCheckStatusUpdatesReq) Reset()         { *m = CrossCheckStatusUpdatesReq{} }
func (m *CrossCheckStatusUpdatesReq) String() string { return proto.CompactTextString(m) }
func (*CrossCheckStatusUpdatesReq) ProtoMessage()    {}
func (*CrossCheckStatusUpdatesReq) Descriptor() ([]byte, []int) {
	return fileDescriptor_service_6256f3cfcc50a5b4, []int{2}
}
func (m *CrossCheckStatusUpdatesReq) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_CrossCheckStatusUpdatesReq.Unmarshal(m, b)
}
func (m *CrossCheckStatusUpdatesReq) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_CrossCheckStatusUpdatesReq.Marshal(b, m, deterministic)
}
func (dst *CrossCheckStatusUpdatesReq) XXX_Merge(src proto.Message) {
	xxx_messageInfo_CrossCheckStatusUpdatesReq.Merge(dst, src)
}
func (m *CrossCheckStatusUpdatesReq) XXX_Size() int {
	return xxx_messageInfo_CrossCheckStatusUpdatesReq.Size(m)
}
func (m *CrossCheckStatusUpdatesReq) XXX_DiscardUnknown() {
	xxx_messageInfo_CrossCheckStatusUpdatesReq.DiscardUnknown(m)
}

var xxx_messageInfo_CrossCheckStatusUpdatesReq proto.InternalMessageInfo

func (m *CrossCheckStatusUpdatesReq) GetMerchantId() string {
	if m != nil {
		return m.MerchantId
	}
	return ""
}

func (m *CrossCheckStatusUpdatesReq) GetTransactionIds() []string {
	if m != nil {
		return m.TransactionIds
	}
	return nil
}

func (m *CrossCheckStatusUpdatesReq) GetStatus() string {
	if m != nil {
		return m.Status
	}
	return ""
}

func (m *CrossCheckStatusUpdatesReq) GetNewCrossCheckTimestamp() int64 {
	if m != nil {
		return m.NewCrossCheckTimestamp
	}
	return 0
}

func (m *CrossCheckStatusUpdatesReq) GetReason() string {
	if m != nil {
		return m.Reason
	}
	return ""
}

type CrossCheckStatusUpdatesRes struct {
	Success              bool     `protobuf:"varint,1,opt,name=success,proto3" json:"success,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *CrossCheckStatusUpdatesRes) Reset()         { *m = CrossCheckStatusUpdatesRes{} }
func (m *CrossCheckStatusUpdatesRes) String() string { return proto.CompactTextString(m) }
func (*CrossCheckStatusUpdatesRes) ProtoMessage()    {}
func (*CrossCheckStatusUpdatesRes) Descriptor() ([]byte, []int) {
	return fileDescriptor_service_6256f3cfcc50a5b4, []int{3}
}
func (m *CrossCheckStatusUpdatesRes) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_CrossCheckStatusUpdatesRes.Unmarshal(m, b)
}
func (m *CrossCheckStatusUpdatesRes) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_CrossCheckStatusUpdatesRes.Marshal(b, m, deterministic)
}
func (dst *CrossCheckStatusUpdatesRes) XXX_Merge(src proto.Message) {
	xxx_messageInfo_CrossCheckStatusUpdatesRes.Merge(dst, src)
}
func (m *CrossCheckStatusUpdatesRes) XXX_Size() int {
	return xxx_messageInfo_CrossCheckStatusUpdatesRes.Size(m)
}
func (m *CrossCheckStatusUpdatesRes) XXX_DiscardUnknown() {
	xxx_messageInfo_CrossCheckStatusUpdatesRes.DiscardUnknown(m)
}

var xxx_messageInfo_CrossCheckStatusUpdatesRes proto.InternalMessageInfo

func (m *CrossCheckStatusUpdatesRes) GetSuccess() bool {
	if m != nil {
		return m.Success
	}
	return false
}

type CreateFeeCheckLogReq struct {
	Status               FeeCheckLogStatus             `protobuf:"varint,1,opt,name=status,proto3,enum=service_merchant_fee.FeeCheckLogStatus" json:"status,omitempty"`
	TimeType             CreateFeeCheckLogReq_TimeType `protobuf:"varint,2,opt,name=time_type,json=timeType,proto3,enum=service_merchant_fee.CreateFeeCheckLogReq_TimeType" json:"time_type,omitempty"`
	Timestamp            int64                         `protobuf:"varint,3,opt,name=timestamp,proto3" json:"timestamp,omitempty"`
	MerchantId           string                        `protobuf:"bytes,4,opt,name=merchant_id,json=merchantId,proto3" json:"merchant_id,omitempty"`
	ServiceType          string                        `protobuf:"bytes,5,opt,name=service_type,json=serviceType,proto3" json:"service_type,omitempty"`
	TransType            string                        `protobuf:"bytes,6,opt,name=trans_type,json=transType,proto3" json:"trans_type,omitempty"`
	Testing              bool                          `protobuf:"varint,7,opt,name=testing,proto3" json:"testing,omitempty"`
	XXX_NoUnkeyedLiteral struct{}                      `json:"-"`
	XXX_unrecognized     []byte                        `json:"-"`
	XXX_sizecache        int32                         `json:"-"`
}

func (m *CreateFeeCheckLogReq) Reset()         { *m = CreateFeeCheckLogReq{} }
func (m *CreateFeeCheckLogReq) String() string { return proto.CompactTextString(m) }
func (*CreateFeeCheckLogReq) ProtoMessage()    {}
func (*CreateFeeCheckLogReq) Descriptor() ([]byte, []int) {
	return fileDescriptor_service_6256f3cfcc50a5b4, []int{4}
}
func (m *CreateFeeCheckLogReq) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_CreateFeeCheckLogReq.Unmarshal(m, b)
}
func (m *CreateFeeCheckLogReq) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_CreateFeeCheckLogReq.Marshal(b, m, deterministic)
}
func (dst *CreateFeeCheckLogReq) XXX_Merge(src proto.Message) {
	xxx_messageInfo_CreateFeeCheckLogReq.Merge(dst, src)
}
func (m *CreateFeeCheckLogReq) XXX_Size() int {
	return xxx_messageInfo_CreateFeeCheckLogReq.Size(m)
}
func (m *CreateFeeCheckLogReq) XXX_DiscardUnknown() {
	xxx_messageInfo_CreateFeeCheckLogReq.DiscardUnknown(m)
}

var xxx_messageInfo_CreateFeeCheckLogReq proto.InternalMessageInfo

func (m *CreateFeeCheckLogReq) GetStatus() FeeCheckLogStatus {
	if m != nil {
		return m.Status
	}
	return FeeCheckLogStatus_PROCESSING
}

func (m *CreateFeeCheckLogReq) GetTimeType() CreateFeeCheckLogReq_TimeType {
	if m != nil {
		return m.TimeType
	}
	return CreateFeeCheckLogReq_DAY
}

func (m *CreateFeeCheckLogReq) GetTimestamp() int64 {
	if m != nil {
		return m.Timestamp
	}
	return 0
}

func (m *CreateFeeCheckLogReq) GetMerchantId() string {
	if m != nil {
		return m.MerchantId
	}
	return ""
}

func (m *CreateFeeCheckLogReq) GetServiceType() string {
	if m != nil {
		return m.ServiceType
	}
	return ""
}

func (m *CreateFeeCheckLogReq) GetTransType() string {
	if m != nil {
		return m.TransType
	}
	return ""
}

func (m *CreateFeeCheckLogReq) GetTesting() bool {
	if m != nil {
		return m.Testing
	}
	return false
}

type CreateFeeCheckLogPeriodReq struct {
	MerchantId           string   `protobuf:"bytes,1,opt,name=merchant_id,json=merchantId,proto3" json:"merchant_id,omitempty"`
	ServiceType          string   `protobuf:"bytes,2,opt,name=service_type,json=serviceType,proto3" json:"service_type,omitempty"`
	TransType            string   `protobuf:"bytes,3,opt,name=trans_type,json=transType,proto3" json:"trans_type,omitempty"`
	TimeBegin            int64    `protobuf:"varint,4,opt,name=time_begin,json=timeBegin,proto3" json:"time_begin,omitempty"`
	TimeEnd              int64    `protobuf:"varint,5,opt,name=time_end,json=timeEnd,proto3" json:"time_end,omitempty"`
	Testing              bool     `protobuf:"varint,6,opt,name=testing,proto3" json:"testing,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *CreateFeeCheckLogPeriodReq) Reset()         { *m = CreateFeeCheckLogPeriodReq{} }
func (m *CreateFeeCheckLogPeriodReq) String() string { return proto.CompactTextString(m) }
func (*CreateFeeCheckLogPeriodReq) ProtoMessage()    {}
func (*CreateFeeCheckLogPeriodReq) Descriptor() ([]byte, []int) {
	return fileDescriptor_service_6256f3cfcc50a5b4, []int{5}
}
func (m *CreateFeeCheckLogPeriodReq) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_CreateFeeCheckLogPeriodReq.Unmarshal(m, b)
}
func (m *CreateFeeCheckLogPeriodReq) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_CreateFeeCheckLogPeriodReq.Marshal(b, m, deterministic)
}
func (dst *CreateFeeCheckLogPeriodReq) XXX_Merge(src proto.Message) {
	xxx_messageInfo_CreateFeeCheckLogPeriodReq.Merge(dst, src)
}
func (m *CreateFeeCheckLogPeriodReq) XXX_Size() int {
	return xxx_messageInfo_CreateFeeCheckLogPeriodReq.Size(m)
}
func (m *CreateFeeCheckLogPeriodReq) XXX_DiscardUnknown() {
	xxx_messageInfo_CreateFeeCheckLogPeriodReq.DiscardUnknown(m)
}

var xxx_messageInfo_CreateFeeCheckLogPeriodReq proto.InternalMessageInfo

func (m *CreateFeeCheckLogPeriodReq) GetMerchantId() string {
	if m != nil {
		return m.MerchantId
	}
	return ""
}

func (m *CreateFeeCheckLogPeriodReq) GetServiceType() string {
	if m != nil {
		return m.ServiceType
	}
	return ""
}

func (m *CreateFeeCheckLogPeriodReq) GetTransType() string {
	if m != nil {
		return m.TransType
	}
	return ""
}

func (m *CreateFeeCheckLogPeriodReq) GetTimeBegin() int64 {
	if m != nil {
		return m.TimeBegin
	}
	return 0
}

func (m *CreateFeeCheckLogPeriodReq) GetTimeEnd() int64 {
	if m != nil {
		return m.TimeEnd
	}
	return 0
}

func (m *CreateFeeCheckLogPeriodReq) GetTesting() bool {
	if m != nil {
		return m.Testing
	}
	return false
}

type CreateFeeCheckLogRes struct {
	Success              bool     `protobuf:"varint,1,opt,name=success,proto3" json:"success,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *CreateFeeCheckLogRes) Reset()         { *m = CreateFeeCheckLogRes{} }
func (m *CreateFeeCheckLogRes) String() string { return proto.CompactTextString(m) }
func (*CreateFeeCheckLogRes) ProtoMessage()    {}
func (*CreateFeeCheckLogRes) Descriptor() ([]byte, []int) {
	return fileDescriptor_service_6256f3cfcc50a5b4, []int{6}
}
func (m *CreateFeeCheckLogRes) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_CreateFeeCheckLogRes.Unmarshal(m, b)
}
func (m *CreateFeeCheckLogRes) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_CreateFeeCheckLogRes.Marshal(b, m, deterministic)
}
func (dst *CreateFeeCheckLogRes) XXX_Merge(src proto.Message) {
	xxx_messageInfo_CreateFeeCheckLogRes.Merge(dst, src)
}
func (m *CreateFeeCheckLogRes) XXX_Size() int {
	return xxx_messageInfo_CreateFeeCheckLogRes.Size(m)
}
func (m *CreateFeeCheckLogRes) XXX_DiscardUnknown() {
	xxx_messageInfo_CreateFeeCheckLogRes.DiscardUnknown(m)
}

var xxx_messageInfo_CreateFeeCheckLogRes proto.InternalMessageInfo

func (m *CreateFeeCheckLogRes) GetSuccess() bool {
	if m != nil {
		return m.Success
	}
	return false
}

type LogTxnMerchantRes struct {
	Success              bool     `protobuf:"varint,1,opt,name=success,proto3" json:"success,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *LogTxnMerchantRes) Reset()         { *m = LogTxnMerchantRes{} }
func (m *LogTxnMerchantRes) String() string { return proto.CompactTextString(m) }
func (*LogTxnMerchantRes) ProtoMessage()    {}
func (*LogTxnMerchantRes) Descriptor() ([]byte, []int) {
	return fileDescriptor_service_6256f3cfcc50a5b4, []int{7}
}
func (m *LogTxnMerchantRes) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_LogTxnMerchantRes.Unmarshal(m, b)
}
func (m *LogTxnMerchantRes) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_LogTxnMerchantRes.Marshal(b, m, deterministic)
}
func (dst *LogTxnMerchantRes) XXX_Merge(src proto.Message) {
	xxx_messageInfo_LogTxnMerchantRes.Merge(dst, src)
}
func (m *LogTxnMerchantRes) XXX_Size() int {
	return xxx_messageInfo_LogTxnMerchantRes.Size(m)
}
func (m *LogTxnMerchantRes) XXX_DiscardUnknown() {
	xxx_messageInfo_LogTxnMerchantRes.DiscardUnknown(m)
}

var xxx_messageInfo_LogTxnMerchantRes proto.InternalMessageInfo

func (m *LogTxnMerchantRes) GetSuccess() bool {
	if m != nil {
		return m.Success
	}
	return false
}

type CheckMerchantQuotaRequest struct {
	TransactionType      string   `protobuf:"bytes,1,opt,name=transaction_type,json=transactionType,proto3" json:"transaction_type,omitempty"`
	Amount               int64    `protobuf:"varint,2,opt,name=amount,proto3" json:"amount,omitempty"`
	MerchantCode         string   `protobuf:"bytes,3,opt,name=merchant_code,json=merchantCode,proto3" json:"merchant_code,omitempty"`
	MerchantId           string   `protobuf:"bytes,4,opt,name=merchant_id,json=merchantId,proto3" json:"merchant_id,omitempty"`
	PaymentChannel       string   `protobuf:"bytes,5,opt,name=payment_channel,json=paymentChannel,proto3" json:"payment_channel,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *CheckMerchantQuotaRequest) Reset()         { *m = CheckMerchantQuotaRequest{} }
func (m *CheckMerchantQuotaRequest) String() string { return proto.CompactTextString(m) }
func (*CheckMerchantQuotaRequest) ProtoMessage()    {}
func (*CheckMerchantQuotaRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_service_6256f3cfcc50a5b4, []int{8}
}
func (m *CheckMerchantQuotaRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_CheckMerchantQuotaRequest.Unmarshal(m, b)
}
func (m *CheckMerchantQuotaRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_CheckMerchantQuotaRequest.Marshal(b, m, deterministic)
}
func (dst *CheckMerchantQuotaRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_CheckMerchantQuotaRequest.Merge(dst, src)
}
func (m *CheckMerchantQuotaRequest) XXX_Size() int {
	return xxx_messageInfo_CheckMerchantQuotaRequest.Size(m)
}
func (m *CheckMerchantQuotaRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_CheckMerchantQuotaRequest.DiscardUnknown(m)
}

var xxx_messageInfo_CheckMerchantQuotaRequest proto.InternalMessageInfo

func (m *CheckMerchantQuotaRequest) GetTransactionType() string {
	if m != nil {
		return m.TransactionType
	}
	return ""
}

func (m *CheckMerchantQuotaRequest) GetAmount() int64 {
	if m != nil {
		return m.Amount
	}
	return 0
}

func (m *CheckMerchantQuotaRequest) GetMerchantCode() string {
	if m != nil {
		return m.MerchantCode
	}
	return ""
}

func (m *CheckMerchantQuotaRequest) GetMerchantId() string {
	if m != nil {
		return m.MerchantId
	}
	return ""
}

func (m *CheckMerchantQuotaRequest) GetPaymentChannel() string {
	if m != nil {
		return m.PaymentChannel
	}
	return ""
}

type CheckMerchantQuotaResponse struct {
	IsSatisfyLimit       bool     `protobuf:"varint,1,opt,name=is_satisfy_limit,json=isSatisfyLimit,proto3" json:"is_satisfy_limit,omitempty"`
	Code                 string   `protobuf:"bytes,2,opt,name=code,proto3" json:"code,omitempty"`
	Message              string   `protobuf:"bytes,3,opt,name=message,proto3" json:"message,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *CheckMerchantQuotaResponse) Reset()         { *m = CheckMerchantQuotaResponse{} }
func (m *CheckMerchantQuotaResponse) String() string { return proto.CompactTextString(m) }
func (*CheckMerchantQuotaResponse) ProtoMessage()    {}
func (*CheckMerchantQuotaResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_service_6256f3cfcc50a5b4, []int{9}
}
func (m *CheckMerchantQuotaResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_CheckMerchantQuotaResponse.Unmarshal(m, b)
}
func (m *CheckMerchantQuotaResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_CheckMerchantQuotaResponse.Marshal(b, m, deterministic)
}
func (dst *CheckMerchantQuotaResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_CheckMerchantQuotaResponse.Merge(dst, src)
}
func (m *CheckMerchantQuotaResponse) XXX_Size() int {
	return xxx_messageInfo_CheckMerchantQuotaResponse.Size(m)
}
func (m *CheckMerchantQuotaResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_CheckMerchantQuotaResponse.DiscardUnknown(m)
}

var xxx_messageInfo_CheckMerchantQuotaResponse proto.InternalMessageInfo

func (m *CheckMerchantQuotaResponse) GetIsSatisfyLimit() bool {
	if m != nil {
		return m.IsSatisfyLimit
	}
	return false
}

func (m *CheckMerchantQuotaResponse) GetCode() string {
	if m != nil {
		return m.Code
	}
	return ""
}

func (m *CheckMerchantQuotaResponse) GetMessage() string {
	if m != nil {
		return m.Message
	}
	return ""
}

type CheckMerchantQuotaAndFeeReq struct {
	Amount               int64    `protobuf:"varint,1,opt,name=amount,proto3" json:"amount,omitempty"`
	ServiceType          string   `protobuf:"bytes,2,opt,name=service_type,json=serviceType,proto3" json:"service_type,omitempty"`
	TransType            string   `protobuf:"bytes,3,opt,name=trans_type,json=transType,proto3" json:"trans_type,omitempty"`
	SubTransType         string   `protobuf:"bytes,4,opt,name=sub_trans_type,json=subTransType,proto3" json:"sub_trans_type,omitempty"`
	MerchantId           string   `protobuf:"bytes,5,opt,name=merchant_id,json=merchantId,proto3" json:"merchant_id,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *CheckMerchantQuotaAndFeeReq) Reset()         { *m = CheckMerchantQuotaAndFeeReq{} }
func (m *CheckMerchantQuotaAndFeeReq) String() string { return proto.CompactTextString(m) }
func (*CheckMerchantQuotaAndFeeReq) ProtoMessage()    {}
func (*CheckMerchantQuotaAndFeeReq) Descriptor() ([]byte, []int) {
	return fileDescriptor_service_6256f3cfcc50a5b4, []int{10}
}
func (m *CheckMerchantQuotaAndFeeReq) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_CheckMerchantQuotaAndFeeReq.Unmarshal(m, b)
}
func (m *CheckMerchantQuotaAndFeeReq) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_CheckMerchantQuotaAndFeeReq.Marshal(b, m, deterministic)
}
func (dst *CheckMerchantQuotaAndFeeReq) XXX_Merge(src proto.Message) {
	xxx_messageInfo_CheckMerchantQuotaAndFeeReq.Merge(dst, src)
}
func (m *CheckMerchantQuotaAndFeeReq) XXX_Size() int {
	return xxx_messageInfo_CheckMerchantQuotaAndFeeReq.Size(m)
}
func (m *CheckMerchantQuotaAndFeeReq) XXX_DiscardUnknown() {
	xxx_messageInfo_CheckMerchantQuotaAndFeeReq.DiscardUnknown(m)
}

var xxx_messageInfo_CheckMerchantQuotaAndFeeReq proto.InternalMessageInfo

func (m *CheckMerchantQuotaAndFeeReq) GetAmount() int64 {
	if m != nil {
		return m.Amount
	}
	return 0
}

func (m *CheckMerchantQuotaAndFeeReq) GetServiceType() string {
	if m != nil {
		return m.ServiceType
	}
	return ""
}

func (m *CheckMerchantQuotaAndFeeReq) GetTransType() string {
	if m != nil {
		return m.TransType
	}
	return ""
}

func (m *CheckMerchantQuotaAndFeeReq) GetSubTransType() string {
	if m != nil {
		return m.SubTransType
	}
	return ""
}

func (m *CheckMerchantQuotaAndFeeReq) GetMerchantId() string {
	if m != nil {
		return m.MerchantId
	}
	return ""
}

type CheckMerchantQuotaAndFeeRes struct {
	FeeAmount            int64                                 `protobuf:"varint,1,opt,name=fee_amount,json=feeAmount,proto3" json:"fee_amount,omitempty"`
	FeeMethod            CheckMerchantQuotaAndFeeRes_FeeMethod `protobuf:"varint,2,opt,name=fee_method,json=feeMethod,proto3,enum=service_merchant_fee.CheckMerchantQuotaAndFeeRes_FeeMethod" json:"fee_method,omitempty"`
	XXX_NoUnkeyedLiteral struct{}                              `json:"-"`
	XXX_unrecognized     []byte                                `json:"-"`
	XXX_sizecache        int32                                 `json:"-"`
}

func (m *CheckMerchantQuotaAndFeeRes) Reset()         { *m = CheckMerchantQuotaAndFeeRes{} }
func (m *CheckMerchantQuotaAndFeeRes) String() string { return proto.CompactTextString(m) }
func (*CheckMerchantQuotaAndFeeRes) ProtoMessage()    {}
func (*CheckMerchantQuotaAndFeeRes) Descriptor() ([]byte, []int) {
	return fileDescriptor_service_6256f3cfcc50a5b4, []int{11}
}
func (m *CheckMerchantQuotaAndFeeRes) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_CheckMerchantQuotaAndFeeRes.Unmarshal(m, b)
}
func (m *CheckMerchantQuotaAndFeeRes) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_CheckMerchantQuotaAndFeeRes.Marshal(b, m, deterministic)
}
func (dst *CheckMerchantQuotaAndFeeRes) XXX_Merge(src proto.Message) {
	xxx_messageInfo_CheckMerchantQuotaAndFeeRes.Merge(dst, src)
}
func (m *CheckMerchantQuotaAndFeeRes) XXX_Size() int {
	return xxx_messageInfo_CheckMerchantQuotaAndFeeRes.Size(m)
}
func (m *CheckMerchantQuotaAndFeeRes) XXX_DiscardUnknown() {
	xxx_messageInfo_CheckMerchantQuotaAndFeeRes.DiscardUnknown(m)
}

var xxx_messageInfo_CheckMerchantQuotaAndFeeRes proto.InternalMessageInfo

func (m *CheckMerchantQuotaAndFeeRes) GetFeeAmount() int64 {
	if m != nil {
		return m.FeeAmount
	}
	return 0
}

func (m *CheckMerchantQuotaAndFeeRes) GetFeeMethod() CheckMerchantQuotaAndFeeRes_FeeMethod {
	if m != nil {
		return m.FeeMethod
	}
	return CheckMerchantQuotaAndFeeRes_FEE_NOW
}

// GetMerchantVendorDiscount messages
type GetMerchantVendorDiscountCard struct {
	Provider             string   `protobuf:"bytes,1,opt,name=provider,proto3" json:"provider,omitempty"`
	CardName             string   `protobuf:"bytes,2,opt,name=card_name,json=cardName,proto3" json:"card_name,omitempty"`
	CardType             string   `protobuf:"bytes,3,opt,name=card_type,json=cardType,proto3" json:"card_type,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *GetMerchantVendorDiscountCard) Reset()         { *m = GetMerchantVendorDiscountCard{} }
func (m *GetMerchantVendorDiscountCard) String() string { return proto.CompactTextString(m) }
func (*GetMerchantVendorDiscountCard) ProtoMessage()    {}
func (*GetMerchantVendorDiscountCard) Descriptor() ([]byte, []int) {
	return fileDescriptor_service_6256f3cfcc50a5b4, []int{12}
}
func (m *GetMerchantVendorDiscountCard) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_GetMerchantVendorDiscountCard.Unmarshal(m, b)
}
func (m *GetMerchantVendorDiscountCard) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_GetMerchantVendorDiscountCard.Marshal(b, m, deterministic)
}
func (dst *GetMerchantVendorDiscountCard) XXX_Merge(src proto.Message) {
	xxx_messageInfo_GetMerchantVendorDiscountCard.Merge(dst, src)
}
func (m *GetMerchantVendorDiscountCard) XXX_Size() int {
	return xxx_messageInfo_GetMerchantVendorDiscountCard.Size(m)
}
func (m *GetMerchantVendorDiscountCard) XXX_DiscardUnknown() {
	xxx_messageInfo_GetMerchantVendorDiscountCard.DiscardUnknown(m)
}

var xxx_messageInfo_GetMerchantVendorDiscountCard proto.InternalMessageInfo

func (m *GetMerchantVendorDiscountCard) GetProvider() string {
	if m != nil {
		return m.Provider
	}
	return ""
}

func (m *GetMerchantVendorDiscountCard) GetCardName() string {
	if m != nil {
		return m.CardName
	}
	return ""
}

func (m *GetMerchantVendorDiscountCard) GetCardType() string {
	if m != nil {
		return m.CardType
	}
	return ""
}

type GetMerchantVendorDiscountReq struct {
	Amount               int64                          `protobuf:"varint,1,opt,name=amount,proto3" json:"amount,omitempty"`
	ServiceType          string                         `protobuf:"bytes,2,opt,name=service_type,json=serviceType,proto3" json:"service_type,omitempty"`
	TransType            string                         `protobuf:"bytes,3,opt,name=trans_type,json=transType,proto3" json:"trans_type,omitempty"`
	SubTransType         string                         `protobuf:"bytes,4,opt,name=sub_trans_type,json=subTransType,proto3" json:"sub_trans_type,omitempty"`
	MerchantId           string                         `protobuf:"bytes,5,opt,name=merchant_id,json=merchantId,proto3" json:"merchant_id,omitempty"`
	Card                 *GetMerchantVendorDiscountCard `protobuf:"bytes,6,opt,name=card,proto3" json:"card,omitempty"`
	XXX_NoUnkeyedLiteral struct{}                       `json:"-"`
	XXX_unrecognized     []byte                         `json:"-"`
	XXX_sizecache        int32                          `json:"-"`
}

func (m *GetMerchantVendorDiscountReq) Reset()         { *m = GetMerchantVendorDiscountReq{} }
func (m *GetMerchantVendorDiscountReq) String() string { return proto.CompactTextString(m) }
func (*GetMerchantVendorDiscountReq) ProtoMessage()    {}
func (*GetMerchantVendorDiscountReq) Descriptor() ([]byte, []int) {
	return fileDescriptor_service_6256f3cfcc50a5b4, []int{13}
}
func (m *GetMerchantVendorDiscountReq) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_GetMerchantVendorDiscountReq.Unmarshal(m, b)
}
func (m *GetMerchantVendorDiscountReq) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_GetMerchantVendorDiscountReq.Marshal(b, m, deterministic)
}
func (dst *GetMerchantVendorDiscountReq) XXX_Merge(src proto.Message) {
	xxx_messageInfo_GetMerchantVendorDiscountReq.Merge(dst, src)
}
func (m *GetMerchantVendorDiscountReq) XXX_Size() int {
	return xxx_messageInfo_GetMerchantVendorDiscountReq.Size(m)
}
func (m *GetMerchantVendorDiscountReq) XXX_DiscardUnknown() {
	xxx_messageInfo_GetMerchantVendorDiscountReq.DiscardUnknown(m)
}

var xxx_messageInfo_GetMerchantVendorDiscountReq proto.InternalMessageInfo

func (m *GetMerchantVendorDiscountReq) GetAmount() int64 {
	if m != nil {
		return m.Amount
	}
	return 0
}

func (m *GetMerchantVendorDiscountReq) GetServiceType() string {
	if m != nil {
		return m.ServiceType
	}
	return ""
}

func (m *GetMerchantVendorDiscountReq) GetTransType() string {
	if m != nil {
		return m.TransType
	}
	return ""
}

func (m *GetMerchantVendorDiscountReq) GetSubTransType() string {
	if m != nil {
		return m.SubTransType
	}
	return ""
}

func (m *GetMerchantVendorDiscountReq) GetMerchantId() string {
	if m != nil {
		return m.MerchantId
	}
	return ""
}

func (m *GetMerchantVendorDiscountReq) GetCard() *GetMerchantVendorDiscountCard {
	if m != nil {
		return m.Card
	}
	return nil
}

type GetMerchantVendorDiscountRes struct {
	MerchantDiscountAmount int64    `protobuf:"varint,3,opt,name=merchant_discount_amount,json=merchantDiscountAmount,proto3" json:"merchant_discount_amount,omitempty"`
	VendorDiscountAmount   int64    `protobuf:"varint,4,opt,name=vendor_discount_amount,json=vendorDiscountAmount,proto3" json:"vendor_discount_amount,omitempty"`
	XXX_NoUnkeyedLiteral   struct{} `json:"-"`
	XXX_unrecognized       []byte   `json:"-"`
	XXX_sizecache          int32    `json:"-"`
}

func (m *GetMerchantVendorDiscountRes) Reset()         { *m = GetMerchantVendorDiscountRes{} }
func (m *GetMerchantVendorDiscountRes) String() string { return proto.CompactTextString(m) }
func (*GetMerchantVendorDiscountRes) ProtoMessage()    {}
func (*GetMerchantVendorDiscountRes) Descriptor() ([]byte, []int) {
	return fileDescriptor_service_6256f3cfcc50a5b4, []int{14}
}
func (m *GetMerchantVendorDiscountRes) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_GetMerchantVendorDiscountRes.Unmarshal(m, b)
}
func (m *GetMerchantVendorDiscountRes) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_GetMerchantVendorDiscountRes.Marshal(b, m, deterministic)
}
func (dst *GetMerchantVendorDiscountRes) XXX_Merge(src proto.Message) {
	xxx_messageInfo_GetMerchantVendorDiscountRes.Merge(dst, src)
}
func (m *GetMerchantVendorDiscountRes) XXX_Size() int {
	return xxx_messageInfo_GetMerchantVendorDiscountRes.Size(m)
}
func (m *GetMerchantVendorDiscountRes) XXX_DiscardUnknown() {
	xxx_messageInfo_GetMerchantVendorDiscountRes.DiscardUnknown(m)
}

var xxx_messageInfo_GetMerchantVendorDiscountRes proto.InternalMessageInfo

func (m *GetMerchantVendorDiscountRes) GetMerchantDiscountAmount() int64 {
	if m != nil {
		return m.MerchantDiscountAmount
	}
	return 0
}

func (m *GetMerchantVendorDiscountRes) GetVendorDiscountAmount() int64 {
	if m != nil {
		return m.VendorDiscountAmount
	}
	return 0
}

func init() {
	proto.RegisterType((*SettlementReq)(nil), "service_merchant_fee.SettlementReq")
	proto.RegisterType((*SettlementRes)(nil), "service_merchant_fee.SettlementRes")
	proto.RegisterType((*CrossCheckStatusUpdatesReq)(nil), "service_merchant_fee.CrossCheckStatusUpdatesReq")
	proto.RegisterType((*CrossCheckStatusUpdatesRes)(nil), "service_merchant_fee.CrossCheckStatusUpdatesRes")
	proto.RegisterType((*CreateFeeCheckLogReq)(nil), "service_merchant_fee.CreateFeeCheckLogReq")
	proto.RegisterType((*CreateFeeCheckLogPeriodReq)(nil), "service_merchant_fee.CreateFeeCheckLogPeriodReq")
	proto.RegisterType((*CreateFeeCheckLogRes)(nil), "service_merchant_fee.CreateFeeCheckLogRes")
	proto.RegisterType((*LogTxnMerchantRes)(nil), "service_merchant_fee.LogTxnMerchantRes")
	proto.RegisterType((*CheckMerchantQuotaRequest)(nil), "service_merchant_fee.CheckMerchantQuotaRequest")
	proto.RegisterType((*CheckMerchantQuotaResponse)(nil), "service_merchant_fee.CheckMerchantQuotaResponse")
	proto.RegisterType((*CheckMerchantQuotaAndFeeReq)(nil), "service_merchant_fee.CheckMerchantQuotaAndFeeReq")
	proto.RegisterType((*CheckMerchantQuotaAndFeeRes)(nil), "service_merchant_fee.CheckMerchantQuotaAndFeeRes")
	proto.RegisterType((*GetMerchantVendorDiscountCard)(nil), "service_merchant_fee.GetMerchantVendorDiscountCard")
	proto.RegisterType((*GetMerchantVendorDiscountReq)(nil), "service_merchant_fee.GetMerchantVendorDiscountReq")
	proto.RegisterType((*GetMerchantVendorDiscountRes)(nil), "service_merchant_fee.GetMerchantVendorDiscountRes")
	proto.RegisterEnum("service_merchant_fee.FeeCheckLogStatus", FeeCheckLogStatus_name, FeeCheckLogStatus_value)
	proto.RegisterEnum("service_merchant_fee.CreateFeeCheckLogReq_TimeType", CreateFeeCheckLogReq_TimeType_name, CreateFeeCheckLogReq_TimeType_value)
	proto.RegisterEnum("service_merchant_fee.CheckMerchantQuotaAndFeeRes_FeeMethod", CheckMerchantQuotaAndFeeRes_FeeMethod_name, CheckMerchantQuotaAndFeeRes_FeeMethod_value)
}

func init() {
	proto.RegisterFile("service_merchant_fee/service.proto", fileDescriptor_service_6256f3cfcc50a5b4)
}

var fileDescriptor_service_6256f3cfcc50a5b4 = []byte{
	// 1047 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0xd4, 0x57, 0xdd, 0x6e, 0xe3, 0x44,
	0x14, 0x8e, 0x93, 0x36, 0x3f, 0xa7, 0x6d, 0x36, 0x1d, 0x55, 0xc1, 0xcd, 0xee, 0x6a, 0x8b, 0x17,
	0xa9, 0xdd, 0x4a, 0x74, 0x4b, 0x17, 0x21, 0x10, 0x42, 0xa8, 0xa4, 0x69, 0xa9, 0xd4, 0xa6, 0xc1,
	0xc9, 0xf2, 0x77, 0x63, 0xb9, 0xf6, 0x69, 0x6a, 0x51, 0x8f, 0x53, 0xcf, 0xa4, 0x4b, 0xae, 0x90,
	0x90, 0x90, 0xb8, 0xe2, 0x91, 0x90, 0x78, 0x00, 0x2e, 0x10, 0x12, 0xcf, 0xc1, 0x23, 0xa0, 0x99,
	0xb1, 0xdd, 0xfc, 0x39, 0x4d, 0xc4, 0xd5, 0xde, 0xf9, 0x9c, 0x39, 0x7f, 0xdf, 0x37, 0x9f, 0xc7,
	0x63, 0x30, 0x18, 0x86, 0x77, 0x9e, 0x83, 0x96, 0x8f, 0xa1, 0x73, 0x6d, 0x53, 0x6e, 0x5d, 0x21,
	0xbe, 0x8c, 0x9c, 0x7b, 0xbd, 0x30, 0xe0, 0x01, 0xd9, 0x98, 0x16, 0x63, 0x3c, 0x83, 0xb5, 0x36,
	0x72, 0x7e, 0x83, 0x3e, 0x52, 0x6e, 0xe2, 0x2d, 0x29, 0x43, 0xd6, 0x73, 0x75, 0x6d, 0x4b, 0xdb,
	0x29, 0x99, 0x59, 0xcf, 0x35, 0x5e, 0x8c, 0x06, 0x30, 0xa2, 0x43, 0x81, 0xf5, 0x1d, 0x07, 0x19,
	0x93, 0x51, 0x45, 0x33, 0x36, 0x8d, 0xbf, 0x34, 0xa8, 0xd5, 0xc3, 0x80, 0xb1, 0xfa, 0x35, 0x3a,
	0x3f, 0xb4, 0xb9, 0xcd, 0xfb, 0xec, 0x75, 0xcf, 0xb5, 0x39, 0x32, 0x51, 0xf9, 0x19, 0xac, 0x24,
	0xad, 0x93, 0x16, 0x10, 0xbb, 0x4e, 0x5d, 0xb2, 0x0d, 0x8f, 0x78, 0x68, 0x53, 0x66, 0x3b, 0xdc,
	0x0b, 0xa8, 0xe5, 0xb9, 0x4c, 0xcf, 0x6e, 0xe5, 0x76, 0x4a, 0x66, 0x79, 0xc8, 0x7d, 0xea, 0x32,
	0x52, 0x85, 0x3c, 0x93, 0xd5, 0xf5, 0x9c, 0x2c, 0x12, 0x59, 0xe4, 0x13, 0xd8, 0xa4, 0xf8, 0xc6,
	0x72, 0xc4, 0x0c, 0x96, 0x23, 0x86, 0xb0, 0xb8, 0xe7, 0x23, 0xe3, 0xb6, 0xdf, 0xd3, 0x97, 0xb6,
	0xb4, 0x9d, 0x9c, 0x59, 0xa5, 0xf8, 0xe6, 0x7e, 0xc6, 0x4e, 0xbc, 0x2a, 0x4a, 0x86, 0x68, 0xb3,
	0x80, 0xea, 0xcb, 0xaa, 0xa4, 0xb2, 0x8c, 0x8f, 0x66, 0x40, 0x9a, 0xc5, 0xc5, 0xbf, 0x59, 0xd8,
	0xa8, 0x87, 0x68, 0x73, 0x3c, 0x46, 0x94, 0xc9, 0x67, 0x41, 0x57, 0xb0, 0xf0, 0x79, 0x32, 0xbb,
	0xc8, 0x28, 0x1f, 0x6c, 0xef, 0x4d, 0xdb, 0x97, 0xbd, 0xa1, 0x2c, 0xd5, 0x35, 0x01, 0xd9, 0x82,
	0x92, 0x00, 0x65, 0xf1, 0x41, 0x0f, 0xf5, 0xac, 0xac, 0xf1, 0x6a, 0x7a, 0x8d, 0x69, 0xfd, 0xf7,
	0x04, 0xe4, 0xce, 0xa0, 0x87, 0x66, 0x91, 0x47, 0x4f, 0xe4, 0x89, 0xaa, 0xa8, 0x68, 0xca, 0x49,
	0x9a, 0xee, 0x1d, 0xe3, 0xdb, 0xb6, 0x34, 0xb1, 0x6d, 0xef, 0xc2, 0x6a, 0xdc, 0x5e, 0xce, 0xa4,
	0x08, 0x5c, 0x89, 0x7c, 0xb2, 0xc3, 0x53, 0x00, 0xb9, 0x85, 0x2a, 0x20, 0x2f, 0x03, 0x4a, 0xd2,
	0x23, 0x97, 0x75, 0x28, 0x70, 0x64, 0xdc, 0xa3, 0x5d, 0xbd, 0xa0, 0x68, 0x8c, 0x4c, 0x63, 0x17,
	0x8a, 0xf1, 0xc0, 0xa4, 0x00, 0xb9, 0xa3, 0xc3, 0xef, 0x2a, 0x19, 0x52, 0x82, 0xe5, 0xf3, 0x8b,
	0x66, 0xe7, 0xcb, 0x8a, 0x46, 0x00, 0xf2, 0xad, 0x86, 0x79, 0x7a, 0x71, 0x54, 0xc9, 0x1a, 0x7f,
	0x4b, 0xf9, 0x8d, 0x41, 0x6e, 0x61, 0xe8, 0x05, 0xee, 0x5c, 0xf2, 0x1b, 0xc7, 0x91, 0x7d, 0x08,
	0x47, 0x6e, 0x1c, 0x87, 0x58, 0x16, 0x5b, 0x73, 0x89, 0x5d, 0x8f, 0x46, 0x82, 0x93, 0x4c, 0x7e,
	0x21, 0x1c, 0x64, 0x13, 0x24, 0xe7, 0x16, 0x52, 0x57, 0x92, 0x94, 0x33, 0x0b, 0xc2, 0x6e, 0x50,
	0x77, 0x98, 0x81, 0xfc, 0x28, 0x03, 0xfb, 0x53, 0x75, 0x34, 0x4b, 0x7a, 0xef, 0xc3, 0xfa, 0x59,
	0xd0, 0xed, 0xfc, 0x48, 0xcf, 0x23, 0x6c, 0xb3, 0xc3, 0xff, 0xd4, 0x60, 0x53, 0x16, 0x8e, 0xc3,
	0xbf, 0xea, 0x07, 0xdc, 0x36, 0xf1, 0xb6, 0x8f, 0x8c, 0x93, 0x17, 0x50, 0x19, 0x7e, 0x27, 0x25,
	0x6e, 0x45, 0xdd, 0xf0, 0xbb, 0x2a, 0xd1, 0x57, 0x21, 0x6f, 0xfb, 0x41, 0x9f, 0x72, 0xc9, 0x5c,
	0xce, 0x8c, 0x2c, 0xf2, 0x1c, 0xd6, 0x12, 0xe2, 0x9d, 0xc0, 0x8d, 0x79, 0x5b, 0x8d, 0x9d, 0xf5,
	0xc0, 0xc5, 0x87, 0x55, 0xb6, 0x0d, 0x8f, 0x7a, 0xf6, 0x40, 0x1c, 0x42, 0x96, 0x70, 0x51, 0xbc,
	0x89, 0x84, 0x56, 0x8e, 0xdc, 0x75, 0xe5, 0x35, 0x38, 0xd4, 0xa6, 0xc1, 0x61, 0xbd, 0x80, 0x32,
	0x24, 0x3b, 0x50, 0xf1, 0x98, 0xc5, 0x6c, 0xee, 0xb1, 0xab, 0x81, 0x75, 0xe3, 0xf9, 0x1e, 0x8f,
	0x08, 0x29, 0x7b, 0xac, 0xad, 0xdc, 0x67, 0xc2, 0x4b, 0x08, 0x2c, 0xc9, 0x69, 0x95, 0x0c, 0xe4,
	0xb3, 0x60, 0xd1, 0x47, 0xc6, 0xec, 0x6e, 0x0c, 0x22, 0x36, 0x8d, 0xdf, 0x35, 0x78, 0x3c, 0xd9,
	0xf6, 0x90, 0xba, 0xc7, 0x88, 0x42, 0x7d, 0xf7, 0xe4, 0x68, 0x23, 0xe4, 0xfc, 0x7f, 0xd1, 0xbd,
	0x07, 0x65, 0xd6, 0xbf, 0xb4, 0x86, 0x42, 0x14, 0x79, 0xab, 0xac, 0x7f, 0xd9, 0x49, 0xa2, 0xc6,
	0xf8, 0x5d, 0x1e, 0xe7, 0xd7, 0xf8, 0x63, 0x26, 0x00, 0x26, 0xa6, 0xb8, 0x42, 0xb4, 0x46, 0x40,
	0x94, 0xae, 0x10, 0x0f, 0x15, 0x8e, 0xef, 0xd5, 0xb2, 0x8f, 0xfc, 0x3a, 0x70, 0xa3, 0x63, 0xe9,
	0xd3, 0x94, 0x63, 0x29, 0xbd, 0x8b, 0x38, 0xf6, 0xce, 0x65, 0x09, 0x59, 0x5b, 0x3d, 0x1a, 0xdb,
	0x50, 0x4a, 0xfc, 0x64, 0x05, 0x0a, 0xc7, 0x8d, 0x86, 0xd5, 0xbc, 0xf8, 0xa6, 0x92, 0x21, 0x6b,
	0x50, 0x12, 0xc6, 0xd9, 0x61, 0xa7, 0x61, 0x56, 0x34, 0xa3, 0x0f, 0x4f, 0x4f, 0x90, 0xc7, 0xa5,
	0xbf, 0x46, 0xea, 0x06, 0xe1, 0x91, 0xc7, 0x1c, 0x31, 0x61, 0xdd, 0x0e, 0x5d, 0x52, 0x83, 0x62,
	0x2f, 0x0c, 0xee, 0x3c, 0x17, 0xc3, 0x48, 0xc5, 0x89, 0x4d, 0x1e, 0x43, 0xc9, 0xb1, 0x43, 0xd7,
	0xa2, 0xb6, 0x1f, 0x6f, 0x43, 0x51, 0x38, 0x9a, 0xb6, 0x8f, 0xc9, 0xe2, 0xd0, 0x16, 0xc8, 0x45,
	0xc1, 0xad, 0xf1, 0x6b, 0x16, 0x9e, 0xa4, 0xf6, 0x7d, 0x1b, 0x36, 0x9f, 0x9c, 0xc0, 0x92, 0x40,
	0x23, 0xcf, 0x9e, 0x95, 0xb4, 0xcf, 0xc9, 0x4c, 0x6a, 0x4d, 0x59, 0xc0, 0xf8, 0x4d, 0x9b, 0x49,
	0x05, 0x23, 0x1f, 0x83, 0x9e, 0x14, 0x75, 0x23, 0x7f, 0x2c, 0x2a, 0xf5, 0xe9, 0xa9, 0xc6, 0xeb,
	0x71, 0x5a, 0xa4, 0xb0, 0x0f, 0xa1, 0x7a, 0x27, 0xcb, 0x4d, 0xe4, 0xa9, 0x83, 0x76, 0xe3, 0x6e,
	0xa4, 0x99, 0xca, 0xda, 0xfd, 0x0c, 0xd6, 0x27, 0x3e, 0xa5, 0xa4, 0x0c, 0xd0, 0x32, 0x2f, 0xea,
	0x8d, 0x76, 0xfb, 0xb4, 0x79, 0x52, 0xc9, 0x08, 0x4d, 0xb5, 0x1a, 0xcd, 0x23, 0x61, 0x68, 0xc2,
	0x68, 0xbf, 0xae, 0x8b, 0xc5, 0x4a, 0xf6, 0xe0, 0x9f, 0x3c, 0x14, 0xda, 0x8a, 0x0c, 0x32, 0x00,
	0x32, 0x29, 0x5d, 0xf2, 0x72, 0x5e, 0x91, 0x47, 0x27, 0x6a, 0x6d, 0x7f, 0xfe, 0x04, 0x75, 0x66,
	0x19, 0x19, 0xf2, 0xb3, 0x06, 0x7a, 0xda, 0x6b, 0x43, 0x3e, 0x58, 0xf4, 0x35, 0xbb, 0xad, 0x2d,
	0x9c, 0xc2, 0x8c, 0x0c, 0xf9, 0x45, 0x83, 0xcd, 0xd4, 0xbd, 0x25, 0x07, 0x0b, 0x8a, 0x46, 0x8c,
	0xb1, 0x78, 0x8e, 0x98, 0xc3, 0x87, 0xf5, 0x89, 0x2f, 0x22, 0xd9, 0x9d, 0xff, 0x0a, 0x54, 0x9b,
	0x3f, 0x56, 0xb4, 0x1b, 0xc0, 0x3b, 0x29, 0xb7, 0x0a, 0xb2, 0x3f, 0x67, 0xa1, 0xe4, 0x12, 0xb2,
	0x60, 0xeb, 0x9f, 0x44, 0xeb, 0xa9, 0x97, 0xcf, 0xf4, 0xd6, 0x69, 0xd7, 0xef, 0xda, 0xa2, 0x19,
	0x62, 0x80, 0x6f, 0x01, 0xee, 0x2f, 0xff, 0xe4, 0xf9, 0xf4, 0x0a, 0x23, 0xff, 0x0f, 0xb5, 0x39,
	0x82, 0x98, 0x91, 0xb9, 0xcc, 0xcb, 0x9f, 0x92, 0x57, 0xff, 0x05, 0x00, 0x00, 0xff, 0xff, 0x8c,
	0x20, 0x03, 0x1b, 0xba, 0x0c, 0x00, 0x00,
}
