package constant

const GAPO_USER = "GAPO"

const (
	SOURCE_OF_FUND_BALANCE_WALLET     = "BALANCE_WAL"
	SOURCE_OF_FUND_BANK_ATM           = "BANK_ATM"
	SOURCE_OF_FUND_INTERNATIONAL_CARD = "INTERNATIONAL_CARD"
)
